#!/bin/bash

#SBATCH --ntasks=1
#SBATCH --cpus-per-task=4
#SBATCH --ntasks-per-node=1
#SBATCH --mem-per-cpu=4G
#SBATCH --gpus-per-node=1
#SBATCH --nodes=1
#SBATCH --partition=small-g
#SBATCH --time=24:00:00
#SBATCH --account=project_465002853
#SBATCH --output=logs/a-dutuseg/output_%j.txt

# Use node-local scratch for MIOpen DB (avoid Lustre/NFS locking issues)
MIOPEN_LOCAL="${SLURM_TMPDIR:-${TMPDIR:-/tmp}}/${USER}/miopen-${SLURM_JOB_ID}"
export MIOPEN_USER_DB_PATH="$MIOPEN_LOCAL"
export MIOPEN_CUSTOM_CACHE_DIR="$MIOPEN_LOCAL"
mkdir -p "$MIOPEN_LOCAL"
export MIOPEN_DISABLE_CACHE=1
export MIOPEN_FIND_MODE=1

# Activate conda in non-interactive shells and activate the env
source /scratch/project_465002853/miniconda3/etc/profile.d/conda.sh
conda activate /scratch/project_465002853/miniconda3/envs/detectron2

# Hugging Face cache in a directory you own
export HF_HOME="/scratch/project_465002853/hf_cache_${USER}"
mkdir -p "$HF_HOME"
export HF_HUB_DISABLE_TELEMETRY=1

export DETECTRON2_DATASETS=/scratch/project_465002853/datasets
export DUTUSEG_DATASET_ROOT=${DUTUSEG_DATASET_ROOT:-/scratch/project_465002853/datasets/dut-useg/DUT-USEG}
export DUTUSEG_MASKS_ROOT=${DUTUSEG_MASKS_ROOT:-${DUTUSEG_DATASET_ROOT}/SegmentationClassVisual}

PROJECT_ROOT=/flash/project_465002853/projects/openworldsam

CONFIG_FILE=${CONFIG_FILE:-tta/cfgs/dutuseg_c/dutuseg_c_tent.yaml}
MODEL_WEIGHTS=${MODEL_WEIGHTS:-checkpoints/dutuseg_model_final.pth}
VISION_PRETRAINED=${VISION_PRETRAINED:-checkpoints/sam2_hiera_large.pt}
OUTPUT_DIR=${OUTPUT_DIR:-./tta/output_dutuseg_c/tent}
RUN_IDX=${RUN_IDX:-0}
TTA_METHOD=${TTA_METHOD:-tent}
NUM_WORKERS=${NUM_WORKERS:-4}
DUTUSEG_NUM_CLASSES=${DUTUSEG_NUM_CLASSES:-5}
TTA_DATASET=${TTA_DATASET:-dutuseg_c_sem_seg}
TTA_DOMAIN_ROOT=${TTA_DOMAIN_ROOT:-/scratch/project_465002853/datasets/dut-useg/DUT-USEG-C/domains}
TTA_MASK_ROOT=${TTA_MASK_ROOT:-/scratch/project_465002853/datasets/dut-useg/DUT-USEG-C/masks}
TTA_BATCH_SIZE=${TTA_BATCH_SIZE:-1}
TTA_MODE=${TTA_MODE:-cont_tta}
TTA_LR=${TTA_LR:-1e-4}
TTA_OPTIM_METHOD=${TTA_OPTIM_METHOD:-SGD}
TTA_OPTIM_STEPS=${TTA_OPTIM_STEPS:-1}
TTA_ADAPT_SAM_VISUAL_ENCODER=${TTA_ADAPT_SAM_VISUAL_ENCODER:-False}
TTA_ADAPT_SAM_MASK_DECODER=${TTA_ADAPT_SAM_MASK_DECODER:-False}
TTA_ADAPT_SAM_PROMPT_ENCODER=${TTA_ADAPT_SAM_PROMPT_ENCODER:-False}
TTA_ADAPT_VLM_ENCODER=${TTA_ADAPT_VLM_ENCODER:-False}
TTA_ADAPT_SOFT_PROMPTING_TRANSFORMER=${TTA_ADAPT_SOFT_PROMPTING_TRANSFORMER:-False}
TTA_COTTA_N_AUGMENTATIONS=${TTA_COTTA_N_AUGMENTATIONS:-6}
TTA_COTTA_MT_ALPHA=${TTA_COTTA_MT_ALPHA:-0.999}
TTA_COTTA_RST=${TTA_COTTA_RST:-0.01}
TTA_COTTA_AP=${TTA_COTTA_AP:-0.9}
TTA_COTTA_STUDENT_CROPS=${TTA_COTTA_STUDENT_CROPS:-2}
TTA_COTTA_STUDENT_CROP_SCALE=${TTA_COTTA_STUDENT_CROP_SCALE:-0.5}

cd "$PROJECT_ROOT"

python run_tta.py \
  --config-file "$CONFIG_FILE" \
  --num-gpus 1 \
  --run_idx "$RUN_IDX" \
  --tta_method "$TTA_METHOD" \
  MODEL.WEIGHTS "$MODEL_WEIGHTS" \
  MODEL.OpenWorldSAM2.VISION_PRETRAINED "$VISION_PRETRAINED" \
  OUTPUT_DIR "$OUTPUT_DIR" \
  MODEL.SEM_SEG_HEAD.NUM_CLASSES "$DUTUSEG_NUM_CLASSES" \
  MODEL.OpenWorldSAM2.TEST.SEMANTIC_ON "True" \
  MODEL.OpenWorldSAM2.TEST.INSTANCE_ON "False" \
  MODEL.OpenWorldSAM2.TEST.PANOPTIC_ON "False" \
  DATASETS.TRAIN "['dutuseg_sem_seg_train']" \
  DATASETS.TEST "['dutuseg_sem_seg_val']" \
  DATALOADER.NUM_WORKERS "$NUM_WORKERS" \
  TTA.ENABLED "True" \
  TTA.METHOD "$TTA_METHOD" \
  TTA.DATASET "$TTA_DATASET" \
  TTA.BATCH_SIZE "$TTA_BATCH_SIZE" \
  TTA.TTA_MODE "$TTA_MODE" \
  TTA.NUM_WORKERS "$NUM_WORKERS" \
  TTA.INIT_WEIGHTS "$MODEL_WEIGHTS" \
  TTA.DOMAIN_ROOT "$TTA_DOMAIN_ROOT" \
  TTA.MASK_ROOT "$TTA_MASK_ROOT" \
  TTA.ADAPT.SAM_VISUAL_ENCODER "$TTA_ADAPT_SAM_VISUAL_ENCODER" \
  TTA.ADAPT.SAM_MASK_DECODER "$TTA_ADAPT_SAM_MASK_DECODER" \
  TTA.ADAPT.SAM_PROMPT_ENCODER "$TTA_ADAPT_SAM_PROMPT_ENCODER" \
  TTA.ADAPT.VLM_ENCODER "$TTA_ADAPT_VLM_ENCODER" \
  TTA.ADAPT.SOFT_PROMPTING_TRANSFORMER "$TTA_ADAPT_SOFT_PROMPTING_TRANSFORMER" \
  TTA.COTTA.N_AUGMENTATIONS "$TTA_COTTA_N_AUGMENTATIONS" \
  TTA.COTTA.MT_ALPHA "$TTA_COTTA_MT_ALPHA" \
  TTA.COTTA.RST "$TTA_COTTA_RST" \
  TTA.COTTA.AP "$TTA_COTTA_AP" \
  TTA.COTTA.STUDENT_CROPS "$TTA_COTTA_STUDENT_CROPS" \
  TTA.COTTA.STUDENT_CROP_SCALE "$TTA_COTTA_STUDENT_CROP_SCALE" \
  TTA.OPTIM.METHOD "$TTA_OPTIM_METHOD" \
  TTA.OPTIM.STEPS "$TTA_OPTIM_STEPS" \
  TTA.OPTIM.LR "$TTA_LR"
