#!/bin/bash

#SBATCH --ntasks=1
#SBATCH --cpus-per-task=4
#SBATCH --ntasks-per-node=1
#SBATCH --mem-per-cpu=4G
#SBATCH --gpus-per-node=1
#SBATCH --nodes=1
#SBATCH --partition=small-g
#SBATCH --time=24:00:00
#SBATCH --account=project_465002853
#SBATCH --output=logs/a-suim/output_%j.txt

# Use node-local scratch for MIOpen DB (avoid Lustre/NFS locking issues)
MIOPEN_LOCAL="${SLURM_TMPDIR:-${TMPDIR:-/tmp}}/${USER}/miopen-${SLURM_JOB_ID}"
export MIOPEN_USER_DB_PATH="$MIOPEN_LOCAL"
export MIOPEN_CUSTOM_CACHE_DIR="$MIOPEN_LOCAL"
mkdir -p "$MIOPEN_LOCAL"
export MIOPEN_DISABLE_CACHE=1
export MIOPEN_FIND_MODE=1

# Activate conda in non-interactive shells and activate the env
source /scratch/project_465002853/miniconda3/etc/profile.d/conda.sh
conda activate /scratch/project_465002853/miniconda3/envs/detectron2

# Hugging Face cache in a directory you own
export HF_HOME="/scratch/project_465002853/hf_cache_${USER}"
mkdir -p "$HF_HOME"
export HF_HUB_DISABLE_TELEMETRY=1

export DETECTRON2_DATASETS=/scratch/project_465002853/datasets

PROJECT_ROOT=/flash/project_465002853/projects/openworldsam

CONFIG_FILE=${CONFIG_FILE:-tta/cfgs/suim_c/suim_c_tent.yaml}
MODEL_WEIGHTS=${MODEL_WEIGHTS:-checkpoints/voc12_model_final.pth}
VOC12_MODEL_WEIGHTS=${VOC12_MODEL_WEIGHTS:-checkpoints/voc12_model_final.pth}
VISION_PRETRAINED=${VISION_PRETRAINED:-checkpoints/sam2_hiera_large.pt}
OUTPUT_DIR=${OUTPUT_DIR:-./tta/output_suim_c/tent}
RUN_IDX=${RUN_IDX:-0}
SEED=${SEED:-1}
TTA_METHOD=${TTA_METHOD:-tent}
NUM_WORKERS=${NUM_WORKERS:-4}
SUIM_NUM_CLASSES=${SUIM_NUM_CLASSES:-6}
TTA_DATASET=${TTA_DATASET:-suim_c_sem_seg}
TTA_USE_CLEAN_DATA=${TTA_USE_CLEAN_DATA:-False}
TTA_INCLUDE_CLEAN_AS_FIRST_DOMAIN=${TTA_INCLUDE_CLEAN_AS_FIRST_DOMAIN:-False}
TTA_USE_PROMPT_DOMAINS=${TTA_USE_PROMPT_DOMAINS:-False}
TTA_INCLUDE_PROMPT_CORRUPTION_DOMAINS_AS_LAST=${TTA_INCLUDE_PROMPT_CORRUPTION_DOMAINS_AS_LAST:-False}
TTA_PROMPT_DOMAIN=${TTA_PROMPT_DOMAIN:-clean}
TTA_PROMPT_DOMAIN_ROOT=${TTA_PROMPT_DOMAIN_ROOT:-}
TTA_PROMPT_DOMAIN_FILE=${TTA_PROMPT_DOMAIN_FILE:-}
TTA_DOMAIN_ROOT=${TTA_DOMAIN_ROOT:-/scratch/project_465002853/datasets/suim/SUIM-C/domains}
TTA_MASK_ROOT=${TTA_MASK_ROOT:-/scratch/project_465002853/datasets/suim/SUIM-C/masks}
TTA_BATCH_SIZE=${TTA_BATCH_SIZE:-1}
TTA_MODE=${TTA_MODE:-normal_tta}
TTA_ROUNDS=${TTA_ROUNDS:-10}
TTA_SEVERITIES=${TTA_SEVERITIES:-"[5]"}
TTA_LR=${TTA_LR:-1e-4}
TTA_OPTIM_METHOD=${TTA_OPTIM_METHOD:-SGD}
TTA_OPTIM_STEPS=${TTA_OPTIM_STEPS:-1}
TTA_ADAPT_SAM_VISUAL_ENCODER=${TTA_ADAPT_SAM_VISUAL_ENCODER:-False}
TTA_ADAPT_SAM_MASK_DECODER=${TTA_ADAPT_SAM_MASK_DECODER:-False}
TTA_ADAPT_SAM_PROMPT_ENCODER=${TTA_ADAPT_SAM_PROMPT_ENCODER:-False}
TTA_ADAPT_VLM_ENCODER=${TTA_ADAPT_VLM_ENCODER:-False}
TTA_ADAPT_SOFT_PROMPTING_TRANSFORMER=${TTA_ADAPT_SOFT_PROMPTING_TRANSFORMER:-False}
TTA_ADAPT_FULL_TRAINABLE_EXCEPT_EXCLUDED=${TTA_ADAPT_FULL_TRAINABLE_EXCEPT_EXCLUDED:-False}
TTA_COTTA_N_AUGMENTATIONS=${TTA_COTTA_N_AUGMENTATIONS:-6}
TTA_COTTA_MT_ALPHA=${TTA_COTTA_MT_ALPHA:-0.999}
TTA_COTTA_RST=${TTA_COTTA_RST:-0.01}
TTA_COTTA_AP=${TTA_COTTA_AP:-0.9}
TTA_COTTA_STUDENT_CROPS=${TTA_COTTA_STUDENT_CROPS:-2}
TTA_COTTA_STUDENT_CROP_SCALE=${TTA_COTTA_STUDENT_CROP_SCALE:-0.5}
TTA_MEMO_N_AUGMENTATIONS=${TTA_MEMO_N_AUGMENTATIONS:-6}
TTA_MEMO_AUG_BATCH_SIZE=${TTA_MEMO_AUG_BATCH_SIZE:-2}
TTA_MEMO_BN_ALPHA=${TTA_MEMO_BN_ALPHA:-0.1}
TTA_LAME_AFFINITY=${TTA_LAME_AFFINITY:-rbf}
TTA_LAME_KNN=${TTA_LAME_KNN:-5}
TTA_LAME_SIGMA=${TTA_LAME_SIGMA:-1.0}
TTA_LAME_FORCE_SYMMETRY=${TTA_LAME_FORCE_SYMMETRY:-False}
TTA_LAME_BOUND_LAMBDA=${TTA_LAME_BOUND_LAMBDA:-1.0}
TTA_LAME_MAX_STEPS=${TTA_LAME_MAX_STEPS:-100}
TTA_SANTA_LAMBDA_CE_TRG=${TTA_SANTA_LAMBDA_CE_TRG:-1.0}
TTA_SANTA_LAMBDA_CONT=${TTA_SANTA_LAMBDA_CONT:-1.0}
TTA_SANTA_TEMPERATURE=${TTA_SANTA_TEMPERATURE:-0.1}
TTA_SANTA_PROJECTION_DIM=${TTA_SANTA_PROJECTION_DIM:-128}
TTA_SANTA_CONTRAST_MODE=${TTA_SANTA_CONTRAST_MODE:-all}
TTA_SANTA_AUG_ALPHA=${TTA_SANTA_AUG_ALPHA:-0.5}
TTA_SANTA_SOURCE_DATASET=${TTA_SANTA_SOURCE_DATASET:-suim_sem_seg_val}
TTA_SANTA_SOURCE_BATCH_SIZE=${TTA_SANTA_SOURCE_BATCH_SIZE:-1}
TTA_SANTA_PROTOTYPE_MAX_SAMPLES=${TTA_SANTA_PROTOTYPE_MAX_SAMPLES:-0}
TTA_SANTA_AUG_CROP_MIN=${TTA_SANTA_AUG_CROP_MIN:-0.3}
TTA_SANTA_AUG_CROP_MAX=${TTA_SANTA_AUG_CROP_MAX:-1.0}
TTA_RPL_Q=${TTA_RPL_Q:-0.8}
TTA_SAR_MARGIN_E0=${TTA_SAR_MARGIN_E0:-0.4}
TTA_SAR_RESET_CONSTANT_EM=${TTA_SAR_RESET_CONSTANT_EM:-0.001}
TTA_SAR_RHO=${TTA_SAR_RHO:-0.05}
TTA_SAR_ADAPTIVE=${TTA_SAR_ADAPTIVE:-False}
TTA_RDUMB_D_MARGIN=${TTA_RDUMB_D_MARGIN:-0.05}
TTA_RDUMB_MARGIN_E0=${TTA_RDUMB_MARGIN_E0:-0.4}
TTA_RDUMB_PROB_EMA=${TTA_RDUMB_PROB_EMA:-0.9}
TTA_RDUMB_RESET_AFTER_NUM_SAMPLES=${TTA_RDUMB_RESET_AFTER_NUM_SAMPLES:-50}
TTA_DEYO_REWEIGHT_ENT=${TTA_DEYO_REWEIGHT_ENT:-True}
TTA_DEYO_REWEIGHT_PLPD=${TTA_DEYO_REWEIGHT_PLPD:-True}
TTA_DEYO_PLPD=${TTA_DEYO_PLPD:-0.2}
TTA_DEYO_MARGIN=${TTA_DEYO_MARGIN:-0.2}
TTA_DEYO_MARGIN_E0=${TTA_DEYO_MARGIN_E0:-0.4}
TTA_DEYO_AUG_TYPE=${TTA_DEYO_AUG_TYPE:-occ}
TTA_DEYO_OCCLUSION_SIZE=${TTA_DEYO_OCCLUSION_SIZE:-64}
TTA_DEYO_ROW_START=${TTA_DEYO_ROW_START:-0}
TTA_DEYO_COLUMN_START=${TTA_DEYO_COLUMN_START:-0}
TTA_DEYO_PATCH_LEN=${TTA_DEYO_PATCH_LEN:-4}
TTA_EATA_MARGIN_E0=${TTA_EATA_MARGIN_E0:-0.4}
TTA_EATA_D_MARGIN=${TTA_EATA_D_MARGIN:-0.05}
TTA_EATA_FISHER_ALPHA=${TTA_EATA_FISHER_ALPHA:-100.0}
TTA_EATA_NUM_SAMPLES=${TTA_EATA_NUM_SAMPLES:-100}
TTA_EATA_SOURCE_DATASET=${TTA_EATA_SOURCE_DATASET:-suim_sem_seg_val}
TTA_EATA_FISHER_BATCH_SIZE=${TTA_EATA_FISHER_BATCH_SIZE:-1}
TTA_EATA_RESET_AFTER_NUM_UPDATES=${TTA_EATA_RESET_AFTER_NUM_UPDATES:-0}
TTA_ROID_USE_WEIGHTING=${TTA_ROID_USE_WEIGHTING:-True}
TTA_ROID_USE_PRIOR_CORRECTION=${TTA_ROID_USE_PRIOR_CORRECTION:-True}
TTA_ROID_USE_CONSISTENCY=${TTA_ROID_USE_CONSISTENCY:-True}
TTA_ROID_MOMENTUM_SRC=${TTA_ROID_MOMENTUM_SRC:-0.999}
TTA_ROID_MOMENTUM_PROBS=${TTA_ROID_MOMENTUM_PROBS:-0.9}
TTA_ROID_TEMPERATURE=${TTA_ROID_TEMPERATURE:-1.0}
TTA_M2A_M=${TTA_M2A_M:-0.1}
TTA_M2A_N=${TTA_M2A_N:-3}
TTA_M2A_LAMBDA_ERL=${TTA_M2A_LAMBDA_ERL:-1.0}
TTA_M2A_LAMBDA_EML=${TTA_M2A_LAMBDA_EML:-1.0}
TTA_M2A_MARGIN=${TTA_M2A_MARGIN:-0.0}
TTA_M2A_RANDOM_MASKING=${TTA_M2A_RANDOM_MASKING:-spatial}
TTA_M2A_NUM_SQUARES=${TTA_M2A_NUM_SQUARES:-1}
TTA_M2A_MASK_TYPE=${TTA_M2A_MASK_TYPE:-binary}
TTA_M2A_SPATIAL_TYPE=${TTA_M2A_SPATIAL_TYPE:-patch}
TTA_M2A_SPECTRAL_TYPE=${TTA_M2A_SPECTRAL_TYPE:-all}
TTA_M2A_SEED=${TTA_M2A_SEED:-1}
TTA_M2A_DISABLE_MCL=${TTA_M2A_DISABLE_MCL:-False}
TTA_M2A_DISABLE_ERL=${TTA_M2A_DISABLE_ERL:-True}
TTA_M2A_DISABLE_EML=${TTA_M2A_DISABLE_EML:-False}
TTA_SMPPM_SOURCE_DATASET=${TTA_SMPPM_SOURCE_DATASET:-suim_sem_seg_val}
TTA_SMPPM_SOURCE_BATCH_SIZE=${TTA_SMPPM_SOURCE_BATCH_SIZE:-1}
TTA_SMPPM_PROTOTYPE_GRID_SIZE=${TTA_SMPPM_PROTOTYPE_GRID_SIZE:-8}

if [ "$TTA_USE_CLEAN_DATA" = "True" ]; then
  TTA_DATASET=suim_sem_seg_val
  MODEL_WEIGHTS="$VOC12_MODEL_WEIGHTS"
fi

OUTPUT_DIR="${OUTPUT_DIR}/seed_${SEED}"

cd "$PROJECT_ROOT"

python run_tta.py \
  --config-file "$CONFIG_FILE" \
  --num-gpus 1 \
  --run_idx "$RUN_IDX" \
  --seed "$SEED" \
  --tta_method "$TTA_METHOD" \
  MODEL.WEIGHTS "$MODEL_WEIGHTS" \
  MODEL.OpenWorldSAM2.VISION_PRETRAINED "$VISION_PRETRAINED" \
  OUTPUT_DIR "$OUTPUT_DIR" \
  MODEL.SEM_SEG_HEAD.NUM_CLASSES "$SUIM_NUM_CLASSES" \
  MODEL.OpenWorldSAM2.TEST.SEMANTIC_ON "True" \
  MODEL.OpenWorldSAM2.TEST.INSTANCE_ON "False" \
  MODEL.OpenWorldSAM2.TEST.PANOPTIC_ON "False" \
  DATASETS.TRAIN "['suim_sem_seg_train']" \
  DATASETS.TEST "['suim_sem_seg_val']" \
  DATALOADER.NUM_WORKERS "$NUM_WORKERS" \
  TTA.ENABLED "True" \
  TTA.METHOD "$TTA_METHOD" \
  TTA.DATASET "$TTA_DATASET" \
  TTA.BATCH_SIZE "$TTA_BATCH_SIZE" \
  TTA.USE_CLEAN_DATA "$TTA_USE_CLEAN_DATA" \
  TTA.INCLUDE_CLEAN_AS_FIRST_DOMAIN "$TTA_INCLUDE_CLEAN_AS_FIRST_DOMAIN" \
  TTA.USE_PROMPT_DOMAINS "$TTA_USE_PROMPT_DOMAINS" \
  TTA.INCLUDE_PROMPT_CORRUPTION_DOMAINS_AS_LAST "$TTA_INCLUDE_PROMPT_CORRUPTION_DOMAINS_AS_LAST" \
  TTA.PROMPT_DOMAIN "$TTA_PROMPT_DOMAIN" \
  TTA.PROMPT_DOMAIN_ROOT "$TTA_PROMPT_DOMAIN_ROOT" \
  TTA.PROMPT_DOMAIN_FILE "$TTA_PROMPT_DOMAIN_FILE" \
  TTA.TTA_MODE "$TTA_MODE" \
  TTA.TTA_ROUNDS "$TTA_ROUNDS" \
  TTA.SEVERITIES "$TTA_SEVERITIES" \
  TTA.NUM_WORKERS "$NUM_WORKERS" \
  TTA.INIT_WEIGHTS "$MODEL_WEIGHTS" \
  TTA.DOMAIN_ROOT "$TTA_DOMAIN_ROOT" \
  TTA.MASK_ROOT "$TTA_MASK_ROOT" \
  TTA.ADAPT.SAM_VISUAL_ENCODER "$TTA_ADAPT_SAM_VISUAL_ENCODER" \
  TTA.ADAPT.SAM_MASK_DECODER "$TTA_ADAPT_SAM_MASK_DECODER" \
  TTA.ADAPT.SAM_PROMPT_ENCODER "$TTA_ADAPT_SAM_PROMPT_ENCODER" \
  TTA.ADAPT.VLM_ENCODER "$TTA_ADAPT_VLM_ENCODER" \
  TTA.ADAPT.SOFT_PROMPTING_TRANSFORMER "$TTA_ADAPT_SOFT_PROMPTING_TRANSFORMER" \
  TTA.ADAPT.FULL_TRAINABLE_EXCEPT_EXCLUDED "$TTA_ADAPT_FULL_TRAINABLE_EXCEPT_EXCLUDED" \
  TTA.COTTA.N_AUGMENTATIONS "$TTA_COTTA_N_AUGMENTATIONS" \
  TTA.COTTA.MT_ALPHA "$TTA_COTTA_MT_ALPHA" \
  TTA.COTTA.RST "$TTA_COTTA_RST" \
  TTA.COTTA.AP "$TTA_COTTA_AP" \
  TTA.COTTA.STUDENT_CROPS "$TTA_COTTA_STUDENT_CROPS" \
  TTA.COTTA.STUDENT_CROP_SCALE "$TTA_COTTA_STUDENT_CROP_SCALE" \
  TTA.MEMO.N_AUGMENTATIONS "$TTA_MEMO_N_AUGMENTATIONS" \
  TTA.MEMO.AUG_BATCH_SIZE "$TTA_MEMO_AUG_BATCH_SIZE" \
  TTA.MEMO.BN_ALPHA "$TTA_MEMO_BN_ALPHA" \
  TTA.LAME.AFFINITY "$TTA_LAME_AFFINITY" \
  TTA.LAME.KNN "$TTA_LAME_KNN" \
  TTA.LAME.SIGMA "$TTA_LAME_SIGMA" \
  TTA.LAME.FORCE_SYMMETRY "$TTA_LAME_FORCE_SYMMETRY" \
  TTA.LAME.BOUND_LAMBDA "$TTA_LAME_BOUND_LAMBDA" \
  TTA.LAME.MAX_STEPS "$TTA_LAME_MAX_STEPS" \
  TTA.SANTA.LAMBDA_CE_TRG "$TTA_SANTA_LAMBDA_CE_TRG" \
  TTA.SANTA.LAMBDA_CONT "$TTA_SANTA_LAMBDA_CONT" \
  TTA.SANTA.TEMPERATURE "$TTA_SANTA_TEMPERATURE" \
  TTA.SANTA.PROJECTION_DIM "$TTA_SANTA_PROJECTION_DIM" \
  TTA.SANTA.CONTRAST_MODE "$TTA_SANTA_CONTRAST_MODE" \
  TTA.SANTA.AUG_ALPHA "$TTA_SANTA_AUG_ALPHA" \
  TTA.SANTA.SOURCE_DATASET "$TTA_SANTA_SOURCE_DATASET" \
  TTA.SANTA.SOURCE_BATCH_SIZE "$TTA_SANTA_SOURCE_BATCH_SIZE" \
  TTA.SANTA.PROTOTYPE_MAX_SAMPLES "$TTA_SANTA_PROTOTYPE_MAX_SAMPLES" \
  TTA.SANTA.AUG_CROP_MIN "$TTA_SANTA_AUG_CROP_MIN" \
  TTA.SANTA.AUG_CROP_MAX "$TTA_SANTA_AUG_CROP_MAX" \
  TTA.RPL.Q "$TTA_RPL_Q" \
  TTA.SAR.MARGIN_E0 "$TTA_SAR_MARGIN_E0" \
  TTA.SAR.RESET_CONSTANT_EM "$TTA_SAR_RESET_CONSTANT_EM" \
  TTA.SAR.RHO "$TTA_SAR_RHO" \
  TTA.SAR.ADAPTIVE "$TTA_SAR_ADAPTIVE" \
  TTA.RDUMB.D_MARGIN "$TTA_RDUMB_D_MARGIN" \
  TTA.RDUMB.MARGIN_E0 "$TTA_RDUMB_MARGIN_E0" \
  TTA.RDUMB.PROB_EMA "$TTA_RDUMB_PROB_EMA" \
  TTA.RDUMB.RESET_AFTER_NUM_SAMPLES "$TTA_RDUMB_RESET_AFTER_NUM_SAMPLES" \
  TTA.DEYO.REWEIGHT_ENT "$TTA_DEYO_REWEIGHT_ENT" \
  TTA.DEYO.REWEIGHT_PLPD "$TTA_DEYO_REWEIGHT_PLPD" \
  TTA.DEYO.PLPD "$TTA_DEYO_PLPD" \
  TTA.DEYO.MARGIN "$TTA_DEYO_MARGIN" \
  TTA.DEYO.MARGIN_E0 "$TTA_DEYO_MARGIN_E0" \
  TTA.DEYO.AUG_TYPE "$TTA_DEYO_AUG_TYPE" \
  TTA.DEYO.OCCLUSION_SIZE "$TTA_DEYO_OCCLUSION_SIZE" \
  TTA.DEYO.ROW_START "$TTA_DEYO_ROW_START" \
  TTA.DEYO.COLUMN_START "$TTA_DEYO_COLUMN_START" \
  TTA.DEYO.PATCH_LEN "$TTA_DEYO_PATCH_LEN" \
  TTA.EATA.MARGIN_E0 "$TTA_EATA_MARGIN_E0" \
  TTA.EATA.D_MARGIN "$TTA_EATA_D_MARGIN" \
  TTA.EATA.FISHER_ALPHA "$TTA_EATA_FISHER_ALPHA" \
  TTA.EATA.NUM_SAMPLES "$TTA_EATA_NUM_SAMPLES" \
  TTA.EATA.SOURCE_DATASET "$TTA_EATA_SOURCE_DATASET" \
  TTA.EATA.FISHER_BATCH_SIZE "$TTA_EATA_FISHER_BATCH_SIZE" \
  TTA.EATA.RESET_AFTER_NUM_UPDATES "$TTA_EATA_RESET_AFTER_NUM_UPDATES" \
  TTA.ROID.USE_WEIGHTING "$TTA_ROID_USE_WEIGHTING" \
  TTA.ROID.USE_PRIOR_CORRECTION "$TTA_ROID_USE_PRIOR_CORRECTION" \
  TTA.ROID.USE_CONSISTENCY "$TTA_ROID_USE_CONSISTENCY" \
  TTA.ROID.MOMENTUM_SRC "$TTA_ROID_MOMENTUM_SRC" \
  TTA.ROID.MOMENTUM_PROBS "$TTA_ROID_MOMENTUM_PROBS" \
  TTA.ROID.TEMPERATURE "$TTA_ROID_TEMPERATURE" \
  TTA.M2A.M "$TTA_M2A_M" \
  TTA.M2A.N "$TTA_M2A_N" \
  TTA.M2A.LAMBDA_ERL "$TTA_M2A_LAMBDA_ERL" \
  TTA.M2A.LAMBDA_EML "$TTA_M2A_LAMBDA_EML" \
  TTA.M2A.MARGIN "$TTA_M2A_MARGIN" \
  TTA.M2A.RANDOM_MASKING "$TTA_M2A_RANDOM_MASKING" \
  TTA.M2A.NUM_SQUARES "$TTA_M2A_NUM_SQUARES" \
  TTA.M2A.MASK_TYPE "$TTA_M2A_MASK_TYPE" \
  TTA.M2A.SPATIAL_TYPE "$TTA_M2A_SPATIAL_TYPE" \
  TTA.M2A.SPECTRAL_TYPE "$TTA_M2A_SPECTRAL_TYPE" \
  TTA.M2A.SEED "$TTA_M2A_SEED" \
  TTA.M2A.DISABLE_MCL "$TTA_M2A_DISABLE_MCL" \
  TTA.M2A.DISABLE_ERL "$TTA_M2A_DISABLE_ERL" \
  TTA.M2A.DISABLE_EML "$TTA_M2A_DISABLE_EML" \
  TTA.SMPPM.SOURCE_DATASET "$TTA_SMPPM_SOURCE_DATASET" \
  TTA.SMPPM.SOURCE_BATCH_SIZE "$TTA_SMPPM_SOURCE_BATCH_SIZE" \
  TTA.SMPPM.PROTOTYPE_GRID_SIZE "$TTA_SMPPM_PROTOTYPE_GRID_SIZE" \
  TTA.OPTIM.METHOD "$TTA_OPTIM_METHOD" \
  TTA.OPTIM.STEPS "$TTA_OPTIM_STEPS" \
  TTA.OPTIM.LR "$TTA_LR"
