
# ------
# ------ TTA_RPL_Q

SEED=1 RUN_IDX="rpl_q_character_1.6" TTA_METHOD=rpl CONFIG_FILE=tta/cfgs/suim_c/suim_c_rpl.yaml TTA_MODE="lifelong_rand_cont_tta" \
TTA_METHOD=rpl OUTPUT_DIR=./tta/output_suim_c/rpl TTA_LR=1e-3 TTA_BATCH_SIZE=1 TTA_INCLUDE_CLEAN_AS_FIRST_DOMAIN=False TTA_INCLUDE_PROMPT_CORRUPTION_DOMAINS_AS_LAST=False TTA_ADAPT_FULL_TRAINABLE_EXCEPT_EXCLUDED=False TTA_ADAPT_SAM_VISUAL_ENCODER=False TTA_ADAPT_SAM_MASK_DECODER=False TTA_ADAPT_SAM_PROMPT_ENCODER=False TTA_ADAPT_VLM_ENCODER=False TTA_ADAPT_SOFT_PROMPTING_TRANSFORMER=False TTA_USE_DATA=False TTA_USE_PROMPT_DOMAINS=True TTA_PROMPT_DOMAIN="character" \
TTA_RPL_Q=1.6 \
sbatch ./slurm_suim_tta.sh

SEED=1 RUN_IDX="rpl_q_character_0.8" TTA_METHOD=rpl CONFIG_FILE=tta/cfgs/suim_c/suim_c_rpl.yaml TTA_MODE="lifelong_rand_cont_tta" \
TTA_METHOD=rpl OUTPUT_DIR=./tta/output_suim_c/rpl TTA_LR=1e-3 TTA_BATCH_SIZE=1 TTA_INCLUDE_CLEAN_AS_FIRST_DOMAIN=False TTA_INCLUDE_PROMPT_CORRUPTION_DOMAINS_AS_LAST=False TTA_ADAPT_FULL_TRAINABLE_EXCEPT_EXCLUDED=False TTA_ADAPT_SAM_VISUAL_ENCODER=False TTA_ADAPT_SAM_MASK_DECODER=False TTA_ADAPT_SAM_PROMPT_ENCODER=False TTA_ADAPT_VLM_ENCODER=False TTA_ADAPT_SOFT_PROMPTING_TRANSFORMER=False TTA_USE_DATA=False TTA_USE_PROMPT_DOMAINS=True TTA_PROMPT_DOMAIN="character" \
TTA_RPL_Q=0.8 \
sbatch ./slurm_suim_tta.sh

SEED=1 RUN_IDX="rpl_q_character_0.4" TTA_METHOD=rpl CONFIG_FILE=tta/cfgs/suim_c/suim_c_rpl.yaml TTA_MODE="lifelong_rand_cont_tta" \
TTA_METHOD=rpl OUTPUT_DIR=./tta/output_suim_c/rpl TTA_LR=1e-3 TTA_BATCH_SIZE=1 TTA_INCLUDE_CLEAN_AS_FIRST_DOMAIN=False TTA_INCLUDE_PROMPT_CORRUPTION_DOMAINS_AS_LAST=False TTA_ADAPT_FULL_TRAINABLE_EXCEPT_EXCLUDED=False TTA_ADAPT_SAM_VISUAL_ENCODER=False TTA_ADAPT_SAM_MASK_DECODER=False TTA_ADAPT_SAM_PROMPT_ENCODER=False TTA_ADAPT_VLM_ENCODER=False TTA_ADAPT_SOFT_PROMPTING_TRANSFORMER=False TTA_USE_DATA=False TTA_USE_PROMPT_DOMAINS=True TTA_PROMPT_DOMAIN="character" \
TTA_RPL_Q=0.4 \
sbatch ./slurm_suim_tta.sh

SEED=1 RUN_IDX="rpl_q_character_0.2" TTA_METHOD=rpl CONFIG_FILE=tta/cfgs/suim_c/suim_c_rpl.yaml TTA_MODE="lifelong_rand_cont_tta" \
TTA_METHOD=rpl OUTPUT_DIR=./tta/output_suim_c/rpl TTA_LR=1e-3 TTA_BATCH_SIZE=1 TTA_INCLUDE_CLEAN_AS_FIRST_DOMAIN=False TTA_INCLUDE_PROMPT_CORRUPTION_DOMAINS_AS_LAST=False TTA_ADAPT_FULL_TRAINABLE_EXCEPT_EXCLUDED=False TTA_ADAPT_SAM_VISUAL_ENCODER=False TTA_ADAPT_SAM_MASK_DECODER=False TTA_ADAPT_SAM_PROMPT_ENCODER=False TTA_ADAPT_VLM_ENCODER=False TTA_ADAPT_SOFT_PROMPTING_TRANSFORMER=False TTA_USE_DATA=False TTA_USE_PROMPT_DOMAINS=True TTA_PROMPT_DOMAIN="character" \
TTA_RPL_Q=0.2 \
sbatch ./slurm_suim_tta.sh

SEED=1 RUN_IDX="rpl_q_character_0.1" TTA_METHOD=rpl CONFIG_FILE=tta/cfgs/suim_c/suim_c_rpl.yaml TTA_MODE="lifelong_rand_cont_tta" \
TTA_METHOD=rpl OUTPUT_DIR=./tta/output_suim_c/rpl TTA_LR=1e-3 TTA_BATCH_SIZE=1 TTA_INCLUDE_CLEAN_AS_FIRST_DOMAIN=False TTA_INCLUDE_PROMPT_CORRUPTION_DOMAINS_AS_LAST=False TTA_ADAPT_FULL_TRAINABLE_EXCEPT_EXCLUDED=False TTA_ADAPT_SAM_VISUAL_ENCODER=False TTA_ADAPT_SAM_MASK_DECODER=False TTA_ADAPT_SAM_PROMPT_ENCODER=False TTA_ADAPT_VLM_ENCODER=False TTA_ADAPT_SOFT_PROMPTING_TRANSFORMER=False TTA_USE_DATA=False TTA_USE_PROMPT_DOMAINS=True TTA_PROMPT_DOMAIN="character" \
TTA_RPL_Q=0.1 \
sbatch ./slurm_suim_tta.sh

SEED=1 RUN_IDX="rpl_q_character_0.0" TTA_METHOD=rpl CONFIG_FILE=tta/cfgs/suim_c/suim_c_rpl.yaml TTA_MODE="lifelong_rand_cont_tta" \
TTA_METHOD=rpl OUTPUT_DIR=./tta/output_suim_c/rpl TTA_LR=1e-3 TTA_BATCH_SIZE=1 TTA_INCLUDE_CLEAN_AS_FIRST_DOMAIN=False TTA_INCLUDE_PROMPT_CORRUPTION_DOMAINS_AS_LAST=False TTA_ADAPT_FULL_TRAINABLE_EXCEPT_EXCLUDED=False TTA_ADAPT_SAM_VISUAL_ENCODER=False TTA_ADAPT_SAM_MASK_DECODER=False TTA_ADAPT_SAM_PROMPT_ENCODER=False TTA_ADAPT_VLM_ENCODER=False TTA_ADAPT_SOFT_PROMPTING_TRANSFORMER=False TTA_USE_DATA=False TTA_USE_PROMPT_DOMAINS=True TTA_PROMPT_DOMAIN="character" \
TTA_RPL_Q=0.0 \
sbatch ./slurm_suim_tta.sh

# ------
# ------ TTA_RPL_PL

SEED=1 RUN_IDX="rpl_spl_character_0.2" TTA_METHOD=rpl CONFIG_FILE=tta/cfgs/suim_c/suim_c_rpl.yaml TTA_MODE="lifelong_rand_cont_tta" \
TTA_METHOD=rpl OUTPUT_DIR=./tta/output_suim_c/rpl TTA_LR=1e-3 TTA_BATCH_SIZE=1 TTA_INCLUDE_CLEAN_AS_FIRST_DOMAIN=False TTA_INCLUDE_PROMPT_CORRUPTION_DOMAINS_AS_LAST=False TTA_ADAPT_FULL_TRAINABLE_EXCEPT_EXCLUDED=False TTA_ADAPT_SAM_VISUAL_ENCODER=False TTA_ADAPT_SAM_MASK_DECODER=False TTA_ADAPT_SAM_PROMPT_ENCODER=False TTA_ADAPT_VLM_ENCODER=False TTA_ADAPT_SOFT_PROMPTING_TRANSFORMER=False TTA_USE_DATA=False TTA_USE_PROMPT_DOMAINS=True TTA_PROMPT_DOMAIN="character" \
TTA_RPL_PSEUDO_LABEL_TYPE="soft" TTA_RPL_TEMPERATURE=0.2 \
sbatch ./slurm_suim_tta.sh

SEED=1 RUN_IDX="rpl_spl_character_0.4" TTA_METHOD=rpl CONFIG_FILE=tta/cfgs/suim_c/suim_c_rpl.yaml TTA_MODE="lifelong_rand_cont_tta" \
TTA_METHOD=rpl OUTPUT_DIR=./tta/output_suim_c/rpl TTA_LR=1e-3 TTA_BATCH_SIZE=1 TTA_INCLUDE_CLEAN_AS_FIRST_DOMAIN=False TTA_INCLUDE_PROMPT_CORRUPTION_DOMAINS_AS_LAST=False TTA_ADAPT_FULL_TRAINABLE_EXCEPT_EXCLUDED=False TTA_ADAPT_SAM_VISUAL_ENCODER=False TTA_ADAPT_SAM_MASK_DECODER=False TTA_ADAPT_SAM_PROMPT_ENCODER=False TTA_ADAPT_VLM_ENCODER=False TTA_ADAPT_SOFT_PROMPTING_TRANSFORMER=False TTA_USE_DATA=False TTA_USE_PROMPT_DOMAINS=True TTA_PROMPT_DOMAIN="character" \
TTA_RPL_PSEUDO_LABEL_TYPE="soft" TTA_RPL_TEMPERATURE=0.4 \
sbatch ./slurm_suim_tta.sh

SEED=1 RUN_IDX="rpl_spl_character_0.8" TTA_METHOD=rpl CONFIG_FILE=tta/cfgs/suim_c/suim_c_rpl.yaml TTA_MODE="lifelong_rand_cont_tta" \
TTA_METHOD=rpl OUTPUT_DIR=./tta/output_suim_c/rpl TTA_LR=1e-3 TTA_BATCH_SIZE=1 TTA_INCLUDE_CLEAN_AS_FIRST_DOMAIN=False TTA_INCLUDE_PROMPT_CORRUPTION_DOMAINS_AS_LAST=False TTA_ADAPT_FULL_TRAINABLE_EXCEPT_EXCLUDED=False TTA_ADAPT_SAM_VISUAL_ENCODER=False TTA_ADAPT_SAM_MASK_DECODER=False TTA_ADAPT_SAM_PROMPT_ENCODER=False TTA_ADAPT_VLM_ENCODER=False TTA_ADAPT_SOFT_PROMPTING_TRANSFORMER=False TTA_USE_DATA=False TTA_USE_PROMPT_DOMAINS=True TTA_PROMPT_DOMAIN="character" \
TTA_RPL_PSEUDO_LABEL_TYPE="soft" TTA_RPL_TEMPERATURE=0.8 \
sbatch ./slurm_suim_tta.sh

SEED=1 RUN_IDX="rpl_spl_character_1.6" TTA_METHOD=rpl CONFIG_FILE=tta/cfgs/suim_c/suim_c_rpl.yaml TTA_MODE="lifelong_rand_cont_tta" \
TTA_METHOD=rpl OUTPUT_DIR=./tta/output_suim_c/rpl TTA_LR=1e-3 TTA_BATCH_SIZE=1 TTA_INCLUDE_CLEAN_AS_FIRST_DOMAIN=False TTA_INCLUDE_PROMPT_CORRUPTION_DOMAINS_AS_LAST=False TTA_ADAPT_FULL_TRAINABLE_EXCEPT_EXCLUDED=False TTA_ADAPT_SAM_VISUAL_ENCODER=False TTA_ADAPT_SAM_MASK_DECODER=False TTA_ADAPT_SAM_PROMPT_ENCODER=False TTA_ADAPT_VLM_ENCODER=False TTA_ADAPT_SOFT_PROMPTING_TRANSFORMER=False TTA_USE_DATA=False TTA_USE_PROMPT_DOMAINS=True TTA_PROMPT_DOMAIN="character" \
TTA_RPL_PSEUDO_LABEL_TYPE="soft" TTA_RPL_TEMPERATURE=1.6 \
sbatch ./slurm_suim_tta.sh

# ------
# ------ TTA_RPL_CONFIDENCE

SEED=1 RUN_IDX="rpl_conf_character_0.0" TTA_METHOD=rpl CONFIG_FILE=tta/cfgs/suim_c/suim_c_rpl.yaml TTA_MODE="lifelong_rand_cont_tta" \
TTA_METHOD=rpl OUTPUT_DIR=./tta/output_suim_c/rpl TTA_LR=1e-3 TTA_BATCH_SIZE=1 TTA_INCLUDE_CLEAN_AS_FIRST_DOMAIN=False TTA_INCLUDE_PROMPT_CORRUPTION_DOMAINS_AS_LAST=False TTA_ADAPT_FULL_TRAINABLE_EXCEPT_EXCLUDED=False TTA_ADAPT_SAM_VISUAL_ENCODER=False TTA_ADAPT_SAM_MASK_DECODER=False TTA_ADAPT_SAM_PROMPT_ENCODER=False TTA_ADAPT_VLM_ENCODER=False TTA_ADAPT_SOFT_PROMPTING_TRANSFORMER=False TTA_USE_DATA=False TTA_USE_PROMPT_DOMAINS=True TTA_PROMPT_DOMAIN="character" \
TTA_RPL_CONFIDENCE_FILTER="max_prob" TTA_RPL_CONFIDENCE_THRESHOLD=0.0 \
sbatch ./slurm_suim_tta.sh

SEED=1 RUN_IDX="rpl_conf_character_0.1" TTA_METHOD=rpl CONFIG_FILE=tta/cfgs/suim_c/suim_c_rpl.yaml TTA_MODE="lifelong_rand_cont_tta" \
TTA_METHOD=rpl OUTPUT_DIR=./tta/output_suim_c/rpl TTA_LR=1e-3 TTA_BATCH_SIZE=1 TTA_INCLUDE_CLEAN_AS_FIRST_DOMAIN=False TTA_INCLUDE_PROMPT_CORRUPTION_DOMAINS_AS_LAST=False TTA_ADAPT_FULL_TRAINABLE_EXCEPT_EXCLUDED=False TTA_ADAPT_SAM_VISUAL_ENCODER=False TTA_ADAPT_SAM_MASK_DECODER=False TTA_ADAPT_SAM_PROMPT_ENCODER=False TTA_ADAPT_VLM_ENCODER=False TTA_ADAPT_SOFT_PROMPTING_TRANSFORMER=False TTA_USE_DATA=False TTA_USE_PROMPT_DOMAINS=True TTA_PROMPT_DOMAIN="character" \
TTA_RPL_CONFIDENCE_FILTER="max_prob" TTA_RPL_CONFIDENCE_THRESHOLD=0.1 \
sbatch ./slurm_suim_tta.sh

SEED=1 RUN_IDX="rpl_conf_character_0.2" TTA_METHOD=rpl CONFIG_FILE=tta/cfgs/suim_c/suim_c_rpl.yaml TTA_MODE="lifelong_rand_cont_tta" \
TTA_METHOD=rpl OUTPUT_DIR=./tta/output_suim_c/rpl TTA_LR=1e-3 TTA_BATCH_SIZE=1 TTA_INCLUDE_CLEAN_AS_FIRST_DOMAIN=False TTA_INCLUDE_PROMPT_CORRUPTION_DOMAINS_AS_LAST=False TTA_ADAPT_FULL_TRAINABLE_EXCEPT_EXCLUDED=False TTA_ADAPT_SAM_VISUAL_ENCODER=False TTA_ADAPT_SAM_MASK_DECODER=False TTA_ADAPT_SAM_PROMPT_ENCODER=False TTA_ADAPT_VLM_ENCODER=False TTA_ADAPT_SOFT_PROMPTING_TRANSFORMER=False TTA_USE_DATA=False TTA_USE_PROMPT_DOMAINS=True TTA_PROMPT_DOMAIN="character" \
TTA_RPL_CONFIDENCE_FILTER="max_prob" TTA_RPL_CONFIDENCE_THRESHOLD=0.2 \
sbatch ./slurm_suim_tta.sh

SEED=1 RUN_IDX="rpl_conf_character_0.4" TTA_METHOD=rpl CONFIG_FILE=tta/cfgs/suim_c/suim_c_rpl.yaml TTA_MODE="lifelong_rand_cont_tta" \
TTA_METHOD=rpl OUTPUT_DIR=./tta/output_suim_c/rpl TTA_LR=1e-3 TTA_BATCH_SIZE=1 TTA_INCLUDE_CLEAN_AS_FIRST_DOMAIN=False TTA_INCLUDE_PROMPT_CORRUPTION_DOMAINS_AS_LAST=False TTA_ADAPT_FULL_TRAINABLE_EXCEPT_EXCLUDED=False TTA_ADAPT_SAM_VISUAL_ENCODER=False TTA_ADAPT_SAM_MASK_DECODER=False TTA_ADAPT_SAM_PROMPT_ENCODER=False TTA_ADAPT_VLM_ENCODER=False TTA_ADAPT_SOFT_PROMPTING_TRANSFORMER=False TTA_USE_DATA=False TTA_USE_PROMPT_DOMAINS=True TTA_PROMPT_DOMAIN="character" \
TTA_RPL_CONFIDENCE_FILTER="max_prob" TTA_RPL_CONFIDENCE_THRESHOLD=0.4 \
sbatch ./slurm_suim_tta.sh

SEED=1 RUN_IDX="rpl_conf_character_0.8" TTA_METHOD=rpl CONFIG_FILE=tta/cfgs/suim_c/suim_c_rpl.yaml TTA_MODE="lifelong_rand_cont_tta" \
TTA_METHOD=rpl OUTPUT_DIR=./tta/output_suim_c/rpl TTA_LR=1e-3 TTA_BATCH_SIZE=1 TTA_INCLUDE_CLEAN_AS_FIRST_DOMAIN=False TTA_INCLUDE_PROMPT_CORRUPTION_DOMAINS_AS_LAST=False TTA_ADAPT_FULL_TRAINABLE_EXCEPT_EXCLUDED=False TTA_ADAPT_SAM_VISUAL_ENCODER=False TTA_ADAPT_SAM_MASK_DECODER=False TTA_ADAPT_SAM_PROMPT_ENCODER=False TTA_ADAPT_VLM_ENCODER=False TTA_ADAPT_SOFT_PROMPTING_TRANSFORMER=False TTA_USE_DATA=False TTA_USE_PROMPT_DOMAINS=True TTA_PROMPT_DOMAIN="character" \
TTA_RPL_CONFIDENCE_FILTER="max_prob" TTA_RPL_CONFIDENCE_THRESHOLD=0.8 \
sbatch ./slurm_suim_tta.sh