

# ------
# ------ source

SEED=1 RUN_IDX="source_clean" TTA_METHOD=source CONFIG_FILE=tta/cfgs/dutuseg_c/dutuseg_c_source.yaml TTA_MODE=normal_tta \
TTA_METHOD=source OUTPUT_DIR=./tta/output_dutuseg_c/source TTA_BATCH_SIZE=1 TTA_ADAPT_FULL_TRAINABLE_EXCEPT_EXCLUDED=False TTA_ADAPT_SAM_VISUAL_ENCODER=False TTA_ADAPT_SAM_MASK_DECODER=False TTA_ADAPT_SAM_PROMPT_ENCODER=False TTA_ADAPT_VLM_ENCODER=False TTA_ADAPT_SOFT_PROMPTING_TRANSFORMER=False TTA_USE_CLEAN_DATA=True \
sbatch ./slurm_dutuseg_tta.sh

SEED=1 RUN_IDX="source_clean" TTA_METHOD=source CONFIG_FILE=tta/cfgs/suim_c/suim_c_source.yaml TTA_MODE=normal_tta \
TTA_METHOD=source OUTPUT_DIR=./tta/output_suim_c/source TTA_BATCH_SIZE=1 TTA_ADAPT_FULL_TRAINABLE_EXCEPT_EXCLUDED=False TTA_ADAPT_SAM_VISUAL_ENCODER=False TTA_ADAPT_SAM_MASK_DECODER=False TTA_ADAPT_SAM_PROMPT_ENCODER=False TTA_ADAPT_VLM_ENCODER=False TTA_ADAPT_SOFT_PROMPTING_TRANSFORMER=False TTA_USE_CLEAN_DATA=True \
sbatch ./slurm_suim_tta.sh

# -------
# ------- tent

SEED=1 RUN_IDX="tent_clean_1" TTA_METHOD=tent CONFIG_FILE=tta/cfgs/dutuseg_c/dutuseg_c_tent.yaml TTA_MODE=normal_tta \
TTA_METHOD=tent OUTPUT_DIR=./tta/output_dutuseg_c/tent TTA_LR=1e-2 TTA_BATCH_SIZE=1 TTA_ADAPT_FULL_TRAINABLE_EXCEPT_EXCLUDED=False TTA_ADAPT_SAM_VISUAL_ENCODER=False TTA_ADAPT_SAM_MASK_DECODER=False TTA_ADAPT_SAM_PROMPT_ENCODER=False TTA_ADAPT_VLM_ENCODER=False TTA_ADAPT_SOFT_PROMPTING_TRANSFORMER=False TTA_USE_CLEAN_DATA=True \
sbatch ./slurm_dutuseg_tta.sh

SEED=1 RUN_IDX="tent_clean_2" TTA_METHOD=tent CONFIG_FILE=tta/cfgs/dutuseg_c/dutuseg_c_tent.yaml TTA_MODE=normal_tta \
TTA_METHOD=tent OUTPUT_DIR=./tta/output_dutuseg_c/tent TTA_LR=1e-3 TTA_BATCH_SIZE=1 TTA_ADAPT_FULL_TRAINABLE_EXCEPT_EXCLUDED=False TTA_ADAPT_SAM_VISUAL_ENCODER=False TTA_ADAPT_SAM_MASK_DECODER=False TTA_ADAPT_SAM_PROMPT_ENCODER=False TTA_ADAPT_VLM_ENCODER=False TTA_ADAPT_SOFT_PROMPTING_TRANSFORMER=False TTA_USE_CLEAN_DATA=True \
sbatch ./slurm_dutuseg_tta.sh

SEED=1 RUN_IDX="tent_clean_3" TTA_METHOD=tent CONFIG_FILE=tta/cfgs/dutuseg_c/dutuseg_c_tent.yaml TTA_MODE=normal_tta \
TTA_METHOD=tent OUTPUT_DIR=./tta/output_dutuseg_c/tent TTA_LR=1e-4 TTA_BATCH_SIZE=1 TTA_ADAPT_FULL_TRAINABLE_EXCEPT_EXCLUDED=False TTA_ADAPT_SAM_VISUAL_ENCODER=False TTA_ADAPT_SAM_MASK_DECODER=False TTA_ADAPT_SAM_PROMPT_ENCODER=False TTA_ADAPT_VLM_ENCODER=False TTA_ADAPT_SOFT_PROMPTING_TRANSFORMER=False TTA_USE_CLEAN_DATA=True \
sbatch ./slurm_dutuseg_tta.sh

# -------

SEED=1 RUN_IDX="tent_clean_1" TTA_METHOD=tent CONFIG_FILE=tta/cfgs/suim_c/suim_c_tent.yaml TTA_MODE=normal_tta \
TTA_METHOD=tent OUTPUT_DIR=./tta/output_suim_c/tent TTA_LR=1e-2 TTA_BATCH_SIZE=1 TTA_ADAPT_FULL_TRAINABLE_EXCEPT_EXCLUDED=False TTA_ADAPT_SAM_VISUAL_ENCODER=False TTA_ADAPT_SAM_MASK_DECODER=False TTA_ADAPT_SAM_PROMPT_ENCODER=False TTA_ADAPT_VLM_ENCODER=False TTA_ADAPT_SOFT_PROMPTING_TRANSFORMER=False TTA_USE_CLEAN_DATA=True \
sbatch ./slurm_suim_tta.sh

SEED=1 RUN_IDX="tent_clean_2" TTA_METHOD=tent CONFIG_FILE=tta/cfgs/suim_c/suim_c_tent.yaml TTA_MODE=normal_tta \
TTA_METHOD=tent OUTPUT_DIR=./tta/output_suim_c/tent TTA_LR=1e-3 TTA_BATCH_SIZE=1 TTA_ADAPT_FULL_TRAINABLE_EXCEPT_EXCLUDED=False TTA_ADAPT_SAM_VISUAL_ENCODER=False TTA_ADAPT_SAM_MASK_DECODER=False TTA_ADAPT_SAM_PROMPT_ENCODER=False TTA_ADAPT_VLM_ENCODER=False TTA_ADAPT_SOFT_PROMPTING_TRANSFORMER=False TTA_USE_CLEAN_DATA=True \
sbatch ./slurm_suim_tta.sh

SEED=1 RUN_IDX="tent_clean_3" TTA_METHOD=tent CONFIG_FILE=tta/cfgs/suim_c/suim_c_tent.yaml TTA_MODE=normal_tta \
TTA_METHOD=tent OUTPUT_DIR=./tta/output_suim_c/tent TTA_LR=1e-4 TTA_BATCH_SIZE=1 TTA_ADAPT_FULL_TRAINABLE_EXCEPT_EXCLUDED=False TTA_ADAPT_SAM_VISUAL_ENCODER=False TTA_ADAPT_SAM_MASK_DECODER=False TTA_ADAPT_SAM_PROMPT_ENCODER=False TTA_ADAPT_VLM_ENCODER=False TTA_ADAPT_SOFT_PROMPTING_TRANSFORMER=False TTA_USE_CLEAN_DATA=True \
sbatch ./slurm_suim_tta.sh


# ------
# ------ rpl

SEED=1 RUN_IDX="rpl_clean_1" TTA_METHOD=rpl CONFIG_FILE=tta/cfgs/dutuseg_c/dutuseg_c_rpl.yaml TTA_MODE=cont_tta \
TTA_METHOD=rpl OUTPUT_DIR=./tta/output_dutuseg_c/rpl TTA_LR=1e-2 TTA_BATCH_SIZE=1 TTA_ADAPT_FULL_TRAINABLE_EXCEPT_EXCLUDED=False TTA_ADAPT_SAM_VISUAL_ENCODER=True TTA_ADAPT_SAM_MASK_DECODER=False TTA_ADAPT_SAM_PROMPT_ENCODER=False TTA_ADAPT_VLM_ENCODER=False TTA_ADAPT_SOFT_PROMPTING_TRANSFORMER=False TTA_USE_CLEAN_DATA=True \
sbatch ./slurm_dutuseg_tta.sh

SEED=1 RUN_IDX="rpl_clean_2" TTA_METHOD=rpl CONFIG_FILE=tta/cfgs/dutuseg_c/dutuseg_c_rpl.yaml TTA_MODE=cont_tta \
TTA_METHOD=rpl OUTPUT_DIR=./tta/output_dutuseg_c/rpl TTA_LR=1e-3 TTA_BATCH_SIZE=1 TTA_ADAPT_FULL_TRAINABLE_EXCEPT_EXCLUDED=False TTA_ADAPT_SAM_VISUAL_ENCODER=True TTA_ADAPT_SAM_MASK_DECODER=False TTA_ADAPT_SAM_PROMPT_ENCODER=False TTA_ADAPT_VLM_ENCODER=False TTA_ADAPT_SOFT_PROMPTING_TRANSFORMER=False TTA_USE_CLEAN_DATA=True \
sbatch ./slurm_dutuseg_tta.sh

SEED=1 RUN_IDX="rpl_clean_3" TTA_METHOD=rpl CONFIG_FILE=tta/cfgs/dutuseg_c/dutuseg_c_rpl.yaml TTA_MODE=cont_tta \
TTA_METHOD=rpl OUTPUT_DIR=./tta/output_dutuseg_c/rpl TTA_LR=1e-4 TTA_BATCH_SIZE=1 TTA_ADAPT_FULL_TRAINABLE_EXCEPT_EXCLUDED=False TTA_ADAPT_SAM_VISUAL_ENCODER=True TTA_ADAPT_SAM_MASK_DECODER=False TTA_ADAPT_SAM_PROMPT_ENCODER=False TTA_ADAPT_VLM_ENCODER=False TTA_ADAPT_SOFT_PROMPTING_TRANSFORMER=False TTA_USE_CLEAN_DATA=True \
sbatch ./slurm_dutuseg_tta.sh

# -------

SEED=1 RUN_IDX="rpl_clean_1" TTA_METHOD=rpl CONFIG_FILE=tta/cfgs/suim_c/suim_c_rpl.yaml TTA_MODE=cont_tta \
TTA_METHOD=rpl OUTPUT_DIR=./tta/output_suim_c/rpl TTA_LR=1e-2 TTA_BATCH_SIZE=1 TTA_ADAPT_FULL_TRAINABLE_EXCEPT_EXCLUDED=False TTA_ADAPT_SAM_VISUAL_ENCODER=True TTA_ADAPT_SAM_MASK_DECODER=False TTA_ADAPT_SAM_PROMPT_ENCODER=False TTA_ADAPT_VLM_ENCODER=False TTA_ADAPT_SOFT_PROMPTING_TRANSFORMER=False TTA_USE_CLEAN_DATA=True \
sbatch ./slurm_suim_tta.sh

SEED=1 RUN_IDX="rpl_clean_2" TTA_METHOD=rpl CONFIG_FILE=tta/cfgs/suim_c/suim_c_rpl.yaml TTA_MODE=cont_tta \
TTA_METHOD=rpl OUTPUT_DIR=./tta/output_suim_c/rpl TTA_LR=1e-3 TTA_BATCH_SIZE=1 TTA_ADAPT_FULL_TRAINABLE_EXCEPT_EXCLUDED=False TTA_ADAPT_SAM_VISUAL_ENCODER=True TTA_ADAPT_SAM_MASK_DECODER=False TTA_ADAPT_SAM_PROMPT_ENCODER=False TTA_ADAPT_VLM_ENCODER=False TTA_ADAPT_SOFT_PROMPTING_TRANSFORMER=False TTA_USE_CLEAN_DATA=True \
sbatch ./slurm_suim_tta.sh

SEED=1 RUN_IDX="rpl_clean_3" TTA_METHOD=rpl CONFIG_FILE=tta/cfgs/suim_c/suim_c_rpl.yaml TTA_MODE=cont_tta \
TTA_METHOD=rpl OUTPUT_DIR=./tta/output_suim_c/rpl TTA_LR=1e-4 TTA_BATCH_SIZE=1 TTA_ADAPT_FULL_TRAINABLE_EXCEPT_EXCLUDED=False TTA_ADAPT_SAM_VISUAL_ENCODER=True TTA_ADAPT_SAM_MASK_DECODER=False TTA_ADAPT_SAM_PROMPT_ENCODER=False TTA_ADAPT_VLM_ENCODER=False TTA_ADAPT_SOFT_PROMPTING_TRANSFORMER=False TTA_USE_CLEAN_DATA=True \
sbatch ./slurm_suim_tta.sh

# ------
# ------ deyo

SEED=1 RUN_IDX="deyo_clean_1" TTA_METHOD=deyo CONFIG_FILE=tta/cfgs/dutuseg_c/dutuseg_c_deyo.yaml TTA_MODE=normal_tta \
TTA_METHOD=deyo OUTPUT_DIR=./tta/output_dutuseg_c/deyo TTA_LR=1e-2 TTA_BATCH_SIZE=1 TTA_ADAPT_FULL_TRAINABLE_EXCEPT_EXCLUDED=False TTA_ADAPT_SAM_VISUAL_ENCODER=False TTA_ADAPT_SAM_MASK_DECODER=False TTA_ADAPT_SAM_PROMPT_ENCODER=False TTA_ADAPT_VLM_ENCODER=False TTA_ADAPT_SOFT_PROMPTING_TRANSFORMER=False TTA_USE_CLEAN_DATA=True \
TTA_DEYO_MARGIN=1.0 TTA_DEYO_PLPD=0.01 \
sbatch ./slurm_dutuseg_tta.sh

SEED=1 RUN_IDX="deyo_clean_2" TTA_METHOD=deyo CONFIG_FILE=tta/cfgs/dutuseg_c/dutuseg_c_deyo.yaml TTA_MODE=normal_tta \
TTA_METHOD=deyo OUTPUT_DIR=./tta/output_dutuseg_c/deyo TTA_LR=1e-3 TTA_BATCH_SIZE=1 TTA_ADAPT_FULL_TRAINABLE_EXCEPT_EXCLUDED=False TTA_ADAPT_SAM_VISUAL_ENCODER=False TTA_ADAPT_SAM_MASK_DECODER=False TTA_ADAPT_SAM_PROMPT_ENCODER=False TTA_ADAPT_VLM_ENCODER=False TTA_ADAPT_SOFT_PROMPTING_TRANSFORMER=False TTA_USE_CLEAN_DATA=True \
TTA_DEYO_MARGIN=1.0 TTA_DEYO_PLPD=0.01 \
sbatch ./slurm_dutuseg_tta.sh

SEED=1 RUN_IDX="deyo_clean_3" TTA_METHOD=deyo CONFIG_FILE=tta/cfgs/dutuseg_c/dutuseg_c_deyo.yaml TTA_MODE=normal_tta \
TTA_METHOD=deyo OUTPUT_DIR=./tta/output_dutuseg_c/deyo TTA_LR=1e-4 TTA_BATCH_SIZE=1 TTA_ADAPT_FULL_TRAINABLE_EXCEPT_EXCLUDED=False TTA_ADAPT_SAM_VISUAL_ENCODER=False TTA_ADAPT_SAM_MASK_DECODER=False TTA_ADAPT_SAM_PROMPT_ENCODER=False TTA_ADAPT_VLM_ENCODER=False TTA_ADAPT_SOFT_PROMPTING_TRANSFORMER=False TTA_USE_CLEAN_DATA=True \
TTA_DEYO_MARGIN=1.0 TTA_DEYO_PLPD=0.01 \
sbatch ./slurm_dutuseg_tta.sh

# -------

SEED=1 RUN_IDX="deyo_clean_1" TTA_METHOD=deyo CONFIG_FILE=tta/cfgs/suim_c/suim_c_deyo.yaml TTA_MODE=normal_tta \
TTA_METHOD=deyo OUTPUT_DIR=./tta/output_suim_c/deyo TTA_LR=1e-2 TTA_BATCH_SIZE=1 TTA_ADAPT_FULL_TRAINABLE_EXCEPT_EXCLUDED=False TTA_ADAPT_SAM_VISUAL_ENCODER=False TTA_ADAPT_SAM_MASK_DECODER=False TTA_ADAPT_SAM_PROMPT_ENCODER=False TTA_ADAPT_VLM_ENCODER=False TTA_ADAPT_SOFT_PROMPTING_TRANSFORMER=False TTA_USE_CLEAN_DATA=True \
TTA_DEYO_MARGIN=1.0 TTA_DEYO_PLPD=0.01 \
sbatch ./slurm_suim_tta.sh

SEED=1 RUN_IDX="deyo_clean_2" TTA_METHOD=deyo CONFIG_FILE=tta/cfgs/suim_c/suim_c_deyo.yaml TTA_MODE=normal_tta \
TTA_METHOD=deyo OUTPUT_DIR=./tta/output_suim_c/deyo TTA_LR=1e-3 TTA_BATCH_SIZE=1 TTA_ADAPT_FULL_TRAINABLE_EXCEPT_EXCLUDED=False TTA_ADAPT_SAM_VISUAL_ENCODER=False TTA_ADAPT_SAM_MASK_DECODER=False TTA_ADAPT_SAM_PROMPT_ENCODER=False TTA_ADAPT_VLM_ENCODER=False TTA_ADAPT_SOFT_PROMPTING_TRANSFORMER=False TTA_USE_CLEAN_DATA=True \
TTA_DEYO_MARGIN=1.0 TTA_DEYO_PLPD=0.01 \
sbatch ./slurm_suim_tta.sh

SEED=1 RUN_IDX="deyo_clean_3" TTA_METHOD=deyo CONFIG_FILE=tta/cfgs/suim_c/suim_c_deyo.yaml TTA_MODE=normal_tta \
TTA_METHOD=deyo OUTPUT_DIR=./tta/output_suim_c/deyo TTA_LR=1e-4 TTA_BATCH_SIZE=1 TTA_ADAPT_FULL_TRAINABLE_EXCEPT_EXCLUDED=False TTA_ADAPT_SAM_VISUAL_ENCODER=False TTA_ADAPT_SAM_MASK_DECODER=False TTA_ADAPT_SAM_PROMPT_ENCODER=False TTA_ADAPT_VLM_ENCODER=False TTA_ADAPT_SOFT_PROMPTING_TRANSFORMER=False TTA_USE_CLEAN_DATA=True \
TTA_DEYO_MARGIN=1.0 TTA_DEYO_PLPD=0.01 \
sbatch ./slurm_suim_tta.sh


# ------
# ------ rdumb

SEED=1 RUN_IDX="rdumb_clean_1" TTA_METHOD=rdumb CONFIG_FILE=tta/cfgs/dutuseg_c/dutuseg_c_rdumb.yaml TTA_MODE=normal_tta \
TTA_METHOD=rdumb OUTPUT_DIR=./tta/output_dutuseg_c/rdumb TTA_LR=1e-2 TTA_BATCH_SIZE=1 TTA_ADAPT_FULL_TRAINABLE_EXCEPT_EXCLUDED=False TTA_ADAPT_SAM_VISUAL_ENCODER=False TTA_ADAPT_SAM_MASK_DECODER=False TTA_ADAPT_SAM_PROMPT_ENCODER=False TTA_ADAPT_VLM_ENCODER=False TTA_ADAPT_SOFT_PROMPTING_TRANSFORMER=False TTA_USE_CLEAN_DATA=True \
TTA_RDUMB_MARGIN_E0=0.8 TTA_RDUMB_D_MARGIN=0.3 TTA_RDUMB_PROB_EMA=0.9 TTA_RDUMB_RESET_AFTER_NUM_SAMPLES=0 \
sbatch ./slurm_dutuseg_tta.sh

SEED=1 RUN_IDX="rdumb_clean_2" TTA_METHOD=rdumb CONFIG_FILE=tta/cfgs/dutuseg_c/dutuseg_c_rdumb.yaml TTA_MODE=normal_tta \
TTA_METHOD=rdumb OUTPUT_DIR=./tta/output_dutuseg_c/rdumb TTA_LR=1e-3 TTA_BATCH_SIZE=1 TTA_ADAPT_FULL_TRAINABLE_EXCEPT_EXCLUDED=False TTA_ADAPT_SAM_VISUAL_ENCODER=False TTA_ADAPT_SAM_MASK_DECODER=False TTA_ADAPT_SAM_PROMPT_ENCODER=False TTA_ADAPT_VLM_ENCODER=False TTA_ADAPT_SOFT_PROMPTING_TRANSFORMER=False TTA_USE_CLEAN_DATA=True \
TTA_RDUMB_MARGIN_E0=0.8 TTA_RDUMB_D_MARGIN=0.3 TTA_RDUMB_PROB_EMA=0.9 TTA_RDUMB_RESET_AFTER_NUM_SAMPLES=0 \
sbatch ./slurm_dutuseg_tta.sh

SEED=1 RUN_IDX="rdumb_clean_3" TTA_METHOD=rdumb CONFIG_FILE=tta/cfgs/dutuseg_c/dutuseg_c_rdumb.yaml TTA_MODE=normal_tta \
TTA_METHOD=rdumb OUTPUT_DIR=./tta/output_dutuseg_c/rdumb TTA_LR=1e-4 TTA_BATCH_SIZE=1 TTA_ADAPT_FULL_TRAINABLE_EXCEPT_EXCLUDED=False TTA_ADAPT_SAM_VISUAL_ENCODER=False TTA_ADAPT_SAM_MASK_DECODER=False TTA_ADAPT_SAM_PROMPT_ENCODER=False TTA_ADAPT_VLM_ENCODER=False TTA_ADAPT_SOFT_PROMPTING_TRANSFORMER=False TTA_USE_CLEAN_DATA=True \
TTA_RDUMB_MARGIN_E0=0.8 TTA_RDUMB_D_MARGIN=0.3 TTA_RDUMB_PROB_EMA=0.9 TTA_RDUMB_RESET_AFTER_NUM_SAMPLES=0 \
sbatch ./slurm_dutuseg_tta.sh

# -------

SEED=1 RUN_IDX="rdumb_clean_1" TTA_METHOD=rdumb CONFIG_FILE=tta/cfgs/suim_c/suim_c_rdumb.yaml TTA_MODE=normal_tta \
TTA_METHOD=rdumb OUTPUT_DIR=./tta/output_suim_c/rdumb TTA_LR=1e-2 TTA_BATCH_SIZE=1 TTA_ADAPT_FULL_TRAINABLE_EXCEPT_EXCLUDED=False TTA_ADAPT_SAM_VISUAL_ENCODER=False TTA_ADAPT_SAM_MASK_DECODER=False TTA_ADAPT_SAM_PROMPT_ENCODER=False TTA_ADAPT_VLM_ENCODER=False TTA_ADAPT_SOFT_PROMPTING_TRANSFORMER=False TTA_USE_CLEAN_DATA=True \
TTA_RDUMB_MARGIN_E0=0.8 TTA_RDUMB_D_MARGIN=0.3 TTA_RDUMB_PROB_EMA=0.9 TTA_RDUMB_RESET_AFTER_NUM_SAMPLES=0 \
sbatch ./slurm_suim_tta.sh

SEED=1 RUN_IDX="rdumb_clean_2" TTA_METHOD=rdumb CONFIG_FILE=tta/cfgs/suim_c/suim_c_rdumb.yaml TTA_MODE=normal_tta \
TTA_METHOD=rdumb OUTPUT_DIR=./tta/output_suim_c/rdumb TTA_LR=1e-3 TTA_BATCH_SIZE=1 TTA_ADAPT_FULL_TRAINABLE_EXCEPT_EXCLUDED=False TTA_ADAPT_SAM_VISUAL_ENCODER=False TTA_ADAPT_SAM_MASK_DECODER=False TTA_ADAPT_SAM_PROMPT_ENCODER=False TTA_ADAPT_VLM_ENCODER=False TTA_ADAPT_SOFT_PROMPTING_TRANSFORMER=False TTA_USE_CLEAN_DATA=True \
TTA_RDUMB_MARGIN_E0=0.8 TTA_RDUMB_D_MARGIN=0.3 TTA_RDUMB_PROB_EMA=0.9 TTA_RDUMB_RESET_AFTER_NUM_SAMPLES=0 \
sbatch ./slurm_suim_tta.sh

SEED=1 RUN_IDX="rdumb_clean_3" TTA_METHOD=rdumb CONFIG_FILE=tta/cfgs/suim_c/suim_c_rdumb.yaml TTA_MODE=normal_tta \
TTA_METHOD=rdumb OUTPUT_DIR=./tta/output_suim_c/rdumb TTA_LR=1e-4 TTA_BATCH_SIZE=1 TTA_ADAPT_FULL_TRAINABLE_EXCEPT_EXCLUDED=False TTA_ADAPT_SAM_VISUAL_ENCODER=False TTA_ADAPT_SAM_MASK_DECODER=False TTA_ADAPT_SAM_PROMPT_ENCODER=False TTA_ADAPT_VLM_ENCODER=False TTA_ADAPT_SOFT_PROMPTING_TRANSFORMER=False TTA_USE_CLEAN_DATA=True \
TTA_RDUMB_MARGIN_E0=0.8 TTA_RDUMB_D_MARGIN=0.3 TTA_RDUMB_PROB_EMA=0.9 TTA_RDUMB_RESET_AFTER_NUM_SAMPLES=0 \
sbatch ./slurm_suim_tta.sh

# ------
# ------ eata

SEED=1 RUN_IDX="eata_clean_1" TTA_METHOD=eata CONFIG_FILE=tta/cfgs/dutuseg_c/dutuseg_c_eata.yaml TTA_MODE=normal_tta \
TTA_METHOD=eata OUTPUT_DIR=./tta/output_dutuseg_c/eata TTA_LR=1e-2 TTA_BATCH_SIZE=1 TTA_ADAPT_FULL_TRAINABLE_EXCEPT_EXCLUDED=False TTA_ADAPT_SAM_VISUAL_ENCODER=False TTA_ADAPT_SAM_MASK_DECODER=False TTA_ADAPT_SAM_PROMPT_ENCODER=False TTA_ADAPT_VLM_ENCODER=False TTA_ADAPT_SOFT_PROMPTING_TRANSFORMER=False TTA_USE_CLEAN_DATA=True \
TTA_EATA_MARGIN_E0=0.8 TTA_EATA_D_MARGIN=0.2 TTA_EATA_FISHER_ALPHA=0.0 TTA_EATA_NUM_SAMPLES=0 \
sbatch ./slurm_dutuseg_tta.sh

SEED=1 RUN_IDX="eata_clean_2" TTA_METHOD=eata CONFIG_FILE=tta/cfgs/dutuseg_c/dutuseg_c_eata.yaml TTA_MODE=normal_tta \
TTA_METHOD=eata OUTPUT_DIR=./tta/output_dutuseg_c/eata TTA_LR=1e-3 TTA_BATCH_SIZE=1 TTA_ADAPT_FULL_TRAINABLE_EXCEPT_EXCLUDED=False TTA_ADAPT_SAM_VISUAL_ENCODER=False TTA_ADAPT_SAM_MASK_DECODER=False TTA_ADAPT_SAM_PROMPT_ENCODER=False TTA_ADAPT_VLM_ENCODER=False TTA_ADAPT_SOFT_PROMPTING_TRANSFORMER=False TTA_USE_CLEAN_DATA=True \
TTA_EATA_MARGIN_E0=0.8 TTA_EATA_D_MARGIN=0.2 TTA_EATA_FISHER_ALPHA=0.0 TTA_EATA_NUM_SAMPLES=0 \
sbatch ./slurm_dutuseg_tta.sh

SEED=1 RUN_IDX="eata_clean_3" TTA_METHOD=eata CONFIG_FILE=tta/cfgs/dutuseg_c/dutuseg_c_eata.yaml TTA_MODE=normal_tta \
TTA_METHOD=eata OUTPUT_DIR=./tta/output_dutuseg_c/eata TTA_LR=1e-4 TTA_BATCH_SIZE=1 TTA_ADAPT_FULL_TRAINABLE_EXCEPT_EXCLUDED=False TTA_ADAPT_SAM_VISUAL_ENCODER=False TTA_ADAPT_SAM_MASK_DECODER=False TTA_ADAPT_SAM_PROMPT_ENCODER=False TTA_ADAPT_VLM_ENCODER=False TTA_ADAPT_SOFT_PROMPTING_TRANSFORMER=False TTA_USE_CLEAN_DATA=True \
TTA_EATA_MARGIN_E0=0.8 TTA_EATA_D_MARGIN=0.2 TTA_EATA_FISHER_ALPHA=0.0 TTA_EATA_NUM_SAMPLES=0 \
sbatch ./slurm_dutuseg_tta.sh

# -------

SEED=1 RUN_IDX="eata_clean_1" TTA_METHOD=eata CONFIG_FILE=tta/cfgs/suim_c/suim_c_eata.yaml TTA_MODE=normal_tta \
TTA_METHOD=eata OUTPUT_DIR=./tta/output_suim_c/eata TTA_LR=1e-2 TTA_BATCH_SIZE=1 TTA_ADAPT_FULL_TRAINABLE_EXCEPT_EXCLUDED=False TTA_ADAPT_SAM_VISUAL_ENCODER=False TTA_ADAPT_SAM_MASK_DECODER=False TTA_ADAPT_SAM_PROMPT_ENCODER=False TTA_ADAPT_VLM_ENCODER=False TTA_ADAPT_SOFT_PROMPTING_TRANSFORMER=False TTA_USE_CLEAN_DATA=True \
TTA_EATA_MARGIN_E0=0.8 TTA_EATA_D_MARGIN=0.2 TTA_EATA_FISHER_ALPHA=0.0 TTA_EATA_NUM_SAMPLES=0 \
sbatch ./slurm_suim_tta.sh

SEED=1 RUN_IDX="eata_clean_2" TTA_METHOD=eata CONFIG_FILE=tta/cfgs/suim_c/suim_c_eata.yaml TTA_MODE=normal_tta \
TTA_METHOD=eata OUTPUT_DIR=./tta/output_suim_c/eata TTA_LR=1e-3 TTA_BATCH_SIZE=1 TTA_ADAPT_FULL_TRAINABLE_EXCEPT_EXCLUDED=False TTA_ADAPT_SAM_VISUAL_ENCODER=False TTA_ADAPT_SAM_MASK_DECODER=False TTA_ADAPT_SAM_PROMPT_ENCODER=False TTA_ADAPT_VLM_ENCODER=False TTA_ADAPT_SOFT_PROMPTING_TRANSFORMER=False TTA_USE_CLEAN_DATA=True \
TTA_EATA_MARGIN_E0=0.8 TTA_EATA_D_MARGIN=0.2 TTA_EATA_FISHER_ALPHA=0.0 TTA_EATA_NUM_SAMPLES=0 \
sbatch ./slurm_suim_tta.sh

SEED=1 RUN_IDX="eata_clean_3" TTA_METHOD=eata CONFIG_FILE=tta/cfgs/suim_c/suim_c_eata.yaml TTA_MODE=normal_tta \
TTA_METHOD=eata OUTPUT_DIR=./tta/output_suim_c/eata TTA_LR=1e-4 TTA_BATCH_SIZE=1 TTA_ADAPT_FULL_TRAINABLE_EXCEPT_EXCLUDED=False TTA_ADAPT_SAM_VISUAL_ENCODER=False TTA_ADAPT_SAM_MASK_DECODER=False TTA_ADAPT_SAM_PROMPT_ENCODER=False TTA_ADAPT_VLM_ENCODER=False TTA_ADAPT_SOFT_PROMPTING_TRANSFORMER=False TTA_USE_CLEAN_DATA=True \
TTA_EATA_MARGIN_E0=0.8 TTA_EATA_D_MARGIN=0.2 TTA_EATA_FISHER_ALPHA=0.0 TTA_EATA_NUM_SAMPLES=0 \
sbatch ./slurm_suim_tta.sh

# ------
# ------ sar

SEED=1 RUN_IDX="sar_clean_1" TTA_METHOD=sar CONFIG_FILE=tta/cfgs/dutuseg_c/dutuseg_c_sar.yaml TTA_MODE=normal_tta \
TTA_METHOD=sar OUTPUT_DIR=./tta/output_dutuseg_c/sar TTA_LR=1e-2 TTA_BATCH_SIZE=1 TTA_ADAPT_FULL_TRAINABLE_EXCEPT_EXCLUDED=False TTA_ADAPT_SAM_VISUAL_ENCODER=False TTA_ADAPT_SAM_MASK_DECODER=False TTA_ADAPT_SAM_PROMPT_ENCODER=False TTA_ADAPT_VLM_ENCODER=False TTA_ADAPT_SOFT_PROMPTING_TRANSFORMER=False TTA_USE_CLEAN_DATA=True \
sbatch ./slurm_dutuseg_tta.sh

SEED=1 RUN_IDX="sar_clean_2" TTA_METHOD=sar CONFIG_FILE=tta/cfgs/dutuseg_c/dutuseg_c_sar.yaml TTA_MODE=normal_tta \
TTA_METHOD=sar OUTPUT_DIR=./tta/output_dutuseg_c/sar TTA_LR=1e-3 TTA_BATCH_SIZE=1 TTA_ADAPT_FULL_TRAINABLE_EXCEPT_EXCLUDED=False TTA_ADAPT_SAM_VISUAL_ENCODER=False TTA_ADAPT_SAM_MASK_DECODER=False TTA_ADAPT_SAM_PROMPT_ENCODER=False TTA_ADAPT_VLM_ENCODER=False TTA_ADAPT_SOFT_PROMPTING_TRANSFORMER=False TTA_USE_CLEAN_DATA=True \
sbatch ./slurm_dutuseg_tta.sh

SEED=1 RUN_IDX="sar_clean_3" TTA_METHOD=sar CONFIG_FILE=tta/cfgs/dutuseg_c/dutuseg_c_sar.yaml TTA_MODE=normal_tta \
TTA_METHOD=sar OUTPUT_DIR=./tta/output_dutuseg_c/sar TTA_LR=1e-4 TTA_BATCH_SIZE=1 TTA_ADAPT_FULL_TRAINABLE_EXCEPT_EXCLUDED=False TTA_ADAPT_SAM_VISUAL_ENCODER=False TTA_ADAPT_SAM_MASK_DECODER=False TTA_ADAPT_SAM_PROMPT_ENCODER=False TTA_ADAPT_VLM_ENCODER=False TTA_ADAPT_SOFT_PROMPTING_TRANSFORMER=False TTA_USE_CLEAN_DATA=True \
sbatch ./slurm_dutuseg_tta.sh

# -------

SEED=1 RUN_IDX="sar_clean_1" TTA_METHOD=sar CONFIG_FILE=tta/cfgs/suim_c/suim_c_sar.yaml TTA_MODE=normal_tta \
TTA_METHOD=sar OUTPUT_DIR=./tta/output_suim_c/sar TTA_LR=1e-2 TTA_BATCH_SIZE=1 TTA_ADAPT_FULL_TRAINABLE_EXCEPT_EXCLUDED=False TTA_ADAPT_SAM_VISUAL_ENCODER=False TTA_ADAPT_SAM_MASK_DECODER=False TTA_ADAPT_SAM_PROMPT_ENCODER=False TTA_ADAPT_VLM_ENCODER=False TTA_ADAPT_SOFT_PROMPTING_TRANSFORMER=False TTA_USE_CLEAN_DATA=True \
sbatch ./slurm_suim_tta.sh

SEED=1 RUN_IDX="sar_clean_2" TTA_METHOD=sar CONFIG_FILE=tta/cfgs/suim_c/suim_c_sar.yaml TTA_MODE=normal_tta \
TTA_METHOD=sar OUTPUT_DIR=./tta/output_suim_c/sar TTA_LR=1e-3 TTA_BATCH_SIZE=1 TTA_ADAPT_FULL_TRAINABLE_EXCEPT_EXCLUDED=False TTA_ADAPT_SAM_VISUAL_ENCODER=False TTA_ADAPT_SAM_MASK_DECODER=False TTA_ADAPT_SAM_PROMPT_ENCODER=False TTA_ADAPT_VLM_ENCODER=False TTA_ADAPT_SOFT_PROMPTING_TRANSFORMER=False TTA_USE_CLEAN_DATA=True \
sbatch ./slurm_suim_tta.sh

SEED=1 RUN_IDX="sar_clean_3" TTA_METHOD=sar CONFIG_FILE=tta/cfgs/suim_c/suim_c_sar.yaml TTA_MODE=normal_tta \
TTA_METHOD=sar OUTPUT_DIR=./tta/output_suim_c/sar TTA_LR=1e-4 TTA_BATCH_SIZE=1 TTA_ADAPT_FULL_TRAINABLE_EXCEPT_EXCLUDED=False TTA_ADAPT_SAM_VISUAL_ENCODER=False TTA_ADAPT_SAM_MASK_DECODER=False TTA_ADAPT_SAM_PROMPT_ENCODER=False TTA_ADAPT_VLM_ENCODER=False TTA_ADAPT_SOFT_PROMPTING_TRANSFORMER=False TTA_USE_CLEAN_DATA=True \
sbatch ./slurm_suim_tta.sh
