

# ------
# ------ source

SEED=1 RUN_IDX="source_lifelong_surface" TTA_METHOD=source CONFIG_FILE=tta/cfgs/suim_c/suim_c_source.yaml TTA_MODE="lifelong_rand_cont_tta" \
TTA_METHOD=source OUTPUT_DIR=./tta/output_suim_c/source TTA_BATCH_SIZE=1 TTA_INCLUDE_CLEAN_AS_FIRST_DOMAIN=False TTA_INCLUDE_PROMPT_CORRUPTION_DOMAINS_AS_LAST=False TTA_ADAPT_FULL_TRAINABLE_EXCEPT_EXCLUDED=False TTA_ADAPT_SAM_VISUAL_ENCODER=False TTA_ADAPT_SAM_MASK_DECODER=False TTA_ADAPT_SAM_PROMPT_ENCODER=False TTA_ADAPT_VLM_ENCODER=False TTA_ADAPT_SOFT_PROMPTING_TRANSFORMER=False TTA_USE_DATA=False TTA_USE_PROMPT_DOMAINS=True TTA_PROMPT_DOMAIN="surface" \
sbatch ./slurm_suim_tta.sh

# -------
# ------- tent

SEED=1 RUN_IDX="tent_lifelong_surface" TTA_METHOD=tent CONFIG_FILE=tta/cfgs/suim_c/suim_c_tent.yaml TTA_MODE="lifelong_rand_cont_tta" \
TTA_METHOD=tent OUTPUT_DIR=./tta/output_suim_c/tent TTA_LR=1e-3 TTA_BATCH_SIZE=1 TTA_INCLUDE_CLEAN_AS_FIRST_DOMAIN=False TTA_INCLUDE_PROMPT_CORRUPTION_DOMAINS_AS_LAST=False TTA_ADAPT_FULL_TRAINABLE_EXCEPT_EXCLUDED=False TTA_ADAPT_SAM_VISUAL_ENCODER=False TTA_ADAPT_SAM_MASK_DECODER=False TTA_ADAPT_SAM_PROMPT_ENCODER=False TTA_ADAPT_VLM_ENCODER=False TTA_ADAPT_SOFT_PROMPTING_TRANSFORMER=False TTA_USE_DATA=False TTA_USE_PROMPT_DOMAINS=True TTA_PROMPT_DOMAIN="surface" \
sbatch ./slurm_suim_tta.sh

# ------
# ------ rpl

SEED=1 RUN_IDX="rpl_lifelong_surface" TTA_METHOD=rpl CONFIG_FILE=tta/cfgs/suim_c/suim_c_rpl.yaml TTA_MODE="lifelong_rand_cont_tta" \
TTA_METHOD=rpl OUTPUT_DIR=./tta/output_suim_c/rpl TTA_LR=1e-3 TTA_BATCH_SIZE=1 TTA_INCLUDE_CLEAN_AS_FIRST_DOMAIN=False TTA_INCLUDE_PROMPT_CORRUPTION_DOMAINS_AS_LAST=False TTA_ADAPT_FULL_TRAINABLE_EXCEPT_EXCLUDED=False TTA_ADAPT_SAM_VISUAL_ENCODER=False TTA_ADAPT_SAM_MASK_DECODER=False TTA_ADAPT_SAM_PROMPT_ENCODER=False TTA_ADAPT_VLM_ENCODER=False TTA_ADAPT_SOFT_PROMPTING_TRANSFORMER=False TTA_USE_DATA=False TTA_USE_PROMPT_DOMAINS=True TTA_PROMPT_DOMAIN="surface" \
sbatch ./slurm_suim_tta.sh

# ------
# ------ deyo

SEED=1 RUN_IDX="deyo_lifelong_surface" TTA_METHOD=deyo CONFIG_FILE=tta/cfgs/suim_c/suim_c_deyo.yaml TTA_MODE="lifelong_rand_cont_tta" \
TTA_METHOD=deyo OUTPUT_DIR=./tta/output_suim_c/deyo TTA_LR=1e-3 TTA_BATCH_SIZE=1 TTA_INCLUDE_CLEAN_AS_FIRST_DOMAIN=False TTA_INCLUDE_PROMPT_CORRUPTION_DOMAINS_AS_LAST=False TTA_ADAPT_FULL_TRAINABLE_EXCEPT_EXCLUDED=False TTA_ADAPT_SAM_VISUAL_ENCODER=False TTA_ADAPT_SAM_MASK_DECODER=False TTA_ADAPT_SAM_PROMPT_ENCODER=False TTA_ADAPT_VLM_ENCODER=False TTA_ADAPT_SOFT_PROMPTING_TRANSFORMER=False TTA_USE_DATA=False TTA_USE_PROMPT_DOMAINS=True TTA_PROMPT_DOMAIN="surface" \
TTA_DEYO_MARGIN=1.0 TTA_DEYO_PLPD=0.01 \
sbatch ./slurm_suim_tta.sh

# ------
# ------ rdumb

SEED=1 RUN_IDX="rdumb_lifelong_surface" TTA_METHOD=rdumb CONFIG_FILE=tta/cfgs/suim_c/suim_c_rdumb.yaml TTA_MODE="lifelong_rand_cont_tta" \
TTA_METHOD=rdumb OUTPUT_DIR=./tta/output_suim_c/rdumb TTA_LR=1e-2 TTA_BATCH_SIZE=1 TTA_INCLUDE_CLEAN_AS_FIRST_DOMAIN=False TTA_INCLUDE_PROMPT_CORRUPTION_DOMAINS_AS_LAST=False TTA_ADAPT_FULL_TRAINABLE_EXCEPT_EXCLUDED=False TTA_ADAPT_SAM_VISUAL_ENCODER=False TTA_ADAPT_SAM_MASK_DECODER=False TTA_ADAPT_SAM_PROMPT_ENCODER=False TTA_ADAPT_VLM_ENCODER=False TTA_ADAPT_SOFT_PROMPTING_TRANSFORMER=False TTA_USE_DATA=False TTA_USE_PROMPT_DOMAINS=True TTA_PROMPT_DOMAIN="surface" \
TTA_RDUMB_MARGIN_E0=0.8 TTA_RDUMB_D_MARGIN=0.3 TTA_RDUMB_PROB_EMA=0.9 TTA_RDUMB_RESET_AFTER_NUM_SAMPLES=0 \
sbatch ./slurm_suim_tta.sh

# ------
# ------ eata

SEED=1 RUN_IDX="eata_lifelong_surface" TTA_METHOD=eata CONFIG_FILE=tta/cfgs/suim_c/suim_c_eata.yaml TTA_MODE="lifelong_rand_cont_tta" \
TTA_METHOD=eata OUTPUT_DIR=./tta/output_suim_c/eata TTA_LR=1e-2 TTA_BATCH_SIZE=1 TTA_INCLUDE_CLEAN_AS_FIRST_DOMAIN=False TTA_INCLUDE_PROMPT_CORRUPTION_DOMAINS_AS_LAST=False TTA_ADAPT_FULL_TRAINABLE_EXCEPT_EXCLUDED=False TTA_ADAPT_SAM_VISUAL_ENCODER=False TTA_ADAPT_SAM_MASK_DECODER=False TTA_ADAPT_SAM_PROMPT_ENCODER=False TTA_ADAPT_VLM_ENCODER=False TTA_ADAPT_SOFT_PROMPTING_TRANSFORMER=False TTA_USE_DATA=False TTA_USE_PROMPT_DOMAINS=True TTA_PROMPT_DOMAIN="surface" \
TTA_EATA_MARGIN_E0=0.8 TTA_EATA_D_MARGIN=0.2 TTA_EATA_FISHER_ALPHA=0.0 TTA_EATA_NUM_SAMPLES=0 \
sbatch ./slurm_suim_tta.sh

# ------
# ------ sar

SEED=1 RUN_IDX="sar_lifelong_surface" TTA_METHOD=sar CONFIG_FILE=tta/cfgs/suim_c/suim_c_sar.yaml TTA_MODE="lifelong_rand_cont_tta" \
TTA_METHOD=sar OUTPUT_DIR=./tta/output_suim_c/sar TTA_LR=1e-2 TTA_BATCH_SIZE=1 TTA_INCLUDE_CLEAN_AS_FIRST_DOMAIN=False TTA_INCLUDE_PROMPT_CORRUPTION_DOMAINS_AS_LAST=False TTA_ADAPT_FULL_TRAINABLE_EXCEPT_EXCLUDED=False TTA_ADAPT_SAM_VISUAL_ENCODER=False TTA_ADAPT_SAM_MASK_DECODER=False TTA_ADAPT_SAM_PROMPT_ENCODER=False TTA_ADAPT_VLM_ENCODER=False TTA_ADAPT_SOFT_PROMPTING_TRANSFORMER=False TTA_USE_DATA=False TTA_USE_PROMPT_DOMAINS=True TTA_PROMPT_DOMAIN="surface" \
sbatch ./slurm_suim_tta.sh

