

# -------
# ------- tent

# dutuseg_c - baseline (no adaptation)
SEED=1 RUN_IDX=1 TTA_METHOD=tent CONFIG_FILE=tta/cfgs/dutuseg_c/dutuseg_c_tent.yaml TTA_MODE=cont_tta \
TTA_METHOD=tent OUTPUT_DIR=./tta/output_dutuseg_c/tent TTA_LR=1e-2 TTA_BATCH_SIZE=1 TTA_ADAPT_FULL_TRAINABLE_EXCEPT_EXCLUDED=False TTA_ADAPT_SAM_VISUAL_ENCODER=False TTA_ADAPT_SAM_MASK_DECODER=False TTA_ADAPT_SAM_PROMPT_ENCODER=False TTA_ADAPT_VLM_ENCODER=False TTA_ADAPT_SOFT_PROMPTING_TRANSFORMER=False \
sbatch ./slurm_dutuseg_tta.sh

SEED=1 RUN_IDX=2 TTA_METHOD=tent CONFIG_FILE=tta/cfgs/dutuseg_c/dutuseg_c_tent.yaml TTA_MODE=cont_tta \
TTA_METHOD=tent OUTPUT_DIR=./tta/output_dutuseg_c/tent TTA_LR=1e-3 TTA_BATCH_SIZE=1 TTA_ADAPT_FULL_TRAINABLE_EXCEPT_EXCLUDED=False TTA_ADAPT_SAM_VISUAL_ENCODER=False TTA_ADAPT_SAM_MASK_DECODER=False TTA_ADAPT_SAM_PROMPT_ENCODER=False TTA_ADAPT_VLM_ENCODER=False TTA_ADAPT_SOFT_PROMPTING_TRANSFORMER=False \
sbatch ./slurm_dutuseg_tta.sh

SEED=1 RUN_IDX=3 TTA_METHOD=tent CONFIG_FILE=tta/cfgs/dutuseg_c/dutuseg_c_tent.yaml TTA_MODE=cont_tta \
TTA_METHOD=tent OUTPUT_DIR=./tta/output_dutuseg_c/tent TTA_LR=1e-4 TTA_BATCH_SIZE=1 TTA_ADAPT_FULL_TRAINABLE_EXCEPT_EXCLUDED=False TTA_ADAPT_SAM_VISUAL_ENCODER=False TTA_ADAPT_SAM_MASK_DECODER=False TTA_ADAPT_SAM_PROMPT_ENCODER=False TTA_ADAPT_VLM_ENCODER=False TTA_ADAPT_SOFT_PROMPTING_TRANSFORMER=False \
sbatch ./slurm_dutuseg_tta.sh

# dutuseg_c - SAM visual encoder
SEED=1 RUN_IDX=1_vis TTA_METHOD=tent CONFIG_FILE=tta/cfgs/dutuseg_c/dutuseg_c_tent.yaml TTA_MODE=cont_tta \
TTA_METHOD=tent OUTPUT_DIR=./tta/output_dutuseg_c/tent TTA_LR=1e-2 TTA_BATCH_SIZE=1 TTA_ADAPT_FULL_TRAINABLE_EXCEPT_EXCLUDED=False TTA_ADAPT_SAM_VISUAL_ENCODER=True TTA_ADAPT_SAM_MASK_DECODER=False TTA_ADAPT_SAM_PROMPT_ENCODER=False TTA_ADAPT_VLM_ENCODER=False TTA_ADAPT_SOFT_PROMPTING_TRANSFORMER=False \
sbatch ./slurm_dutuseg_tta.sh

SEED=1 RUN_IDX=2_vis TTA_METHOD=tent CONFIG_FILE=tta/cfgs/dutuseg_c/dutuseg_c_tent.yaml TTA_MODE=cont_tta \
TTA_METHOD=tent OUTPUT_DIR=./tta/output_dutuseg_c/tent TTA_LR=1e-3 TTA_BATCH_SIZE=1 TTA_ADAPT_FULL_TRAINABLE_EXCEPT_EXCLUDED=False TTA_ADAPT_SAM_VISUAL_ENCODER=True TTA_ADAPT_SAM_MASK_DECODER=False TTA_ADAPT_SAM_PROMPT_ENCODER=False TTA_ADAPT_VLM_ENCODER=False TTA_ADAPT_SOFT_PROMPTING_TRANSFORMER=False \
sbatch ./slurm_dutuseg_tta.sh

SEED=1 RUN_IDX=3_vis TTA_METHOD=tent CONFIG_FILE=tta/cfgs/dutuseg_c/dutuseg_c_tent.yaml TTA_MODE=cont_tta \
TTA_METHOD=tent OUTPUT_DIR=./tta/output_dutuseg_c/tent TTA_LR=1e-4 TTA_BATCH_SIZE=1 TTA_ADAPT_FULL_TRAINABLE_EXCEPT_EXCLUDED=False TTA_ADAPT_SAM_VISUAL_ENCODER=True TTA_ADAPT_SAM_MASK_DECODER=False TTA_ADAPT_SAM_PROMPT_ENCODER=False TTA_ADAPT_VLM_ENCODER=False TTA_ADAPT_SOFT_PROMPTING_TRANSFORMER=False \
sbatch ./slurm_dutuseg_tta.sh

# dutuseg_c - SAM mask decoder
SEED=1 RUN_IDX=1_decoder TTA_METHOD=tent CONFIG_FILE=tta/cfgs/dutuseg_c/dutuseg_c_tent.yaml TTA_MODE=cont_tta \
TTA_METHOD=tent OUTPUT_DIR=./tta/output_dutuseg_c/tent TTA_LR=1e-2 TTA_BATCH_SIZE=1 TTA_ADAPT_FULL_TRAINABLE_EXCEPT_EXCLUDED=False TTA_ADAPT_SAM_VISUAL_ENCODER=False TTA_ADAPT_SAM_MASK_DECODER=True TTA_ADAPT_SAM_PROMPT_ENCODER=False TTA_ADAPT_VLM_ENCODER=False TTA_ADAPT_SOFT_PROMPTING_TRANSFORMER=False \
sbatch ./slurm_dutuseg_tta.sh

SEED=1 RUN_IDX=2_decoder TTA_METHOD=tent CONFIG_FILE=tta/cfgs/dutuseg_c/dutuseg_c_tent.yaml TTA_MODE=cont_tta \
TTA_METHOD=tent OUTPUT_DIR=./tta/output_dutuseg_c/tent TTA_LR=1e-3 TTA_BATCH_SIZE=1 TTA_ADAPT_FULL_TRAINABLE_EXCEPT_EXCLUDED=False TTA_ADAPT_SAM_VISUAL_ENCODER=False TTA_ADAPT_SAM_MASK_DECODER=True TTA_ADAPT_SAM_PROMPT_ENCODER=False TTA_ADAPT_VLM_ENCODER=False TTA_ADAPT_SOFT_PROMPTING_TRANSFORMER=False \
sbatch ./slurm_dutuseg_tta.sh

SEED=1 RUN_IDX=3_decoder TTA_METHOD=tent CONFIG_FILE=tta/cfgs/dutuseg_c/dutuseg_c_tent.yaml TTA_MODE=cont_tta \
TTA_METHOD=tent OUTPUT_DIR=./tta/output_dutuseg_c/tent TTA_LR=1e-4 TTA_BATCH_SIZE=1 TTA_ADAPT_FULL_TRAINABLE_EXCEPT_EXCLUDED=False TTA_ADAPT_SAM_VISUAL_ENCODER=False TTA_ADAPT_SAM_MASK_DECODER=True TTA_ADAPT_SAM_PROMPT_ENCODER=False TTA_ADAPT_VLM_ENCODER=False TTA_ADAPT_SOFT_PROMPTING_TRANSFORMER=False \
sbatch ./slurm_dutuseg_tta.sh

# dutuseg_c - VLM encoder
SEED=1 RUN_IDX=1_vlm TTA_METHOD=tent CONFIG_FILE=tta/cfgs/dutuseg_c/dutuseg_c_tent.yaml TTA_MODE=cont_tta \
TTA_METHOD=tent OUTPUT_DIR=./tta/output_dutuseg_c/tent TTA_LR=1e-2 TTA_BATCH_SIZE=1 TTA_ADAPT_FULL_TRAINABLE_EXCEPT_EXCLUDED=False TTA_ADAPT_SAM_VISUAL_ENCODER=False TTA_ADAPT_SAM_MASK_DECODER=False TTA_ADAPT_SAM_PROMPT_ENCODER=False TTA_ADAPT_VLM_ENCODER=True TTA_ADAPT_SOFT_PROMPTING_TRANSFORMER=False \
sbatch ./slurm_dutuseg_tta.sh

SEED=1 RUN_IDX=2_vlm TTA_METHOD=tent CONFIG_FILE=tta/cfgs/dutuseg_c/dutuseg_c_tent.yaml TTA_MODE=cont_tta \
TTA_METHOD=tent OUTPUT_DIR=./tta/output_dutuseg_c/tent TTA_LR=1e-3 TTA_BATCH_SIZE=1 TTA_ADAPT_FULL_TRAINABLE_EXCEPT_EXCLUDED=False TTA_ADAPT_SAM_VISUAL_ENCODER=False TTA_ADAPT_SAM_MASK_DECODER=False TTA_ADAPT_SAM_PROMPT_ENCODER=False TTA_ADAPT_VLM_ENCODER=True TTA_ADAPT_SOFT_PROMPTING_TRANSFORMER=False \
sbatch ./slurm_dutuseg_tta.sh

SEED=1 RUN_IDX=3_vlm TTA_METHOD=tent CONFIG_FILE=tta/cfgs/dutuseg_c/dutuseg_c_tent.yaml TTA_MODE=cont_tta \
TTA_METHOD=tent OUTPUT_DIR=./tta/output_dutuseg_c/tent TTA_LR=1e-4 TTA_BATCH_SIZE=1 TTA_ADAPT_FULL_TRAINABLE_EXCEPT_EXCLUDED=False TTA_ADAPT_SAM_VISUAL_ENCODER=False TTA_ADAPT_SAM_MASK_DECODER=False TTA_ADAPT_SAM_PROMPT_ENCODER=False TTA_ADAPT_VLM_ENCODER=True TTA_ADAPT_SOFT_PROMPTING_TRANSFORMER=False \
sbatch ./slurm_dutuseg_tta.sh

# dutuseg_c - soft prompting transformer
SEED=1 RUN_IDX=1_soft TTA_METHOD=tent CONFIG_FILE=tta/cfgs/dutuseg_c/dutuseg_c_tent.yaml TTA_MODE=cont_tta \
TTA_METHOD=tent OUTPUT_DIR=./tta/output_dutuseg_c/tent TTA_LR=1e-2 TTA_BATCH_SIZE=1 TTA_ADAPT_FULL_TRAINABLE_EXCEPT_EXCLUDED=False TTA_ADAPT_SAM_VISUAL_ENCODER=False TTA_ADAPT_SAM_MASK_DECODER=False TTA_ADAPT_SAM_PROMPT_ENCODER=False TTA_ADAPT_VLM_ENCODER=False TTA_ADAPT_SOFT_PROMPTING_TRANSFORMER=True \
sbatch ./slurm_dutuseg_tta.sh

SEED=1 RUN_IDX=2_soft TTA_METHOD=tent CONFIG_FILE=tta/cfgs/dutuseg_c/dutuseg_c_tent.yaml TTA_MODE=cont_tta \
TTA_METHOD=tent OUTPUT_DIR=./tta/output_dutuseg_c/tent TTA_LR=1e-3 TTA_BATCH_SIZE=1 TTA_ADAPT_FULL_TRAINABLE_EXCEPT_EXCLUDED=False TTA_ADAPT_SAM_VISUAL_ENCODER=False TTA_ADAPT_SAM_MASK_DECODER=False TTA_ADAPT_SAM_PROMPT_ENCODER=False TTA_ADAPT_VLM_ENCODER=False TTA_ADAPT_SOFT_PROMPTING_TRANSFORMER=True \
sbatch ./slurm_dutuseg_tta.sh

SEED=1 RUN_IDX=3_soft TTA_METHOD=tent CONFIG_FILE=tta/cfgs/dutuseg_c/dutuseg_c_tent.yaml TTA_MODE=cont_tta \
TTA_METHOD=tent OUTPUT_DIR=./tta/output_dutuseg_c/tent TTA_LR=1e-4 TTA_BATCH_SIZE=1 TTA_ADAPT_FULL_TRAINABLE_EXCEPT_EXCLUDED=False TTA_ADAPT_SAM_VISUAL_ENCODER=False TTA_ADAPT_SAM_MASK_DECODER=False TTA_ADAPT_SAM_PROMPT_ENCODER=False TTA_ADAPT_VLM_ENCODER=False TTA_ADAPT_SOFT_PROMPTING_TRANSFORMER=True \
sbatch ./slurm_dutuseg_tta.sh

# -------

# suim_c - baseline (no adaptation)
SEED=1 RUN_IDX=1 TTA_METHOD=tent CONFIG_FILE=tta/cfgs/suim_c/suim_c_tent.yaml TTA_MODE=cont_tta \
TTA_METHOD=tent OUTPUT_DIR=./tta/output_suim_c/tent TTA_LR=1e-2 TTA_BATCH_SIZE=1 TTA_ADAPT_FULL_TRAINABLE_EXCEPT_EXCLUDED=False TTA_ADAPT_SAM_VISUAL_ENCODER=False TTA_ADAPT_SAM_MASK_DECODER=False TTA_ADAPT_SAM_PROMPT_ENCODER=False TTA_ADAPT_VLM_ENCODER=False TTA_ADAPT_SOFT_PROMPTING_TRANSFORMER=False \
sbatch ./slurm_suim_tta.sh

SEED=1 RUN_IDX=2 TTA_METHOD=tent CONFIG_FILE=tta/cfgs/suim_c/suim_c_tent.yaml TTA_MODE=cont_tta \
TTA_METHOD=tent OUTPUT_DIR=./tta/output_suim_c/tent TTA_LR=1e-3 TTA_BATCH_SIZE=1 TTA_ADAPT_FULL_TRAINABLE_EXCEPT_EXCLUDED=False TTA_ADAPT_SAM_VISUAL_ENCODER=False TTA_ADAPT_SAM_MASK_DECODER=False TTA_ADAPT_SAM_PROMPT_ENCODER=False TTA_ADAPT_VLM_ENCODER=False TTA_ADAPT_SOFT_PROMPTING_TRANSFORMER=False \
sbatch ./slurm_suim_tta.sh

SEED=1 RUN_IDX=3 TTA_METHOD=tent CONFIG_FILE=tta/cfgs/suim_c/suim_c_tent.yaml TTA_MODE=cont_tta \
TTA_METHOD=tent OUTPUT_DIR=./tta/output_suim_c/tent TTA_LR=1e-4 TTA_BATCH_SIZE=1 TTA_ADAPT_FULL_TRAINABLE_EXCEPT_EXCLUDED=False TTA_ADAPT_SAM_VISUAL_ENCODER=False TTA_ADAPT_SAM_MASK_DECODER=False TTA_ADAPT_SAM_PROMPT_ENCODER=False TTA_ADAPT_VLM_ENCODER=False TTA_ADAPT_SOFT_PROMPTING_TRANSFORMER=False \
sbatch ./slurm_suim_tta.sh

# suim_c - SAM visual encoder
SEED=1 RUN_IDX=1_vis TTA_METHOD=tent CONFIG_FILE=tta/cfgs/suim_c/suim_c_tent.yaml TTA_MODE=cont_tta \
TTA_METHOD=tent OUTPUT_DIR=./tta/output_suim_c/tent TTA_LR=1e-2 TTA_BATCH_SIZE=1 TTA_ADAPT_FULL_TRAINABLE_EXCEPT_EXCLUDED=False TTA_ADAPT_SAM_VISUAL_ENCODER=True TTA_ADAPT_SAM_MASK_DECODER=False TTA_ADAPT_SAM_PROMPT_ENCODER=False TTA_ADAPT_VLM_ENCODER=False TTA_ADAPT_SOFT_PROMPTING_TRANSFORMER=False \
sbatch ./slurm_suim_tta.sh

SEED=1 RUN_IDX=2_vis TTA_METHOD=tent CONFIG_FILE=tta/cfgs/suim_c/suim_c_tent.yaml TTA_MODE=cont_tta \
TTA_METHOD=tent OUTPUT_DIR=./tta/output_suim_c/tent TTA_LR=1e-3 TTA_BATCH_SIZE=1 TTA_ADAPT_FULL_TRAINABLE_EXCEPT_EXCLUDED=False TTA_ADAPT_SAM_VISUAL_ENCODER=True TTA_ADAPT_SAM_MASK_DECODER=False TTA_ADAPT_SAM_PROMPT_ENCODER=False TTA_ADAPT_VLM_ENCODER=False TTA_ADAPT_SOFT_PROMPTING_TRANSFORMER=False \
sbatch ./slurm_suim_tta.sh

SEED=1 RUN_IDX=3_vis TTA_METHOD=tent CONFIG_FILE=tta/cfgs/suim_c/suim_c_tent.yaml TTA_MODE=cont_tta \
TTA_METHOD=tent OUTPUT_DIR=./tta/output_suim_c/tent TTA_LR=1e-4 TTA_BATCH_SIZE=1 TTA_ADAPT_FULL_TRAINABLE_EXCEPT_EXCLUDED=False TTA_ADAPT_SAM_VISUAL_ENCODER=True TTA_ADAPT_SAM_MASK_DECODER=False TTA_ADAPT_SAM_PROMPT_ENCODER=False TTA_ADAPT_VLM_ENCODER=False TTA_ADAPT_SOFT_PROMPTING_TRANSFORMER=False \
sbatch ./slurm_suim_tta.sh

# suim_c - SAM mask decoder
SEED=1 RUN_IDX=1_decoder TTA_METHOD=tent CONFIG_FILE=tta/cfgs/suim_c/suim_c_tent.yaml TTA_MODE=cont_tta \
TTA_METHOD=tent OUTPUT_DIR=./tta/output_suim_c/tent TTA_LR=1e-2 TTA_BATCH_SIZE=1 TTA_ADAPT_FULL_TRAINABLE_EXCEPT_EXCLUDED=False TTA_ADAPT_SAM_VISUAL_ENCODER=False TTA_ADAPT_SAM_MASK_DECODER=True TTA_ADAPT_SAM_PROMPT_ENCODER=False TTA_ADAPT_VLM_ENCODER=False TTA_ADAPT_SOFT_PROMPTING_TRANSFORMER=False \
sbatch ./slurm_suim_tta.sh

SEED=1 RUN_IDX=2_decoder TTA_METHOD=tent CONFIG_FILE=tta/cfgs/suim_c/suim_c_tent.yaml TTA_MODE=cont_tta \
TTA_METHOD=tent OUTPUT_DIR=./tta/output_suim_c/tent TTA_LR=1e-3 TTA_BATCH_SIZE=1 TTA_ADAPT_FULL_TRAINABLE_EXCEPT_EXCLUDED=False TTA_ADAPT_SAM_VISUAL_ENCODER=False TTA_ADAPT_SAM_MASK_DECODER=True TTA_ADAPT_SAM_PROMPT_ENCODER=False TTA_ADAPT_VLM_ENCODER=False TTA_ADAPT_SOFT_PROMPTING_TRANSFORMER=False \
sbatch ./slurm_suim_tta.sh

SEED=1 RUN_IDX=3_decoder TTA_METHOD=tent CONFIG_FILE=tta/cfgs/suim_c/suim_c_tent.yaml TTA_MODE=cont_tta \
TTA_METHOD=tent OUTPUT_DIR=./tta/output_suim_c/tent TTA_LR=1e-4 TTA_BATCH_SIZE=1 TTA_ADAPT_FULL_TRAINABLE_EXCEPT_EXCLUDED=False TTA_ADAPT_SAM_VISUAL_ENCODER=False TTA_ADAPT_SAM_MASK_DECODER=True TTA_ADAPT_SAM_PROMPT_ENCODER=False TTA_ADAPT_VLM_ENCODER=False TTA_ADAPT_SOFT_PROMPTING_TRANSFORMER=False \
sbatch ./slurm_suim_tta.sh

# suim_c - VLM encoder
SEED=1 RUN_IDX=1_vlm TTA_METHOD=tent CONFIG_FILE=tta/cfgs/suim_c/suim_c_tent.yaml TTA_MODE=cont_tta \
TTA_METHOD=tent OUTPUT_DIR=./tta/output_suim_c/tent TTA_LR=1e-2 TTA_BATCH_SIZE=1 TTA_ADAPT_FULL_TRAINABLE_EXCEPT_EXCLUDED=False TTA_ADAPT_SAM_VISUAL_ENCODER=False TTA_ADAPT_SAM_MASK_DECODER=False TTA_ADAPT_SAM_PROMPT_ENCODER=False TTA_ADAPT_VLM_ENCODER=True TTA_ADAPT_SOFT_PROMPTING_TRANSFORMER=False \
sbatch ./slurm_suim_tta.sh

SEED=1 RUN_IDX=2_vlm TTA_METHOD=tent CONFIG_FILE=tta/cfgs/suim_c/suim_c_tent.yaml TTA_MODE=cont_tta \
TTA_METHOD=tent OUTPUT_DIR=./tta/output_suim_c/tent TTA_LR=1e-3 TTA_BATCH_SIZE=1 TTA_ADAPT_FULL_TRAINABLE_EXCEPT_EXCLUDED=False TTA_ADAPT_SAM_VISUAL_ENCODER=False TTA_ADAPT_SAM_MASK_DECODER=False TTA_ADAPT_SAM_PROMPT_ENCODER=False TTA_ADAPT_VLM_ENCODER=True TTA_ADAPT_SOFT_PROMPTING_TRANSFORMER=False \
sbatch ./slurm_suim_tta.sh

SEED=1 RUN_IDX=3_vlm TTA_METHOD=tent CONFIG_FILE=tta/cfgs/suim_c/suim_c_tent.yaml TTA_MODE=cont_tta \
TTA_METHOD=tent OUTPUT_DIR=./tta/output_suim_c/tent TTA_LR=1e-4 TTA_BATCH_SIZE=1 TTA_ADAPT_FULL_TRAINABLE_EXCEPT_EXCLUDED=False TTA_ADAPT_SAM_VISUAL_ENCODER=False TTA_ADAPT_SAM_MASK_DECODER=False TTA_ADAPT_SAM_PROMPT_ENCODER=False TTA_ADAPT_VLM_ENCODER=True TTA_ADAPT_SOFT_PROMPTING_TRANSFORMER=False \
sbatch ./slurm_suim_tta.sh

# suim_c - soft prompting transformer
SEED=1 RUN_IDX=1_soft TTA_METHOD=tent CONFIG_FILE=tta/cfgs/suim_c/suim_c_tent.yaml TTA_MODE=cont_tta \
TTA_METHOD=tent OUTPUT_DIR=./tta/output_suim_c/tent TTA_LR=1e-2 TTA_BATCH_SIZE=1 TTA_ADAPT_FULL_TRAINABLE_EXCEPT_EXCLUDED=False TTA_ADAPT_SAM_VISUAL_ENCODER=False TTA_ADAPT_SAM_MASK_DECODER=False TTA_ADAPT_SAM_PROMPT_ENCODER=False TTA_ADAPT_VLM_ENCODER=False TTA_ADAPT_SOFT_PROMPTING_TRANSFORMER=True \
sbatch ./slurm_suim_tta.sh

SEED=1 RUN_IDX=2_soft TTA_METHOD=tent CONFIG_FILE=tta/cfgs/suim_c/suim_c_tent.yaml TTA_MODE=cont_tta \
TTA_METHOD=tent OUTPUT_DIR=./tta/output_suim_c/tent TTA_LR=1e-3 TTA_BATCH_SIZE=1 TTA_ADAPT_FULL_TRAINABLE_EXCEPT_EXCLUDED=False TTA_ADAPT_SAM_VISUAL_ENCODER=False TTA_ADAPT_SAM_MASK_DECODER=False TTA_ADAPT_SAM_PROMPT_ENCODER=False TTA_ADAPT_VLM_ENCODER=False TTA_ADAPT_SOFT_PROMPTING_TRANSFORMER=True \
sbatch ./slurm_suim_tta.sh

SEED=1 RUN_IDX=3_soft TTA_METHOD=tent CONFIG_FILE=tta/cfgs/suim_c/suim_c_tent.yaml TTA_MODE=cont_tta \
TTA_METHOD=tent OUTPUT_DIR=./tta/output_suim_c/tent TTA_LR=1e-4 TTA_BATCH_SIZE=1 TTA_ADAPT_FULL_TRAINABLE_EXCEPT_EXCLUDED=False TTA_ADAPT_SAM_VISUAL_ENCODER=False TTA_ADAPT_SAM_MASK_DECODER=False TTA_ADAPT_SAM_PROMPT_ENCODER=False TTA_ADAPT_VLM_ENCODER=False TTA_ADAPT_SOFT_PROMPTING_TRANSFORMER=True \
sbatch ./slurm_suim_tta.sh

# ------
# ------ sar

# dutuseg_c - baseline (no adaptation)
SEED=1 RUN_IDX=1 TTA_METHOD=sar CONFIG_FILE=tta/cfgs/dutuseg_c/dutuseg_c_sar.yaml TTA_MODE=cont_tta \
TTA_METHOD=sar OUTPUT_DIR=./tta/output_dutuseg_c/sar TTA_LR=1e-2 TTA_BATCH_SIZE=1 TTA_ADAPT_FULL_TRAINABLE_EXCEPT_EXCLUDED=False TTA_ADAPT_SAM_VISUAL_ENCODER=False TTA_ADAPT_SAM_MASK_DECODER=False TTA_ADAPT_SAM_PROMPT_ENCODER=False TTA_ADAPT_VLM_ENCODER=False TTA_ADAPT_SOFT_PROMPTING_TRANSFORMER=False \
sbatch ./slurm_dutuseg_tta.sh

SEED=1 RUN_IDX=2 TTA_METHOD=sar CONFIG_FILE=tta/cfgs/dutuseg_c/dutuseg_c_sar.yaml TTA_MODE=cont_tta \
TTA_METHOD=sar OUTPUT_DIR=./tta/output_dutuseg_c/sar TTA_LR=1e-3 TTA_BATCH_SIZE=1 TTA_ADAPT_FULL_TRAINABLE_EXCEPT_EXCLUDED=False TTA_ADAPT_SAM_VISUAL_ENCODER=False TTA_ADAPT_SAM_MASK_DECODER=False TTA_ADAPT_SAM_PROMPT_ENCODER=False TTA_ADAPT_VLM_ENCODER=False TTA_ADAPT_SOFT_PROMPTING_TRANSFORMER=False \
sbatch ./slurm_dutuseg_tta.sh

SEED=1 RUN_IDX=3 TTA_METHOD=sar CONFIG_FILE=tta/cfgs/dutuseg_c/dutuseg_c_sar.yaml TTA_MODE=cont_tta \
TTA_METHOD=sar OUTPUT_DIR=./tta/output_dutuseg_c/sar TTA_LR=1e-4 TTA_BATCH_SIZE=1 TTA_ADAPT_FULL_TRAINABLE_EXCEPT_EXCLUDED=False TTA_ADAPT_SAM_VISUAL_ENCODER=False TTA_ADAPT_SAM_MASK_DECODER=False TTA_ADAPT_SAM_PROMPT_ENCODER=False TTA_ADAPT_VLM_ENCODER=False TTA_ADAPT_SOFT_PROMPTING_TRANSFORMER=False \
sbatch ./slurm_dutuseg_tta.sh

# dutuseg_c - SAM visual encoder
SEED=1 RUN_IDX=1_vis TTA_METHOD=sar CONFIG_FILE=tta/cfgs/dutuseg_c/dutuseg_c_sar.yaml TTA_MODE=cont_tta \
TTA_METHOD=sar OUTPUT_DIR=./tta/output_dutuseg_c/sar TTA_LR=1e-2 TTA_BATCH_SIZE=1 TTA_ADAPT_FULL_TRAINABLE_EXCEPT_EXCLUDED=False TTA_ADAPT_SAM_VISUAL_ENCODER=True TTA_ADAPT_SAM_MASK_DECODER=False TTA_ADAPT_SAM_PROMPT_ENCODER=False TTA_ADAPT_VLM_ENCODER=False TTA_ADAPT_SOFT_PROMPTING_TRANSFORMER=False \
sbatch ./slurm_dutuseg_tta.sh

SEED=1 RUN_IDX=2_vis TTA_METHOD=sar CONFIG_FILE=tta/cfgs/dutuseg_c/dutuseg_c_sar.yaml TTA_MODE=cont_tta \
TTA_METHOD=sar OUTPUT_DIR=./tta/output_dutuseg_c/sar TTA_LR=1e-3 TTA_BATCH_SIZE=1 TTA_ADAPT_FULL_TRAINABLE_EXCEPT_EXCLUDED=False TTA_ADAPT_SAM_VISUAL_ENCODER=True TTA_ADAPT_SAM_MASK_DECODER=False TTA_ADAPT_SAM_PROMPT_ENCODER=False TTA_ADAPT_VLM_ENCODER=False TTA_ADAPT_SOFT_PROMPTING_TRANSFORMER=False \
sbatch ./slurm_dutuseg_tta.sh

SEED=1 RUN_IDX=3_vis TTA_METHOD=sar CONFIG_FILE=tta/cfgs/dutuseg_c/dutuseg_c_sar.yaml TTA_MODE=cont_tta \
TTA_METHOD=sar OUTPUT_DIR=./tta/output_dutuseg_c/sar TTA_LR=1e-4 TTA_BATCH_SIZE=1 TTA_ADAPT_FULL_TRAINABLE_EXCEPT_EXCLUDED=False TTA_ADAPT_SAM_VISUAL_ENCODER=True TTA_ADAPT_SAM_MASK_DECODER=False TTA_ADAPT_SAM_PROMPT_ENCODER=False TTA_ADAPT_VLM_ENCODER=False TTA_ADAPT_SOFT_PROMPTING_TRANSFORMER=False \
sbatch ./slurm_dutuseg_tta.sh

# dutuseg_c - SAM mask decoder
SEED=1 RUN_IDX=1_decoder TTA_METHOD=sar CONFIG_FILE=tta/cfgs/dutuseg_c/dutuseg_c_sar.yaml TTA_MODE=cont_tta \
TTA_METHOD=sar OUTPUT_DIR=./tta/output_dutuseg_c/sar TTA_LR=1e-2 TTA_BATCH_SIZE=1 TTA_ADAPT_FULL_TRAINABLE_EXCEPT_EXCLUDED=False TTA_ADAPT_SAM_VISUAL_ENCODER=False TTA_ADAPT_SAM_MASK_DECODER=True TTA_ADAPT_SAM_PROMPT_ENCODER=False TTA_ADAPT_VLM_ENCODER=False TTA_ADAPT_SOFT_PROMPTING_TRANSFORMER=False \
sbatch ./slurm_dutuseg_tta.sh

SEED=1 RUN_IDX=2_decoder TTA_METHOD=sar CONFIG_FILE=tta/cfgs/dutuseg_c/dutuseg_c_sar.yaml TTA_MODE=cont_tta \
TTA_METHOD=sar OUTPUT_DIR=./tta/output_dutuseg_c/sar TTA_LR=1e-3 TTA_BATCH_SIZE=1 TTA_ADAPT_FULL_TRAINABLE_EXCEPT_EXCLUDED=False TTA_ADAPT_SAM_VISUAL_ENCODER=False TTA_ADAPT_SAM_MASK_DECODER=True TTA_ADAPT_SAM_PROMPT_ENCODER=False TTA_ADAPT_VLM_ENCODER=False TTA_ADAPT_SOFT_PROMPTING_TRANSFORMER=False \
sbatch ./slurm_dutuseg_tta.sh

SEED=1 RUN_IDX=3_decoder TTA_METHOD=sar CONFIG_FILE=tta/cfgs/dutuseg_c/dutuseg_c_sar.yaml TTA_MODE=cont_tta \
TTA_METHOD=sar OUTPUT_DIR=./tta/output_dutuseg_c/sar TTA_LR=1e-4 TTA_BATCH_SIZE=1 TTA_ADAPT_FULL_TRAINABLE_EXCEPT_EXCLUDED=False TTA_ADAPT_SAM_VISUAL_ENCODER=False TTA_ADAPT_SAM_MASK_DECODER=True TTA_ADAPT_SAM_PROMPT_ENCODER=False TTA_ADAPT_VLM_ENCODER=False TTA_ADAPT_SOFT_PROMPTING_TRANSFORMER=False \
sbatch ./slurm_dutuseg_tta.sh

# dutuseg_c - VLM encoder
SEED=1 RUN_IDX=1_vlm TTA_METHOD=sar CONFIG_FILE=tta/cfgs/dutuseg_c/dutuseg_c_sar.yaml TTA_MODE=cont_tta \
TTA_METHOD=sar OUTPUT_DIR=./tta/output_dutuseg_c/sar TTA_LR=1e-2 TTA_BATCH_SIZE=1 TTA_ADAPT_FULL_TRAINABLE_EXCEPT_EXCLUDED=False TTA_ADAPT_SAM_VISUAL_ENCODER=False TTA_ADAPT_SAM_MASK_DECODER=False TTA_ADAPT_SAM_PROMPT_ENCODER=False TTA_ADAPT_VLM_ENCODER=True TTA_ADAPT_SOFT_PROMPTING_TRANSFORMER=False \
sbatch ./slurm_dutuseg_tta.sh

SEED=1 RUN_IDX=2_vlm TTA_METHOD=sar CONFIG_FILE=tta/cfgs/dutuseg_c/dutuseg_c_sar.yaml TTA_MODE=cont_tta \
TTA_METHOD=sar OUTPUT_DIR=./tta/output_dutuseg_c/sar TTA_LR=1e-3 TTA_BATCH_SIZE=1 TTA_ADAPT_FULL_TRAINABLE_EXCEPT_EXCLUDED=False TTA_ADAPT_SAM_VISUAL_ENCODER=False TTA_ADAPT_SAM_MASK_DECODER=False TTA_ADAPT_SAM_PROMPT_ENCODER=False TTA_ADAPT_VLM_ENCODER=True TTA_ADAPT_SOFT_PROMPTING_TRANSFORMER=False \
sbatch ./slurm_dutuseg_tta.sh

SEED=1 RUN_IDX=3_vlm TTA_METHOD=sar CONFIG_FILE=tta/cfgs/dutuseg_c/dutuseg_c_sar.yaml TTA_MODE=cont_tta \
TTA_METHOD=sar OUTPUT_DIR=./tta/output_dutuseg_c/sar TTA_LR=1e-4 TTA_BATCH_SIZE=1 TTA_ADAPT_FULL_TRAINABLE_EXCEPT_EXCLUDED=False TTA_ADAPT_SAM_VISUAL_ENCODER=False TTA_ADAPT_SAM_MASK_DECODER=False TTA_ADAPT_SAM_PROMPT_ENCODER=False TTA_ADAPT_VLM_ENCODER=True TTA_ADAPT_SOFT_PROMPTING_TRANSFORMER=False \
sbatch ./slurm_dutuseg_tta.sh

# dutuseg_c - soft prompting transformer
SEED=1 RUN_IDX=1_soft TTA_METHOD=sar CONFIG_FILE=tta/cfgs/dutuseg_c/dutuseg_c_sar.yaml TTA_MODE=cont_tta \
TTA_METHOD=sar OUTPUT_DIR=./tta/output_dutuseg_c/sar TTA_LR=1e-2 TTA_BATCH_SIZE=1 TTA_ADAPT_FULL_TRAINABLE_EXCEPT_EXCLUDED=False TTA_ADAPT_SAM_VISUAL_ENCODER=False TTA_ADAPT_SAM_MASK_DECODER=False TTA_ADAPT_SAM_PROMPT_ENCODER=False TTA_ADAPT_VLM_ENCODER=False TTA_ADAPT_SOFT_PROMPTING_TRANSFORMER=True \
sbatch ./slurm_dutuseg_tta.sh

SEED=1 RUN_IDX=2_soft TTA_METHOD=sar CONFIG_FILE=tta/cfgs/dutuseg_c/dutuseg_c_sar.yaml TTA_MODE=cont_tta \
TTA_METHOD=sar OUTPUT_DIR=./tta/output_dutuseg_c/sar TTA_LR=1e-3 TTA_BATCH_SIZE=1 TTA_ADAPT_FULL_TRAINABLE_EXCEPT_EXCLUDED=False TTA_ADAPT_SAM_VISUAL_ENCODER=False TTA_ADAPT_SAM_MASK_DECODER=False TTA_ADAPT_SAM_PROMPT_ENCODER=False TTA_ADAPT_VLM_ENCODER=False TTA_ADAPT_SOFT_PROMPTING_TRANSFORMER=True \
sbatch ./slurm_dutuseg_tta.sh

SEED=1 RUN_IDX=3_soft TTA_METHOD=sar CONFIG_FILE=tta/cfgs/dutuseg_c/dutuseg_c_sar.yaml TTA_MODE=cont_tta \
TTA_METHOD=sar OUTPUT_DIR=./tta/output_dutuseg_c/sar TTA_LR=1e-4 TTA_BATCH_SIZE=1 TTA_ADAPT_FULL_TRAINABLE_EXCEPT_EXCLUDED=False TTA_ADAPT_SAM_VISUAL_ENCODER=False TTA_ADAPT_SAM_MASK_DECODER=False TTA_ADAPT_SAM_PROMPT_ENCODER=False TTA_ADAPT_VLM_ENCODER=False TTA_ADAPT_SOFT_PROMPTING_TRANSFORMER=True \
sbatch ./slurm_dutuseg_tta.sh

# -------

# suim_c - baseline (no adaptation)
SEED=1 RUN_IDX=1 TTA_METHOD=sar CONFIG_FILE=tta/cfgs/suim_c/suim_c_sar.yaml TTA_MODE=cont_tta \
TTA_METHOD=sar OUTPUT_DIR=./tta/output_suim_c/sar TTA_LR=1e-2 TTA_BATCH_SIZE=1 TTA_ADAPT_FULL_TRAINABLE_EXCEPT_EXCLUDED=False TTA_ADAPT_SAM_VISUAL_ENCODER=False TTA_ADAPT_SAM_MASK_DECODER=False TTA_ADAPT_SAM_PROMPT_ENCODER=False TTA_ADAPT_VLM_ENCODER=False TTA_ADAPT_SOFT_PROMPTING_TRANSFORMER=False \
sbatch ./slurm_suim_tta.sh

SEED=1 RUN_IDX=2 TTA_METHOD=sar CONFIG_FILE=tta/cfgs/suim_c/suim_c_sar.yaml TTA_MODE=cont_tta \
TTA_METHOD=sar OUTPUT_DIR=./tta/output_suim_c/sar TTA_LR=1e-3 TTA_BATCH_SIZE=1 TTA_ADAPT_FULL_TRAINABLE_EXCEPT_EXCLUDED=False TTA_ADAPT_SAM_VISUAL_ENCODER=False TTA_ADAPT_SAM_MASK_DECODER=False TTA_ADAPT_SAM_PROMPT_ENCODER=False TTA_ADAPT_VLM_ENCODER=False TTA_ADAPT_SOFT_PROMPTING_TRANSFORMER=False \
sbatch ./slurm_suim_tta.sh

SEED=1 RUN_IDX=3 TTA_METHOD=sar CONFIG_FILE=tta/cfgs/suim_c/suim_c_sar.yaml TTA_MODE=cont_tta \
TTA_METHOD=sar OUTPUT_DIR=./tta/output_suim_c/sar TTA_LR=1e-4 TTA_BATCH_SIZE=1 TTA_ADAPT_FULL_TRAINABLE_EXCEPT_EXCLUDED=False TTA_ADAPT_SAM_VISUAL_ENCODER=False TTA_ADAPT_SAM_MASK_DECODER=False TTA_ADAPT_SAM_PROMPT_ENCODER=False TTA_ADAPT_VLM_ENCODER=False TTA_ADAPT_SOFT_PROMPTING_TRANSFORMER=False \
sbatch ./slurm_suim_tta.sh

# suim_c - SAM visual encoder
SEED=1 RUN_IDX=1_vis TTA_METHOD=sar CONFIG_FILE=tta/cfgs/suim_c/suim_c_sar.yaml TTA_MODE=cont_tta \
TTA_METHOD=sar OUTPUT_DIR=./tta/output_suim_c/sar TTA_LR=1e-2 TTA_BATCH_SIZE=1 TTA_ADAPT_FULL_TRAINABLE_EXCEPT_EXCLUDED=False TTA_ADAPT_SAM_VISUAL_ENCODER=True TTA_ADAPT_SAM_MASK_DECODER=False TTA_ADAPT_SAM_PROMPT_ENCODER=False TTA_ADAPT_VLM_ENCODER=False TTA_ADAPT_SOFT_PROMPTING_TRANSFORMER=False \
sbatch ./slurm_suim_tta.sh

SEED=1 RUN_IDX=2_vis TTA_METHOD=sar CONFIG_FILE=tta/cfgs/suim_c/suim_c_sar.yaml TTA_MODE=cont_tta \
TTA_METHOD=sar OUTPUT_DIR=./tta/output_suim_c/sar TTA_LR=1e-3 TTA_BATCH_SIZE=1 TTA_ADAPT_FULL_TRAINABLE_EXCEPT_EXCLUDED=False TTA_ADAPT_SAM_VISUAL_ENCODER=True TTA_ADAPT_SAM_MASK_DECODER=False TTA_ADAPT_SAM_PROMPT_ENCODER=False TTA_ADAPT_VLM_ENCODER=False TTA_ADAPT_SOFT_PROMPTING_TRANSFORMER=False \
sbatch ./slurm_suim_tta.sh

SEED=1 RUN_IDX=3_vis TTA_METHOD=sar CONFIG_FILE=tta/cfgs/suim_c/suim_c_sar.yaml TTA_MODE=cont_tta \
TTA_METHOD=sar OUTPUT_DIR=./tta/output_suim_c/sar TTA_LR=1e-4 TTA_BATCH_SIZE=1 TTA_ADAPT_FULL_TRAINABLE_EXCEPT_EXCLUDED=False TTA_ADAPT_SAM_VISUAL_ENCODER=True TTA_ADAPT_SAM_MASK_DECODER=False TTA_ADAPT_SAM_PROMPT_ENCODER=False TTA_ADAPT_VLM_ENCODER=False TTA_ADAPT_SOFT_PROMPTING_TRANSFORMER=False \
sbatch ./slurm_suim_tta.sh

# suim_c - SAM mask decoder
SEED=1 RUN_IDX=1_decoder TTA_METHOD=sar CONFIG_FILE=tta/cfgs/suim_c/suim_c_sar.yaml TTA_MODE=cont_tta \
TTA_METHOD=sar OUTPUT_DIR=./tta/output_suim_c/sar TTA_LR=1e-2 TTA_BATCH_SIZE=1 TTA_ADAPT_FULL_TRAINABLE_EXCEPT_EXCLUDED=False TTA_ADAPT_SAM_VISUAL_ENCODER=False TTA_ADAPT_SAM_MASK_DECODER=True TTA_ADAPT_SAM_PROMPT_ENCODER=False TTA_ADAPT_VLM_ENCODER=False TTA_ADAPT_SOFT_PROMPTING_TRANSFORMER=False \
sbatch ./slurm_suim_tta.sh

SEED=1 RUN_IDX=2_decoder TTA_METHOD=sar CONFIG_FILE=tta/cfgs/suim_c/suim_c_sar.yaml TTA_MODE=cont_tta \
TTA_METHOD=sar OUTPUT_DIR=./tta/output_suim_c/sar TTA_LR=1e-3 TTA_BATCH_SIZE=1 TTA_ADAPT_FULL_TRAINABLE_EXCEPT_EXCLUDED=False TTA_ADAPT_SAM_VISUAL_ENCODER=False TTA_ADAPT_SAM_MASK_DECODER=True TTA_ADAPT_SAM_PROMPT_ENCODER=False TTA_ADAPT_VLM_ENCODER=False TTA_ADAPT_SOFT_PROMPTING_TRANSFORMER=False \
sbatch ./slurm_suim_tta.sh

SEED=1 RUN_IDX=3_decoder TTA_METHOD=sar CONFIG_FILE=tta/cfgs/suim_c/suim_c_sar.yaml TTA_MODE=cont_tta \
TTA_METHOD=sar OUTPUT_DIR=./tta/output_suim_c/sar TTA_LR=1e-4 TTA_BATCH_SIZE=1 TTA_ADAPT_FULL_TRAINABLE_EXCEPT_EXCLUDED=False TTA_ADAPT_SAM_VISUAL_ENCODER=False TTA_ADAPT_SAM_MASK_DECODER=True TTA_ADAPT_SAM_PROMPT_ENCODER=False TTA_ADAPT_VLM_ENCODER=False TTA_ADAPT_SOFT_PROMPTING_TRANSFORMER=False \
sbatch ./slurm_suim_tta.sh

# suim_c - VLM encoder
SEED=1 RUN_IDX=1_vlm TTA_METHOD=sar CONFIG_FILE=tta/cfgs/suim_c/suim_c_sar.yaml TTA_MODE=cont_tta \
TTA_METHOD=sar OUTPUT_DIR=./tta/output_suim_c/sar TTA_LR=1e-2 TTA_BATCH_SIZE=1 TTA_ADAPT_FULL_TRAINABLE_EXCEPT_EXCLUDED=False TTA_ADAPT_SAM_VISUAL_ENCODER=False TTA_ADAPT_SAM_MASK_DECODER=False TTA_ADAPT_SAM_PROMPT_ENCODER=False TTA_ADAPT_VLM_ENCODER=True TTA_ADAPT_SOFT_PROMPTING_TRANSFORMER=False \
sbatch ./slurm_suim_tta.sh

SEED=1 RUN_IDX=2_vlm TTA_METHOD=sar CONFIG_FILE=tta/cfgs/suim_c/suim_c_sar.yaml TTA_MODE=cont_tta \
TTA_METHOD=sar OUTPUT_DIR=./tta/output_suim_c/sar TTA_LR=1e-3 TTA_BATCH_SIZE=1 TTA_ADAPT_FULL_TRAINABLE_EXCEPT_EXCLUDED=False TTA_ADAPT_SAM_VISUAL_ENCODER=False TTA_ADAPT_SAM_MASK_DECODER=False TTA_ADAPT_SAM_PROMPT_ENCODER=False TTA_ADAPT_VLM_ENCODER=True TTA_ADAPT_SOFT_PROMPTING_TRANSFORMER=False \
sbatch ./slurm_suim_tta.sh

SEED=1 RUN_IDX=3_vlm TTA_METHOD=sar CONFIG_FILE=tta/cfgs/suim_c/suim_c_sar.yaml TTA_MODE=cont_tta \
TTA_METHOD=sar OUTPUT_DIR=./tta/output_suim_c/sar TTA_LR=1e-4 TTA_BATCH_SIZE=1 TTA_ADAPT_FULL_TRAINABLE_EXCEPT_EXCLUDED=False TTA_ADAPT_SAM_VISUAL_ENCODER=False TTA_ADAPT_SAM_MASK_DECODER=False TTA_ADAPT_SAM_PROMPT_ENCODER=False TTA_ADAPT_VLM_ENCODER=True TTA_ADAPT_SOFT_PROMPTING_TRANSFORMER=False \
sbatch ./slurm_suim_tta.sh

# suim_c - soft prompting transformer
SEED=1 RUN_IDX=1_soft TTA_METHOD=sar CONFIG_FILE=tta/cfgs/suim_c/suim_c_sar.yaml TTA_MODE=cont_tta \
TTA_METHOD=sar OUTPUT_DIR=./tta/output_suim_c/sar TTA_LR=1e-2 TTA_BATCH_SIZE=1 TTA_ADAPT_FULL_TRAINABLE_EXCEPT_EXCLUDED=False TTA_ADAPT_SAM_VISUAL_ENCODER=False TTA_ADAPT_SAM_MASK_DECODER=False TTA_ADAPT_SAM_PROMPT_ENCODER=False TTA_ADAPT_VLM_ENCODER=False TTA_ADAPT_SOFT_PROMPTING_TRANSFORMER=True \
sbatch ./slurm_suim_tta.sh

SEED=1 RUN_IDX=2_soft TTA_METHOD=sar CONFIG_FILE=tta/cfgs/suim_c/suim_c_sar.yaml TTA_MODE=cont_tta \
TTA_METHOD=sar OUTPUT_DIR=./tta/output_suim_c/sar TTA_LR=1e-3 TTA_BATCH_SIZE=1 TTA_ADAPT_FULL_TRAINABLE_EXCEPT_EXCLUDED=False TTA_ADAPT_SAM_VISUAL_ENCODER=False TTA_ADAPT_SAM_MASK_DECODER=False TTA_ADAPT_SAM_PROMPT_ENCODER=False TTA_ADAPT_VLM_ENCODER=False TTA_ADAPT_SOFT_PROMPTING_TRANSFORMER=True \
sbatch ./slurm_suim_tta.sh

SEED=1 RUN_IDX=3_soft TTA_METHOD=sar CONFIG_FILE=tta/cfgs/suim_c/suim_c_sar.yaml TTA_MODE=cont_tta \
TTA_METHOD=sar OUTPUT_DIR=./tta/output_suim_c/sar TTA_LR=1e-4 TTA_BATCH_SIZE=1 TTA_ADAPT_FULL_TRAINABLE_EXCEPT_EXCLUDED=False TTA_ADAPT_SAM_VISUAL_ENCODER=False TTA_ADAPT_SAM_MASK_DECODER=False TTA_ADAPT_SAM_PROMPT_ENCODER=False TTA_ADAPT_VLM_ENCODER=False TTA_ADAPT_SOFT_PROMPTING_TRANSFORMER=True \
sbatch ./slurm_suim_tta.sh

# ------
# ------ rdumb

# dutuseg_c - baseline (no adaptation)
SEED=1 RUN_IDX=1 TTA_METHOD=rdumb CONFIG_FILE=tta/cfgs/dutuseg_c/dutuseg_c_rdumb.yaml TTA_MODE=cont_tta \
TTA_METHOD=rdumb OUTPUT_DIR=./tta/output_dutuseg_c/rdumb TTA_LR=1e-2 TTA_BATCH_SIZE=1 TTA_ADAPT_FULL_TRAINABLE_EXCEPT_EXCLUDED=False TTA_ADAPT_SAM_VISUAL_ENCODER=False TTA_ADAPT_SAM_MASK_DECODER=False TTA_ADAPT_SAM_PROMPT_ENCODER=False TTA_ADAPT_VLM_ENCODER=False TTA_ADAPT_SOFT_PROMPTING_TRANSFORMER=False \
sbatch ./slurm_dutuseg_tta.sh

SEED=1 RUN_IDX=2 TTA_METHOD=rdumb CONFIG_FILE=tta/cfgs/dutuseg_c/dutuseg_c_rdumb.yaml TTA_MODE=cont_tta \
TTA_METHOD=rdumb OUTPUT_DIR=./tta/output_dutuseg_c/rdumb TTA_LR=1e-3 TTA_BATCH_SIZE=1 TTA_ADAPT_FULL_TRAINABLE_EXCEPT_EXCLUDED=False TTA_ADAPT_SAM_VISUAL_ENCODER=False TTA_ADAPT_SAM_MASK_DECODER=False TTA_ADAPT_SAM_PROMPT_ENCODER=False TTA_ADAPT_VLM_ENCODER=False TTA_ADAPT_SOFT_PROMPTING_TRANSFORMER=False \
sbatch ./slurm_dutuseg_tta.sh

SEED=1 RUN_IDX=3 TTA_METHOD=rdumb CONFIG_FILE=tta/cfgs/dutuseg_c/dutuseg_c_rdumb.yaml TTA_MODE=cont_tta \
TTA_METHOD=rdumb OUTPUT_DIR=./tta/output_dutuseg_c/rdumb TTA_LR=1e-4 TTA_BATCH_SIZE=1 TTA_ADAPT_FULL_TRAINABLE_EXCEPT_EXCLUDED=False TTA_ADAPT_SAM_VISUAL_ENCODER=False TTA_ADAPT_SAM_MASK_DECODER=False TTA_ADAPT_SAM_PROMPT_ENCODER=False TTA_ADAPT_VLM_ENCODER=False TTA_ADAPT_SOFT_PROMPTING_TRANSFORMER=False \
sbatch ./slurm_dutuseg_tta.sh

# dutuseg_c - SAM visual encoder
SEED=1 RUN_IDX=1_vis TTA_METHOD=rdumb CONFIG_FILE=tta/cfgs/dutuseg_c/dutuseg_c_rdumb.yaml TTA_MODE=cont_tta \
TTA_METHOD=rdumb OUTPUT_DIR=./tta/output_dutuseg_c/rdumb TTA_LR=1e-2 TTA_BATCH_SIZE=1 TTA_ADAPT_FULL_TRAINABLE_EXCEPT_EXCLUDED=False TTA_ADAPT_SAM_VISUAL_ENCODER=True TTA_ADAPT_SAM_MASK_DECODER=False TTA_ADAPT_SAM_PROMPT_ENCODER=False TTA_ADAPT_VLM_ENCODER=False TTA_ADAPT_SOFT_PROMPTING_TRANSFORMER=False \
sbatch ./slurm_dutuseg_tta.sh

SEED=1 RUN_IDX=2_vis TTA_METHOD=rdumb CONFIG_FILE=tta/cfgs/dutuseg_c/dutuseg_c_rdumb.yaml TTA_MODE=cont_tta \
TTA_METHOD=rdumb OUTPUT_DIR=./tta/output_dutuseg_c/rdumb TTA_LR=1e-3 TTA_BATCH_SIZE=1 TTA_ADAPT_FULL_TRAINABLE_EXCEPT_EXCLUDED=False TTA_ADAPT_SAM_VISUAL_ENCODER=True TTA_ADAPT_SAM_MASK_DECODER=False TTA_ADAPT_SAM_PROMPT_ENCODER=False TTA_ADAPT_VLM_ENCODER=False TTA_ADAPT_SOFT_PROMPTING_TRANSFORMER=False \
sbatch ./slurm_dutuseg_tta.sh

SEED=1 RUN_IDX=3_vis TTA_METHOD=rdumb CONFIG_FILE=tta/cfgs/dutuseg_c/dutuseg_c_rdumb.yaml TTA_MODE=cont_tta \
TTA_METHOD=rdumb OUTPUT_DIR=./tta/output_dutuseg_c/rdumb TTA_LR=1e-4 TTA_BATCH_SIZE=1 TTA_ADAPT_FULL_TRAINABLE_EXCEPT_EXCLUDED=False TTA_ADAPT_SAM_VISUAL_ENCODER=True TTA_ADAPT_SAM_MASK_DECODER=False TTA_ADAPT_SAM_PROMPT_ENCODER=False TTA_ADAPT_VLM_ENCODER=False TTA_ADAPT_SOFT_PROMPTING_TRANSFORMER=False \
sbatch ./slurm_dutuseg_tta.sh

# dutuseg_c - SAM mask decoder
SEED=1 RUN_IDX=1_decoder TTA_METHOD=rdumb CONFIG_FILE=tta/cfgs/dutuseg_c/dutuseg_c_rdumb.yaml TTA_MODE=cont_tta \
TTA_METHOD=rdumb OUTPUT_DIR=./tta/output_dutuseg_c/rdumb TTA_LR=1e-2 TTA_BATCH_SIZE=1 TTA_ADAPT_FULL_TRAINABLE_EXCEPT_EXCLUDED=False TTA_ADAPT_SAM_VISUAL_ENCODER=False TTA_ADAPT_SAM_MASK_DECODER=True TTA_ADAPT_SAM_PROMPT_ENCODER=False TTA_ADAPT_VLM_ENCODER=False TTA_ADAPT_SOFT_PROMPTING_TRANSFORMER=False \
sbatch ./slurm_dutuseg_tta.sh

SEED=1 RUN_IDX=2_decoder TTA_METHOD=rdumb CONFIG_FILE=tta/cfgs/dutuseg_c/dutuseg_c_rdumb.yaml TTA_MODE=cont_tta \
TTA_METHOD=rdumb OUTPUT_DIR=./tta/output_dutuseg_c/rdumb TTA_LR=1e-3 TTA_BATCH_SIZE=1 TTA_ADAPT_FULL_TRAINABLE_EXCEPT_EXCLUDED=False TTA_ADAPT_SAM_VISUAL_ENCODER=False TTA_ADAPT_SAM_MASK_DECODER=True TTA_ADAPT_SAM_PROMPT_ENCODER=False TTA_ADAPT_VLM_ENCODER=False TTA_ADAPT_SOFT_PROMPTING_TRANSFORMER=False \
sbatch ./slurm_dutuseg_tta.sh

SEED=1 RUN_IDX=3_decoder TTA_METHOD=rdumb CONFIG_FILE=tta/cfgs/dutuseg_c/dutuseg_c_rdumb.yaml TTA_MODE=cont_tta \
TTA_METHOD=rdumb OUTPUT_DIR=./tta/output_dutuseg_c/rdumb TTA_LR=1e-4 TTA_BATCH_SIZE=1 TTA_ADAPT_FULL_TRAINABLE_EXCEPT_EXCLUDED=False TTA_ADAPT_SAM_VISUAL_ENCODER=False TTA_ADAPT_SAM_MASK_DECODER=True TTA_ADAPT_SAM_PROMPT_ENCODER=False TTA_ADAPT_VLM_ENCODER=False TTA_ADAPT_SOFT_PROMPTING_TRANSFORMER=False \
sbatch ./slurm_dutuseg_tta.sh

# dutuseg_c - VLM encoder
SEED=1 RUN_IDX=1_vlm TTA_METHOD=rdumb CONFIG_FILE=tta/cfgs/dutuseg_c/dutuseg_c_rdumb.yaml TTA_MODE=cont_tta \
TTA_METHOD=rdumb OUTPUT_DIR=./tta/output_dutuseg_c/rdumb TTA_LR=1e-2 TTA_BATCH_SIZE=1 TTA_ADAPT_FULL_TRAINABLE_EXCEPT_EXCLUDED=False TTA_ADAPT_SAM_VISUAL_ENCODER=False TTA_ADAPT_SAM_MASK_DECODER=False TTA_ADAPT_SAM_PROMPT_ENCODER=False TTA_ADAPT_VLM_ENCODER=True TTA_ADAPT_SOFT_PROMPTING_TRANSFORMER=False \
sbatch ./slurm_dutuseg_tta.sh

SEED=1 RUN_IDX=2_vlm TTA_METHOD=rdumb CONFIG_FILE=tta/cfgs/dutuseg_c/dutuseg_c_rdumb.yaml TTA_MODE=cont_tta \
TTA_METHOD=rdumb OUTPUT_DIR=./tta/output_dutuseg_c/rdumb TTA_LR=1e-3 TTA_BATCH_SIZE=1 TTA_ADAPT_FULL_TRAINABLE_EXCEPT_EXCLUDED=False TTA_ADAPT_SAM_VISUAL_ENCODER=False TTA_ADAPT_SAM_MASK_DECODER=False TTA_ADAPT_SAM_PROMPT_ENCODER=False TTA_ADAPT_VLM_ENCODER=True TTA_ADAPT_SOFT_PROMPTING_TRANSFORMER=False \
sbatch ./slurm_dutuseg_tta.sh

SEED=1 RUN_IDX=3_vlm TTA_METHOD=rdumb CONFIG_FILE=tta/cfgs/dutuseg_c/dutuseg_c_rdumb.yaml TTA_MODE=cont_tta \
TTA_METHOD=rdumb OUTPUT_DIR=./tta/output_dutuseg_c/rdumb TTA_LR=1e-4 TTA_BATCH_SIZE=1 TTA_ADAPT_FULL_TRAINABLE_EXCEPT_EXCLUDED=False TTA_ADAPT_SAM_VISUAL_ENCODER=False TTA_ADAPT_SAM_MASK_DECODER=False TTA_ADAPT_SAM_PROMPT_ENCODER=False TTA_ADAPT_VLM_ENCODER=True TTA_ADAPT_SOFT_PROMPTING_TRANSFORMER=False \
sbatch ./slurm_dutuseg_tta.sh

# dutuseg_c - soft prompting transformer
SEED=1 RUN_IDX=1_soft TTA_METHOD=rdumb CONFIG_FILE=tta/cfgs/dutuseg_c/dutuseg_c_rdumb.yaml TTA_MODE=cont_tta \
TTA_METHOD=rdumb OUTPUT_DIR=./tta/output_dutuseg_c/rdumb TTA_LR=1e-2 TTA_BATCH_SIZE=1 TTA_ADAPT_FULL_TRAINABLE_EXCEPT_EXCLUDED=False TTA_ADAPT_SAM_VISUAL_ENCODER=False TTA_ADAPT_SAM_MASK_DECODER=False TTA_ADAPT_SAM_PROMPT_ENCODER=False TTA_ADAPT_VLM_ENCODER=False TTA_ADAPT_SOFT_PROMPTING_TRANSFORMER=True \
sbatch ./slurm_dutuseg_tta.sh

SEED=1 RUN_IDX=2_soft TTA_METHOD=rdumb CONFIG_FILE=tta/cfgs/dutuseg_c/dutuseg_c_rdumb.yaml TTA_MODE=cont_tta \
TTA_METHOD=rdumb OUTPUT_DIR=./tta/output_dutuseg_c/rdumb TTA_LR=1e-3 TTA_BATCH_SIZE=1 TTA_ADAPT_FULL_TRAINABLE_EXCEPT_EXCLUDED=False TTA_ADAPT_SAM_VISUAL_ENCODER=False TTA_ADAPT_SAM_MASK_DECODER=False TTA_ADAPT_SAM_PROMPT_ENCODER=False TTA_ADAPT_VLM_ENCODER=False TTA_ADAPT_SOFT_PROMPTING_TRANSFORMER=True \
sbatch ./slurm_dutuseg_tta.sh

SEED=1 RUN_IDX=3_soft TTA_METHOD=rdumb CONFIG_FILE=tta/cfgs/dutuseg_c/dutuseg_c_rdumb.yaml TTA_MODE=cont_tta \
TTA_METHOD=rdumb OUTPUT_DIR=./tta/output_dutuseg_c/rdumb TTA_LR=1e-4 TTA_BATCH_SIZE=1 TTA_ADAPT_FULL_TRAINABLE_EXCEPT_EXCLUDED=False TTA_ADAPT_SAM_VISUAL_ENCODER=False TTA_ADAPT_SAM_MASK_DECODER=False TTA_ADAPT_SAM_PROMPT_ENCODER=False TTA_ADAPT_VLM_ENCODER=False TTA_ADAPT_SOFT_PROMPTING_TRANSFORMER=True \
sbatch ./slurm_dutuseg_tta.sh

# -------

# suim_c - baseline (no adaptation)
SEED=1 RUN_IDX=1 TTA_METHOD=rdumb CONFIG_FILE=tta/cfgs/suim_c/suim_c_rdumb.yaml TTA_MODE=cont_tta \
TTA_METHOD=rdumb OUTPUT_DIR=./tta/output_suim_c/rdumb TTA_LR=1e-2 TTA_BATCH_SIZE=1 TTA_ADAPT_FULL_TRAINABLE_EXCEPT_EXCLUDED=False TTA_ADAPT_SAM_VISUAL_ENCODER=False TTA_ADAPT_SAM_MASK_DECODER=False TTA_ADAPT_SAM_PROMPT_ENCODER=False TTA_ADAPT_VLM_ENCODER=False TTA_ADAPT_SOFT_PROMPTING_TRANSFORMER=False \
sbatch ./slurm_suim_tta.sh

SEED=1 RUN_IDX=2 TTA_METHOD=rdumb CONFIG_FILE=tta/cfgs/suim_c/suim_c_rdumb.yaml TTA_MODE=cont_tta \
TTA_METHOD=rdumb OUTPUT_DIR=./tta/output_suim_c/rdumb TTA_LR=1e-3 TTA_BATCH_SIZE=1 TTA_ADAPT_FULL_TRAINABLE_EXCEPT_EXCLUDED=False TTA_ADAPT_SAM_VISUAL_ENCODER=False TTA_ADAPT_SAM_MASK_DECODER=False TTA_ADAPT_SAM_PROMPT_ENCODER=False TTA_ADAPT_VLM_ENCODER=False TTA_ADAPT_SOFT_PROMPTING_TRANSFORMER=False \
sbatch ./slurm_suim_tta.sh

SEED=1 RUN_IDX=3 TTA_METHOD=rdumb CONFIG_FILE=tta/cfgs/suim_c/suim_c_rdumb.yaml TTA_MODE=cont_tta \
TTA_METHOD=rdumb OUTPUT_DIR=./tta/output_suim_c/rdumb TTA_LR=1e-4 TTA_BATCH_SIZE=1 TTA_ADAPT_FULL_TRAINABLE_EXCEPT_EXCLUDED=False TTA_ADAPT_SAM_VISUAL_ENCODER=False TTA_ADAPT_SAM_MASK_DECODER=False TTA_ADAPT_SAM_PROMPT_ENCODER=False TTA_ADAPT_VLM_ENCODER=False TTA_ADAPT_SOFT_PROMPTING_TRANSFORMER=False \
sbatch ./slurm_suim_tta.sh

# suim_c - SAM visual encoder
SEED=1 RUN_IDX=1_vis TTA_METHOD=rdumb CONFIG_FILE=tta/cfgs/suim_c/suim_c_rdumb.yaml TTA_MODE=cont_tta \
TTA_METHOD=rdumb OUTPUT_DIR=./tta/output_suim_c/rdumb TTA_LR=1e-2 TTA_BATCH_SIZE=1 TTA_ADAPT_FULL_TRAINABLE_EXCEPT_EXCLUDED=False TTA_ADAPT_SAM_VISUAL_ENCODER=True TTA_ADAPT_SAM_MASK_DECODER=False TTA_ADAPT_SAM_PROMPT_ENCODER=False TTA_ADAPT_VLM_ENCODER=False TTA_ADAPT_SOFT_PROMPTING_TRANSFORMER=False \
sbatch ./slurm_suim_tta.sh

SEED=1 RUN_IDX=2_vis TTA_METHOD=rdumb CONFIG_FILE=tta/cfgs/suim_c/suim_c_rdumb.yaml TTA_MODE=cont_tta \
TTA_METHOD=rdumb OUTPUT_DIR=./tta/output_suim_c/rdumb TTA_LR=1e-3 TTA_BATCH_SIZE=1 TTA_ADAPT_FULL_TRAINABLE_EXCEPT_EXCLUDED=False TTA_ADAPT_SAM_VISUAL_ENCODER=True TTA_ADAPT_SAM_MASK_DECODER=False TTA_ADAPT_SAM_PROMPT_ENCODER=False TTA_ADAPT_VLM_ENCODER=False TTA_ADAPT_SOFT_PROMPTING_TRANSFORMER=False \
sbatch ./slurm_suim_tta.sh

SEED=1 RUN_IDX=3_vis TTA_METHOD=rdumb CONFIG_FILE=tta/cfgs/suim_c/suim_c_rdumb.yaml TTA_MODE=cont_tta \
TTA_METHOD=rdumb OUTPUT_DIR=./tta/output_suim_c/rdumb TTA_LR=1e-4 TTA_BATCH_SIZE=1 TTA_ADAPT_FULL_TRAINABLE_EXCEPT_EXCLUDED=False TTA_ADAPT_SAM_VISUAL_ENCODER=True TTA_ADAPT_SAM_MASK_DECODER=False TTA_ADAPT_SAM_PROMPT_ENCODER=False TTA_ADAPT_VLM_ENCODER=False TTA_ADAPT_SOFT_PROMPTING_TRANSFORMER=False \
sbatch ./slurm_suim_tta.sh

# suim_c - SAM mask decoder
SEED=1 RUN_IDX=1_decoder TTA_METHOD=rdumb CONFIG_FILE=tta/cfgs/suim_c/suim_c_rdumb.yaml TTA_MODE=cont_tta \
TTA_METHOD=rdumb OUTPUT_DIR=./tta/output_suim_c/rdumb TTA_LR=1e-2 TTA_BATCH_SIZE=1 TTA_ADAPT_FULL_TRAINABLE_EXCEPT_EXCLUDED=False TTA_ADAPT_SAM_VISUAL_ENCODER=False TTA_ADAPT_SAM_MASK_DECODER=True TTA_ADAPT_SAM_PROMPT_ENCODER=False TTA_ADAPT_VLM_ENCODER=False TTA_ADAPT_SOFT_PROMPTING_TRANSFORMER=False \
sbatch ./slurm_suim_tta.sh

SEED=1 RUN_IDX=2_decoder TTA_METHOD=rdumb CONFIG_FILE=tta/cfgs/suim_c/suim_c_rdumb.yaml TTA_MODE=cont_tta \
TTA_METHOD=rdumb OUTPUT_DIR=./tta/output_suim_c/rdumb TTA_LR=1e-3 TTA_BATCH_SIZE=1 TTA_ADAPT_FULL_TRAINABLE_EXCEPT_EXCLUDED=False TTA_ADAPT_SAM_VISUAL_ENCODER=False TTA_ADAPT_SAM_MASK_DECODER=True TTA_ADAPT_SAM_PROMPT_ENCODER=False TTA_ADAPT_VLM_ENCODER=False TTA_ADAPT_SOFT_PROMPTING_TRANSFORMER=False \
sbatch ./slurm_suim_tta.sh

SEED=1 RUN_IDX=3_decoder TTA_METHOD=rdumb CONFIG_FILE=tta/cfgs/suim_c/suim_c_rdumb.yaml TTA_MODE=cont_tta \
TTA_METHOD=rdumb OUTPUT_DIR=./tta/output_suim_c/rdumb TTA_LR=1e-4 TTA_BATCH_SIZE=1 TTA_ADAPT_FULL_TRAINABLE_EXCEPT_EXCLUDED=False TTA_ADAPT_SAM_VISUAL_ENCODER=False TTA_ADAPT_SAM_MASK_DECODER=True TTA_ADAPT_SAM_PROMPT_ENCODER=False TTA_ADAPT_VLM_ENCODER=False TTA_ADAPT_SOFT_PROMPTING_TRANSFORMER=False \
sbatch ./slurm_suim_tta.sh

# suim_c - VLM encoder
SEED=1 RUN_IDX=1_vlm TTA_METHOD=rdumb CONFIG_FILE=tta/cfgs/suim_c/suim_c_rdumb.yaml TTA_MODE=cont_tta \
TTA_METHOD=rdumb OUTPUT_DIR=./tta/output_suim_c/rdumb TTA_LR=1e-2 TTA_BATCH_SIZE=1 TTA_ADAPT_FULL_TRAINABLE_EXCEPT_EXCLUDED=False TTA_ADAPT_SAM_VISUAL_ENCODER=False TTA_ADAPT_SAM_MASK_DECODER=False TTA_ADAPT_SAM_PROMPT_ENCODER=False TTA_ADAPT_VLM_ENCODER=True TTA_ADAPT_SOFT_PROMPTING_TRANSFORMER=False \
sbatch ./slurm_suim_tta.sh

SEED=1 RUN_IDX=2_vlm TTA_METHOD=rdumb CONFIG_FILE=tta/cfgs/suim_c/suim_c_rdumb.yaml TTA_MODE=cont_tta \
TTA_METHOD=rdumb OUTPUT_DIR=./tta/output_suim_c/rdumb TTA_LR=1e-3 TTA_BATCH_SIZE=1 TTA_ADAPT_FULL_TRAINABLE_EXCEPT_EXCLUDED=False TTA_ADAPT_SAM_VISUAL_ENCODER=False TTA_ADAPT_SAM_MASK_DECODER=False TTA_ADAPT_SAM_PROMPT_ENCODER=False TTA_ADAPT_VLM_ENCODER=True TTA_ADAPT_SOFT_PROMPTING_TRANSFORMER=False \
sbatch ./slurm_suim_tta.sh

SEED=1 RUN_IDX=3_vlm TTA_METHOD=rdumb CONFIG_FILE=tta/cfgs/suim_c/suim_c_rdumb.yaml TTA_MODE=cont_tta \
TTA_METHOD=rdumb OUTPUT_DIR=./tta/output_suim_c/rdumb TTA_LR=1e-4 TTA_BATCH_SIZE=1 TTA_ADAPT_FULL_TRAINABLE_EXCEPT_EXCLUDED=False TTA_ADAPT_SAM_VISUAL_ENCODER=False TTA_ADAPT_SAM_MASK_DECODER=False TTA_ADAPT_SAM_PROMPT_ENCODER=False TTA_ADAPT_VLM_ENCODER=True TTA_ADAPT_SOFT_PROMPTING_TRANSFORMER=False \
sbatch ./slurm_suim_tta.sh

# suim_c - soft prompting transformer
SEED=1 RUN_IDX=1_soft TTA_METHOD=rdumb CONFIG_FILE=tta/cfgs/suim_c/suim_c_rdumb.yaml TTA_MODE=cont_tta \
TTA_METHOD=rdumb OUTPUT_DIR=./tta/output_suim_c/rdumb TTA_LR=1e-2 TTA_BATCH_SIZE=1 TTA_ADAPT_FULL_TRAINABLE_EXCEPT_EXCLUDED=False TTA_ADAPT_SAM_VISUAL_ENCODER=False TTA_ADAPT_SAM_MASK_DECODER=False TTA_ADAPT_SAM_PROMPT_ENCODER=False TTA_ADAPT_VLM_ENCODER=False TTA_ADAPT_SOFT_PROMPTING_TRANSFORMER=True \
sbatch ./slurm_suim_tta.sh

SEED=1 RUN_IDX=2_soft TTA_METHOD=rdumb CONFIG_FILE=tta/cfgs/suim_c/suim_c_rdumb.yaml TTA_MODE=cont_tta \
TTA_METHOD=rdumb OUTPUT_DIR=./tta/output_suim_c/rdumb TTA_LR=1e-3 TTA_BATCH_SIZE=1 TTA_ADAPT_FULL_TRAINABLE_EXCEPT_EXCLUDED=False TTA_ADAPT_SAM_VISUAL_ENCODER=False TTA_ADAPT_SAM_MASK_DECODER=False TTA_ADAPT_SAM_PROMPT_ENCODER=False TTA_ADAPT_VLM_ENCODER=False TTA_ADAPT_SOFT_PROMPTING_TRANSFORMER=True \
sbatch ./slurm_suim_tta.sh

SEED=1 RUN_IDX=3_soft TTA_METHOD=rdumb CONFIG_FILE=tta/cfgs/suim_c/suim_c_rdumb.yaml TTA_MODE=cont_tta \
TTA_METHOD=rdumb OUTPUT_DIR=./tta/output_suim_c/rdumb TTA_LR=1e-4 TTA_BATCH_SIZE=1 TTA_ADAPT_FULL_TRAINABLE_EXCEPT_EXCLUDED=False TTA_ADAPT_SAM_VISUAL_ENCODER=False TTA_ADAPT_SAM_MASK_DECODER=False TTA_ADAPT_SAM_PROMPT_ENCODER=False TTA_ADAPT_VLM_ENCODER=False TTA_ADAPT_SOFT_PROMPTING_TRANSFORMER=True \
sbatch ./slurm_suim_tta.sh

# ------
# ------ deyo

# dutuseg_c - baseline (no adaptation)
SEED=1 RUN_IDX=1 TTA_METHOD=deyo CONFIG_FILE=tta/cfgs/dutuseg_c/dutuseg_c_deyo.yaml TTA_MODE=cont_tta \
TTA_METHOD=deyo OUTPUT_DIR=./tta/output_dutuseg_c/deyo TTA_LR=1e-2 TTA_BATCH_SIZE=1 TTA_ADAPT_FULL_TRAINABLE_EXCEPT_EXCLUDED=False TTA_ADAPT_SAM_VISUAL_ENCODER=False TTA_ADAPT_SAM_MASK_DECODER=False TTA_ADAPT_SAM_PROMPT_ENCODER=False TTA_ADAPT_VLM_ENCODER=False TTA_ADAPT_SOFT_PROMPTING_TRANSFORMER=False \
sbatch ./slurm_dutuseg_tta.sh

SEED=1 RUN_IDX=2 TTA_METHOD=deyo CONFIG_FILE=tta/cfgs/dutuseg_c/dutuseg_c_deyo.yaml TTA_MODE=cont_tta \
TTA_METHOD=deyo OUTPUT_DIR=./tta/output_dutuseg_c/deyo TTA_LR=1e-3 TTA_BATCH_SIZE=1 TTA_ADAPT_FULL_TRAINABLE_EXCEPT_EXCLUDED=False TTA_ADAPT_SAM_VISUAL_ENCODER=False TTA_ADAPT_SAM_MASK_DECODER=False TTA_ADAPT_SAM_PROMPT_ENCODER=False TTA_ADAPT_VLM_ENCODER=False TTA_ADAPT_SOFT_PROMPTING_TRANSFORMER=False \
sbatch ./slurm_dutuseg_tta.sh

SEED=1 RUN_IDX=3 TTA_METHOD=deyo CONFIG_FILE=tta/cfgs/dutuseg_c/dutuseg_c_deyo.yaml TTA_MODE=cont_tta \
TTA_METHOD=deyo OUTPUT_DIR=./tta/output_dutuseg_c/deyo TTA_LR=1e-4 TTA_BATCH_SIZE=1 TTA_ADAPT_FULL_TRAINABLE_EXCEPT_EXCLUDED=False TTA_ADAPT_SAM_VISUAL_ENCODER=False TTA_ADAPT_SAM_MASK_DECODER=False TTA_ADAPT_SAM_PROMPT_ENCODER=False TTA_ADAPT_VLM_ENCODER=False TTA_ADAPT_SOFT_PROMPTING_TRANSFORMER=False \
sbatch ./slurm_dutuseg_tta.sh

# dutuseg_c - SAM visual encoder
SEED=1 RUN_IDX=1_vis TTA_METHOD=deyo CONFIG_FILE=tta/cfgs/dutuseg_c/dutuseg_c_deyo.yaml TTA_MODE=cont_tta \
TTA_METHOD=deyo OUTPUT_DIR=./tta/output_dutuseg_c/deyo TTA_LR=1e-2 TTA_BATCH_SIZE=1 TTA_ADAPT_FULL_TRAINABLE_EXCEPT_EXCLUDED=False TTA_ADAPT_SAM_VISUAL_ENCODER=True TTA_ADAPT_SAM_MASK_DECODER=False TTA_ADAPT_SAM_PROMPT_ENCODER=False TTA_ADAPT_VLM_ENCODER=False TTA_ADAPT_SOFT_PROMPTING_TRANSFORMER=False \
sbatch ./slurm_dutuseg_tta.sh

SEED=1 RUN_IDX=2_vis TTA_METHOD=deyo CONFIG_FILE=tta/cfgs/dutuseg_c/dutuseg_c_deyo.yaml TTA_MODE=cont_tta \
TTA_METHOD=deyo OUTPUT_DIR=./tta/output_dutuseg_c/deyo TTA_LR=1e-3 TTA_BATCH_SIZE=1 TTA_ADAPT_FULL_TRAINABLE_EXCEPT_EXCLUDED=False TTA_ADAPT_SAM_VISUAL_ENCODER=True TTA_ADAPT_SAM_MASK_DECODER=False TTA_ADAPT_SAM_PROMPT_ENCODER=False TTA_ADAPT_VLM_ENCODER=False TTA_ADAPT_SOFT_PROMPTING_TRANSFORMER=False \
sbatch ./slurm_dutuseg_tta.sh

SEED=1 RUN_IDX=3_vis TTA_METHOD=deyo CONFIG_FILE=tta/cfgs/dutuseg_c/dutuseg_c_deyo.yaml TTA_MODE=cont_tta \
TTA_METHOD=deyo OUTPUT_DIR=./tta/output_dutuseg_c/deyo TTA_LR=1e-4 TTA_BATCH_SIZE=1 TTA_ADAPT_FULL_TRAINABLE_EXCEPT_EXCLUDED=False TTA_ADAPT_SAM_VISUAL_ENCODER=True TTA_ADAPT_SAM_MASK_DECODER=False TTA_ADAPT_SAM_PROMPT_ENCODER=False TTA_ADAPT_VLM_ENCODER=False TTA_ADAPT_SOFT_PROMPTING_TRANSFORMER=False \
sbatch ./slurm_dutuseg_tta.sh

# dutuseg_c - SAM mask decoder
SEED=1 RUN_IDX=1_decoder TTA_METHOD=deyo CONFIG_FILE=tta/cfgs/dutuseg_c/dutuseg_c_deyo.yaml TTA_MODE=cont_tta \
TTA_METHOD=deyo OUTPUT_DIR=./tta/output_dutuseg_c/deyo TTA_LR=1e-2 TTA_BATCH_SIZE=1 TTA_ADAPT_FULL_TRAINABLE_EXCEPT_EXCLUDED=False TTA_ADAPT_SAM_VISUAL_ENCODER=False TTA_ADAPT_SAM_MASK_DECODER=True TTA_ADAPT_SAM_PROMPT_ENCODER=False TTA_ADAPT_VLM_ENCODER=False TTA_ADAPT_SOFT_PROMPTING_TRANSFORMER=False \
sbatch ./slurm_dutuseg_tta.sh

SEED=1 RUN_IDX=2_decoder TTA_METHOD=deyo CONFIG_FILE=tta/cfgs/dutuseg_c/dutuseg_c_deyo.yaml TTA_MODE=cont_tta \
TTA_METHOD=deyo OUTPUT_DIR=./tta/output_dutuseg_c/deyo TTA_LR=1e-3 TTA_BATCH_SIZE=1 TTA_ADAPT_FULL_TRAINABLE_EXCEPT_EXCLUDED=False TTA_ADAPT_SAM_VISUAL_ENCODER=False TTA_ADAPT_SAM_MASK_DECODER=True TTA_ADAPT_SAM_PROMPT_ENCODER=False TTA_ADAPT_VLM_ENCODER=False TTA_ADAPT_SOFT_PROMPTING_TRANSFORMER=False \
sbatch ./slurm_dutuseg_tta.sh

SEED=1 RUN_IDX=3_decoder TTA_METHOD=deyo CONFIG_FILE=tta/cfgs/dutuseg_c/dutuseg_c_deyo.yaml TTA_MODE=cont_tta \
TTA_METHOD=deyo OUTPUT_DIR=./tta/output_dutuseg_c/deyo TTA_LR=1e-4 TTA_BATCH_SIZE=1 TTA_ADAPT_FULL_TRAINABLE_EXCEPT_EXCLUDED=False TTA_ADAPT_SAM_VISUAL_ENCODER=False TTA_ADAPT_SAM_MASK_DECODER=True TTA_ADAPT_SAM_PROMPT_ENCODER=False TTA_ADAPT_VLM_ENCODER=False TTA_ADAPT_SOFT_PROMPTING_TRANSFORMER=False \
sbatch ./slurm_dutuseg_tta.sh

# dutuseg_c - VLM encoder
SEED=1 RUN_IDX=1_vlm TTA_METHOD=deyo CONFIG_FILE=tta/cfgs/dutuseg_c/dutuseg_c_deyo.yaml TTA_MODE=cont_tta \
TTA_METHOD=deyo OUTPUT_DIR=./tta/output_dutuseg_c/deyo TTA_LR=1e-2 TTA_BATCH_SIZE=1 TTA_ADAPT_FULL_TRAINABLE_EXCEPT_EXCLUDED=False TTA_ADAPT_SAM_VISUAL_ENCODER=False TTA_ADAPT_SAM_MASK_DECODER=False TTA_ADAPT_SAM_PROMPT_ENCODER=False TTA_ADAPT_VLM_ENCODER=True TTA_ADAPT_SOFT_PROMPTING_TRANSFORMER=False \
sbatch ./slurm_dutuseg_tta.sh

SEED=1 RUN_IDX=2_vlm TTA_METHOD=deyo CONFIG_FILE=tta/cfgs/dutuseg_c/dutuseg_c_deyo.yaml TTA_MODE=cont_tta \
TTA_METHOD=deyo OUTPUT_DIR=./tta/output_dutuseg_c/deyo TTA_LR=1e-3 TTA_BATCH_SIZE=1 TTA_ADAPT_FULL_TRAINABLE_EXCEPT_EXCLUDED=False TTA_ADAPT_SAM_VISUAL_ENCODER=False TTA_ADAPT_SAM_MASK_DECODER=False TTA_ADAPT_SAM_PROMPT_ENCODER=False TTA_ADAPT_VLM_ENCODER=True TTA_ADAPT_SOFT_PROMPTING_TRANSFORMER=False \
sbatch ./slurm_dutuseg_tta.sh

SEED=1 RUN_IDX=3_vlm TTA_METHOD=deyo CONFIG_FILE=tta/cfgs/dutuseg_c/dutuseg_c_deyo.yaml TTA_MODE=cont_tta \
TTA_METHOD=deyo OUTPUT_DIR=./tta/output_dutuseg_c/deyo TTA_LR=1e-4 TTA_BATCH_SIZE=1 TTA_ADAPT_FULL_TRAINABLE_EXCEPT_EXCLUDED=False TTA_ADAPT_SAM_VISUAL_ENCODER=False TTA_ADAPT_SAM_MASK_DECODER=False TTA_ADAPT_SAM_PROMPT_ENCODER=False TTA_ADAPT_VLM_ENCODER=True TTA_ADAPT_SOFT_PROMPTING_TRANSFORMER=False \
sbatch ./slurm_dutuseg_tta.sh

# dutuseg_c - soft prompting transformer
SEED=1 RUN_IDX=1_soft TTA_METHOD=deyo CONFIG_FILE=tta/cfgs/dutuseg_c/dutuseg_c_deyo.yaml TTA_MODE=cont_tta \
TTA_METHOD=deyo OUTPUT_DIR=./tta/output_dutuseg_c/deyo TTA_LR=1e-2 TTA_BATCH_SIZE=1 TTA_ADAPT_FULL_TRAINABLE_EXCEPT_EXCLUDED=False TTA_ADAPT_SAM_VISUAL_ENCODER=False TTA_ADAPT_SAM_MASK_DECODER=False TTA_ADAPT_SAM_PROMPT_ENCODER=False TTA_ADAPT_VLM_ENCODER=False TTA_ADAPT_SOFT_PROMPTING_TRANSFORMER=True \
sbatch ./slurm_dutuseg_tta.sh

SEED=1 RUN_IDX=2_soft TTA_METHOD=deyo CONFIG_FILE=tta/cfgs/dutuseg_c/dutuseg_c_deyo.yaml TTA_MODE=cont_tta \
TTA_METHOD=deyo OUTPUT_DIR=./tta/output_dutuseg_c/deyo TTA_LR=1e-3 TTA_BATCH_SIZE=1 TTA_ADAPT_FULL_TRAINABLE_EXCEPT_EXCLUDED=False TTA_ADAPT_SAM_VISUAL_ENCODER=False TTA_ADAPT_SAM_MASK_DECODER=False TTA_ADAPT_SAM_PROMPT_ENCODER=False TTA_ADAPT_VLM_ENCODER=False TTA_ADAPT_SOFT_PROMPTING_TRANSFORMER=True \
sbatch ./slurm_dutuseg_tta.sh

SEED=1 RUN_IDX=3_soft TTA_METHOD=deyo CONFIG_FILE=tta/cfgs/dutuseg_c/dutuseg_c_deyo.yaml TTA_MODE=cont_tta \
TTA_METHOD=deyo OUTPUT_DIR=./tta/output_dutuseg_c/deyo TTA_LR=1e-4 TTA_BATCH_SIZE=1 TTA_ADAPT_FULL_TRAINABLE_EXCEPT_EXCLUDED=False TTA_ADAPT_SAM_VISUAL_ENCODER=False TTA_ADAPT_SAM_MASK_DECODER=False TTA_ADAPT_SAM_PROMPT_ENCODER=False TTA_ADAPT_VLM_ENCODER=False TTA_ADAPT_SOFT_PROMPTING_TRANSFORMER=True \
sbatch ./slurm_dutuseg_tta.sh

# -------

# suim_c - baseline (no adaptation)
SEED=1 RUN_IDX=1 TTA_METHOD=deyo CONFIG_FILE=tta/cfgs/suim_c/suim_c_deyo.yaml TTA_MODE=cont_tta \
TTA_METHOD=deyo OUTPUT_DIR=./tta/output_suim_c/deyo TTA_LR=1e-2 TTA_BATCH_SIZE=1 TTA_ADAPT_FULL_TRAINABLE_EXCEPT_EXCLUDED=False TTA_ADAPT_SAM_VISUAL_ENCODER=False TTA_ADAPT_SAM_MASK_DECODER=False TTA_ADAPT_SAM_PROMPT_ENCODER=False TTA_ADAPT_VLM_ENCODER=False TTA_ADAPT_SOFT_PROMPTING_TRANSFORMER=False \
sbatch ./slurm_suim_tta.sh

SEED=1 RUN_IDX=2 TTA_METHOD=deyo CONFIG_FILE=tta/cfgs/suim_c/suim_c_deyo.yaml TTA_MODE=cont_tta \
TTA_METHOD=deyo OUTPUT_DIR=./tta/output_suim_c/deyo TTA_LR=1e-3 TTA_BATCH_SIZE=1 TTA_ADAPT_FULL_TRAINABLE_EXCEPT_EXCLUDED=False TTA_ADAPT_SAM_VISUAL_ENCODER=False TTA_ADAPT_SAM_MASK_DECODER=False TTA_ADAPT_SAM_PROMPT_ENCODER=False TTA_ADAPT_VLM_ENCODER=False TTA_ADAPT_SOFT_PROMPTING_TRANSFORMER=False \
sbatch ./slurm_suim_tta.sh

SEED=1 RUN_IDX=3 TTA_METHOD=deyo CONFIG_FILE=tta/cfgs/suim_c/suim_c_deyo.yaml TTA_MODE=cont_tta \
TTA_METHOD=deyo OUTPUT_DIR=./tta/output_suim_c/deyo TTA_LR=1e-4 TTA_BATCH_SIZE=1 TTA_ADAPT_FULL_TRAINABLE_EXCEPT_EXCLUDED=False TTA_ADAPT_SAM_VISUAL_ENCODER=False TTA_ADAPT_SAM_MASK_DECODER=False TTA_ADAPT_SAM_PROMPT_ENCODER=False TTA_ADAPT_VLM_ENCODER=False TTA_ADAPT_SOFT_PROMPTING_TRANSFORMER=False \
sbatch ./slurm_suim_tta.sh

# suim_c - SAM visual encoder
SEED=1 RUN_IDX=1_vis TTA_METHOD=deyo CONFIG_FILE=tta/cfgs/suim_c/suim_c_deyo.yaml TTA_MODE=cont_tta \
TTA_METHOD=deyo OUTPUT_DIR=./tta/output_suim_c/deyo TTA_LR=1e-2 TTA_BATCH_SIZE=1 TTA_ADAPT_FULL_TRAINABLE_EXCEPT_EXCLUDED=False TTA_ADAPT_SAM_VISUAL_ENCODER=True TTA_ADAPT_SAM_MASK_DECODER=False TTA_ADAPT_SAM_PROMPT_ENCODER=False TTA_ADAPT_VLM_ENCODER=False TTA_ADAPT_SOFT_PROMPTING_TRANSFORMER=False \
sbatch ./slurm_suim_tta.sh

SEED=1 RUN_IDX=2_vis TTA_METHOD=deyo CONFIG_FILE=tta/cfgs/suim_c/suim_c_deyo.yaml TTA_MODE=cont_tta \
TTA_METHOD=deyo OUTPUT_DIR=./tta/output_suim_c/deyo TTA_LR=1e-3 TTA_BATCH_SIZE=1 TTA_ADAPT_FULL_TRAINABLE_EXCEPT_EXCLUDED=False TTA_ADAPT_SAM_VISUAL_ENCODER=True TTA_ADAPT_SAM_MASK_DECODER=False TTA_ADAPT_SAM_PROMPT_ENCODER=False TTA_ADAPT_VLM_ENCODER=False TTA_ADAPT_SOFT_PROMPTING_TRANSFORMER=False \
sbatch ./slurm_suim_tta.sh

SEED=1 RUN_IDX=3_vis TTA_METHOD=deyo CONFIG_FILE=tta/cfgs/suim_c/suim_c_deyo.yaml TTA_MODE=cont_tta \
TTA_METHOD=deyo OUTPUT_DIR=./tta/output_suim_c/deyo TTA_LR=1e-4 TTA_BATCH_SIZE=1 TTA_ADAPT_FULL_TRAINABLE_EXCEPT_EXCLUDED=False TTA_ADAPT_SAM_VISUAL_ENCODER=True TTA_ADAPT_SAM_MASK_DECODER=False TTA_ADAPT_SAM_PROMPT_ENCODER=False TTA_ADAPT_VLM_ENCODER=False TTA_ADAPT_SOFT_PROMPTING_TRANSFORMER=False \
sbatch ./slurm_suim_tta.sh

# suim_c - SAM mask decoder
SEED=1 RUN_IDX=1_decoder TTA_METHOD=deyo CONFIG_FILE=tta/cfgs/suim_c/suim_c_deyo.yaml TTA_MODE=cont_tta \
TTA_METHOD=deyo OUTPUT_DIR=./tta/output_suim_c/deyo TTA_LR=1e-2 TTA_BATCH_SIZE=1 TTA_ADAPT_FULL_TRAINABLE_EXCEPT_EXCLUDED=False TTA_ADAPT_SAM_VISUAL_ENCODER=False TTA_ADAPT_SAM_MASK_DECODER=True TTA_ADAPT_SAM_PROMPT_ENCODER=False TTA_ADAPT_VLM_ENCODER=False TTA_ADAPT_SOFT_PROMPTING_TRANSFORMER=False \
sbatch ./slurm_suim_tta.sh

SEED=1 RUN_IDX=2_decoder TTA_METHOD=deyo CONFIG_FILE=tta/cfgs/suim_c/suim_c_deyo.yaml TTA_MODE=cont_tta \
TTA_METHOD=deyo OUTPUT_DIR=./tta/output_suim_c/deyo TTA_LR=1e-3 TTA_BATCH_SIZE=1 TTA_ADAPT_FULL_TRAINABLE_EXCEPT_EXCLUDED=False TTA_ADAPT_SAM_VISUAL_ENCODER=False TTA_ADAPT_SAM_MASK_DECODER=True TTA_ADAPT_SAM_PROMPT_ENCODER=False TTA_ADAPT_VLM_ENCODER=False TTA_ADAPT_SOFT_PROMPTING_TRANSFORMER=False \
sbatch ./slurm_suim_tta.sh

SEED=1 RUN_IDX=3_decoder TTA_METHOD=deyo CONFIG_FILE=tta/cfgs/suim_c/suim_c_deyo.yaml TTA_MODE=cont_tta \
TTA_METHOD=deyo OUTPUT_DIR=./tta/output_suim_c/deyo TTA_LR=1e-4 TTA_BATCH_SIZE=1 TTA_ADAPT_FULL_TRAINABLE_EXCEPT_EXCLUDED=False TTA_ADAPT_SAM_VISUAL_ENCODER=False TTA_ADAPT_SAM_MASK_DECODER=True TTA_ADAPT_SAM_PROMPT_ENCODER=False TTA_ADAPT_VLM_ENCODER=False TTA_ADAPT_SOFT_PROMPTING_TRANSFORMER=False \
sbatch ./slurm_suim_tta.sh

# suim_c - VLM encoder
SEED=1 RUN_IDX=1_vlm TTA_METHOD=deyo CONFIG_FILE=tta/cfgs/suim_c/suim_c_deyo.yaml TTA_MODE=cont_tta \
TTA_METHOD=deyo OUTPUT_DIR=./tta/output_suim_c/deyo TTA_LR=1e-2 TTA_BATCH_SIZE=1 TTA_ADAPT_FULL_TRAINABLE_EXCEPT_EXCLUDED=False TTA_ADAPT_SAM_VISUAL_ENCODER=False TTA_ADAPT_SAM_MASK_DECODER=False TTA_ADAPT_SAM_PROMPT_ENCODER=False TTA_ADAPT_VLM_ENCODER=True TTA_ADAPT_SOFT_PROMPTING_TRANSFORMER=False \
sbatch ./slurm_suim_tta.sh

SEED=1 RUN_IDX=2_vlm TTA_METHOD=deyo CONFIG_FILE=tta/cfgs/suim_c/suim_c_deyo.yaml TTA_MODE=cont_tta \
TTA_METHOD=deyo OUTPUT_DIR=./tta/output_suim_c/deyo TTA_LR=1e-3 TTA_BATCH_SIZE=1 TTA_ADAPT_FULL_TRAINABLE_EXCEPT_EXCLUDED=False TTA_ADAPT_SAM_VISUAL_ENCODER=False TTA_ADAPT_SAM_MASK_DECODER=False TTA_ADAPT_SAM_PROMPT_ENCODER=False TTA_ADAPT_VLM_ENCODER=True TTA_ADAPT_SOFT_PROMPTING_TRANSFORMER=False \
sbatch ./slurm_suim_tta.sh

SEED=1 RUN_IDX=3_vlm TTA_METHOD=deyo CONFIG_FILE=tta/cfgs/suim_c/suim_c_deyo.yaml TTA_MODE=cont_tta \
TTA_METHOD=deyo OUTPUT_DIR=./tta/output_suim_c/deyo TTA_LR=1e-4 TTA_BATCH_SIZE=1 TTA_ADAPT_FULL_TRAINABLE_EXCEPT_EXCLUDED=False TTA_ADAPT_SAM_VISUAL_ENCODER=False TTA_ADAPT_SAM_MASK_DECODER=False TTA_ADAPT_SAM_PROMPT_ENCODER=False TTA_ADAPT_VLM_ENCODER=True TTA_ADAPT_SOFT_PROMPTING_TRANSFORMER=False \
sbatch ./slurm_suim_tta.sh

# suim_c - soft prompting transformer
SEED=1 RUN_IDX=1_soft TTA_METHOD=deyo CONFIG_FILE=tta/cfgs/suim_c/suim_c_deyo.yaml TTA_MODE=cont_tta \
TTA_METHOD=deyo OUTPUT_DIR=./tta/output_suim_c/deyo TTA_LR=1e-2 TTA_BATCH_SIZE=1 TTA_ADAPT_FULL_TRAINABLE_EXCEPT_EXCLUDED=False TTA_ADAPT_SAM_VISUAL_ENCODER=False TTA_ADAPT_SAM_MASK_DECODER=False TTA_ADAPT_SAM_PROMPT_ENCODER=False TTA_ADAPT_VLM_ENCODER=False TTA_ADAPT_SOFT_PROMPTING_TRANSFORMER=True \
sbatch ./slurm_suim_tta.sh

SEED=1 RUN_IDX=2_soft TTA_METHOD=deyo CONFIG_FILE=tta/cfgs/suim_c/suim_c_deyo.yaml TTA_MODE=cont_tta \
TTA_METHOD=deyo OUTPUT_DIR=./tta/output_suim_c/deyo TTA_LR=1e-3 TTA_BATCH_SIZE=1 TTA_ADAPT_FULL_TRAINABLE_EXCEPT_EXCLUDED=False TTA_ADAPT_SAM_VISUAL_ENCODER=False TTA_ADAPT_SAM_MASK_DECODER=False TTA_ADAPT_SAM_PROMPT_ENCODER=False TTA_ADAPT_VLM_ENCODER=False TTA_ADAPT_SOFT_PROMPTING_TRANSFORMER=True \
sbatch ./slurm_suim_tta.sh

SEED=1 RUN_IDX=3_soft TTA_METHOD=deyo CONFIG_FILE=tta/cfgs/suim_c/suim_c_deyo.yaml TTA_MODE=cont_tta \
TTA_METHOD=deyo OUTPUT_DIR=./tta/output_suim_c/deyo TTA_LR=1e-4 TTA_BATCH_SIZE=1 TTA_ADAPT_FULL_TRAINABLE_EXCEPT_EXCLUDED=False TTA_ADAPT_SAM_VISUAL_ENCODER=False TTA_ADAPT_SAM_MASK_DECODER=False TTA_ADAPT_SAM_PROMPT_ENCODER=False TTA_ADAPT_VLM_ENCODER=False TTA_ADAPT_SOFT_PROMPTING_TRANSFORMER=True \
sbatch ./slurm_suim_tta.sh

# ------
# ------ eata

# dutuseg_c - baseline (no adaptation)
SEED=1 RUN_IDX=1 TTA_METHOD=eata CONFIG_FILE=tta/cfgs/dutuseg_c/dutuseg_c_eata.yaml TTA_MODE=cont_tta \
TTA_METHOD=eata OUTPUT_DIR=./tta/output_dutuseg_c/eata TTA_LR=1e-2 TTA_BATCH_SIZE=1 TTA_ADAPT_FULL_TRAINABLE_EXCEPT_EXCLUDED=False TTA_ADAPT_SAM_VISUAL_ENCODER=False TTA_ADAPT_SAM_MASK_DECODER=False TTA_ADAPT_SAM_PROMPT_ENCODER=False TTA_ADAPT_VLM_ENCODER=False TTA_ADAPT_SOFT_PROMPTING_TRANSFORMER=False \
sbatch ./slurm_dutuseg_tta.sh

SEED=1 RUN_IDX=2 TTA_METHOD=eata CONFIG_FILE=tta/cfgs/dutuseg_c/dutuseg_c_eata.yaml TTA_MODE=cont_tta \
TTA_METHOD=eata OUTPUT_DIR=./tta/output_dutuseg_c/eata TTA_LR=1e-3 TTA_BATCH_SIZE=1 TTA_ADAPT_FULL_TRAINABLE_EXCEPT_EXCLUDED=False TTA_ADAPT_SAM_VISUAL_ENCODER=False TTA_ADAPT_SAM_MASK_DECODER=False TTA_ADAPT_SAM_PROMPT_ENCODER=False TTA_ADAPT_VLM_ENCODER=False TTA_ADAPT_SOFT_PROMPTING_TRANSFORMER=False \
sbatch ./slurm_dutuseg_tta.sh

SEED=1 RUN_IDX=3 TTA_METHOD=eata CONFIG_FILE=tta/cfgs/dutuseg_c/dutuseg_c_eata.yaml TTA_MODE=cont_tta \
TTA_METHOD=eata OUTPUT_DIR=./tta/output_dutuseg_c/eata TTA_LR=1e-4 TTA_BATCH_SIZE=1 TTA_ADAPT_FULL_TRAINABLE_EXCEPT_EXCLUDED=False TTA_ADAPT_SAM_VISUAL_ENCODER=False TTA_ADAPT_SAM_MASK_DECODER=False TTA_ADAPT_SAM_PROMPT_ENCODER=False TTA_ADAPT_VLM_ENCODER=False TTA_ADAPT_SOFT_PROMPTING_TRANSFORMER=False \
sbatch ./slurm_dutuseg_tta.sh

# dutuseg_c - SAM visual encoder
SEED=1 RUN_IDX=1_vis TTA_METHOD=eata CONFIG_FILE=tta/cfgs/dutuseg_c/dutuseg_c_eata.yaml TTA_MODE=cont_tta \
TTA_METHOD=eata OUTPUT_DIR=./tta/output_dutuseg_c/eata TTA_LR=1e-2 TTA_BATCH_SIZE=1 TTA_ADAPT_FULL_TRAINABLE_EXCEPT_EXCLUDED=False TTA_ADAPT_SAM_VISUAL_ENCODER=True TTA_ADAPT_SAM_MASK_DECODER=False TTA_ADAPT_SAM_PROMPT_ENCODER=False TTA_ADAPT_VLM_ENCODER=False TTA_ADAPT_SOFT_PROMPTING_TRANSFORMER=False \
sbatch ./slurm_dutuseg_tta.sh

SEED=1 RUN_IDX=2_vis TTA_METHOD=eata CONFIG_FILE=tta/cfgs/dutuseg_c/dutuseg_c_eata.yaml TTA_MODE=cont_tta \
TTA_METHOD=eata OUTPUT_DIR=./tta/output_dutuseg_c/eata TTA_LR=1e-3 TTA_BATCH_SIZE=1 TTA_ADAPT_FULL_TRAINABLE_EXCEPT_EXCLUDED=False TTA_ADAPT_SAM_VISUAL_ENCODER=True TTA_ADAPT_SAM_MASK_DECODER=False TTA_ADAPT_SAM_PROMPT_ENCODER=False TTA_ADAPT_VLM_ENCODER=False TTA_ADAPT_SOFT_PROMPTING_TRANSFORMER=False \
sbatch ./slurm_dutuseg_tta.sh

SEED=1 RUN_IDX=3_vis TTA_METHOD=eata CONFIG_FILE=tta/cfgs/dutuseg_c/dutuseg_c_eata.yaml TTA_MODE=cont_tta \
TTA_METHOD=eata OUTPUT_DIR=./tta/output_dutuseg_c/eata TTA_LR=1e-4 TTA_BATCH_SIZE=1 TTA_ADAPT_FULL_TRAINABLE_EXCEPT_EXCLUDED=False TTA_ADAPT_SAM_VISUAL_ENCODER=True TTA_ADAPT_SAM_MASK_DECODER=False TTA_ADAPT_SAM_PROMPT_ENCODER=False TTA_ADAPT_VLM_ENCODER=False TTA_ADAPT_SOFT_PROMPTING_TRANSFORMER=False \
sbatch ./slurm_dutuseg_tta.sh

# dutuseg_c - SAM mask decoder
SEED=1 RUN_IDX=1_decoder TTA_METHOD=eata CONFIG_FILE=tta/cfgs/dutuseg_c/dutuseg_c_eata.yaml TTA_MODE=cont_tta \
TTA_METHOD=eata OUTPUT_DIR=./tta/output_dutuseg_c/eata TTA_LR=1e-2 TTA_BATCH_SIZE=1 TTA_ADAPT_FULL_TRAINABLE_EXCEPT_EXCLUDED=False TTA_ADAPT_SAM_VISUAL_ENCODER=False TTA_ADAPT_SAM_MASK_DECODER=True TTA_ADAPT_SAM_PROMPT_ENCODER=False TTA_ADAPT_VLM_ENCODER=False TTA_ADAPT_SOFT_PROMPTING_TRANSFORMER=False \
sbatch ./slurm_dutuseg_tta.sh

SEED=1 RUN_IDX=2_decoder TTA_METHOD=eata CONFIG_FILE=tta/cfgs/dutuseg_c/dutuseg_c_eata.yaml TTA_MODE=cont_tta \
TTA_METHOD=eata OUTPUT_DIR=./tta/output_dutuseg_c/eata TTA_LR=1e-3 TTA_BATCH_SIZE=1 TTA_ADAPT_FULL_TRAINABLE_EXCEPT_EXCLUDED=False TTA_ADAPT_SAM_VISUAL_ENCODER=False TTA_ADAPT_SAM_MASK_DECODER=True TTA_ADAPT_SAM_PROMPT_ENCODER=False TTA_ADAPT_VLM_ENCODER=False TTA_ADAPT_SOFT_PROMPTING_TRANSFORMER=False \
sbatch ./slurm_dutuseg_tta.sh

SEED=1 RUN_IDX=3_decoder TTA_METHOD=eata CONFIG_FILE=tta/cfgs/dutuseg_c/dutuseg_c_eata.yaml TTA_MODE=cont_tta \
TTA_METHOD=eata OUTPUT_DIR=./tta/output_dutuseg_c/eata TTA_LR=1e-4 TTA_BATCH_SIZE=1 TTA_ADAPT_FULL_TRAINABLE_EXCEPT_EXCLUDED=False TTA_ADAPT_SAM_VISUAL_ENCODER=False TTA_ADAPT_SAM_MASK_DECODER=True TTA_ADAPT_SAM_PROMPT_ENCODER=False TTA_ADAPT_VLM_ENCODER=False TTA_ADAPT_SOFT_PROMPTING_TRANSFORMER=False \
sbatch ./slurm_dutuseg_tta.sh

# dutuseg_c - VLM encoder
SEED=1 RUN_IDX=1_vlm TTA_METHOD=eata CONFIG_FILE=tta/cfgs/dutuseg_c/dutuseg_c_eata.yaml TTA_MODE=cont_tta \
TTA_METHOD=eata OUTPUT_DIR=./tta/output_dutuseg_c/eata TTA_LR=1e-2 TTA_BATCH_SIZE=1 TTA_ADAPT_FULL_TRAINABLE_EXCEPT_EXCLUDED=False TTA_ADAPT_SAM_VISUAL_ENCODER=False TTA_ADAPT_SAM_MASK_DECODER=False TTA_ADAPT_SAM_PROMPT_ENCODER=False TTA_ADAPT_VLM_ENCODER=True TTA_ADAPT_SOFT_PROMPTING_TRANSFORMER=False \
sbatch ./slurm_dutuseg_tta.sh

SEED=1 RUN_IDX=2_vlm TTA_METHOD=eata CONFIG_FILE=tta/cfgs/dutuseg_c/dutuseg_c_eata.yaml TTA_MODE=cont_tta \
TTA_METHOD=eata OUTPUT_DIR=./tta/output_dutuseg_c/eata TTA_LR=1e-3 TTA_BATCH_SIZE=1 TTA_ADAPT_FULL_TRAINABLE_EXCEPT_EXCLUDED=False TTA_ADAPT_SAM_VISUAL_ENCODER=False TTA_ADAPT_SAM_MASK_DECODER=False TTA_ADAPT_SAM_PROMPT_ENCODER=False TTA_ADAPT_VLM_ENCODER=True TTA_ADAPT_SOFT_PROMPTING_TRANSFORMER=False \
sbatch ./slurm_dutuseg_tta.sh

SEED=1 RUN_IDX=3_vlm TTA_METHOD=eata CONFIG_FILE=tta/cfgs/dutuseg_c/dutuseg_c_eata.yaml TTA_MODE=cont_tta \
TTA_METHOD=eata OUTPUT_DIR=./tta/output_dutuseg_c/eata TTA_LR=1e-4 TTA_BATCH_SIZE=1 TTA_ADAPT_FULL_TRAINABLE_EXCEPT_EXCLUDED=False TTA_ADAPT_SAM_VISUAL_ENCODER=False TTA_ADAPT_SAM_MASK_DECODER=False TTA_ADAPT_SAM_PROMPT_ENCODER=False TTA_ADAPT_VLM_ENCODER=True TTA_ADAPT_SOFT_PROMPTING_TRANSFORMER=False \
sbatch ./slurm_dutuseg_tta.sh

# dutuseg_c - soft prompting transformer
SEED=1 RUN_IDX=1_soft TTA_METHOD=eata CONFIG_FILE=tta/cfgs/dutuseg_c/dutuseg_c_eata.yaml TTA_MODE=cont_tta \
TTA_METHOD=eata OUTPUT_DIR=./tta/output_dutuseg_c/eata TTA_LR=1e-2 TTA_BATCH_SIZE=1 TTA_ADAPT_FULL_TRAINABLE_EXCEPT_EXCLUDED=False TTA_ADAPT_SAM_VISUAL_ENCODER=False TTA_ADAPT_SAM_MASK_DECODER=False TTA_ADAPT_SAM_PROMPT_ENCODER=False TTA_ADAPT_VLM_ENCODER=False TTA_ADAPT_SOFT_PROMPTING_TRANSFORMER=True \
sbatch ./slurm_dutuseg_tta.sh

SEED=1 RUN_IDX=2_soft TTA_METHOD=eata CONFIG_FILE=tta/cfgs/dutuseg_c/dutuseg_c_eata.yaml TTA_MODE=cont_tta \
TTA_METHOD=eata OUTPUT_DIR=./tta/output_dutuseg_c/eata TTA_LR=1e-3 TTA_BATCH_SIZE=1 TTA_ADAPT_FULL_TRAINABLE_EXCEPT_EXCLUDED=False TTA_ADAPT_SAM_VISUAL_ENCODER=False TTA_ADAPT_SAM_MASK_DECODER=False TTA_ADAPT_SAM_PROMPT_ENCODER=False TTA_ADAPT_VLM_ENCODER=False TTA_ADAPT_SOFT_PROMPTING_TRANSFORMER=True \
sbatch ./slurm_dutuseg_tta.sh

SEED=1 RUN_IDX=3_soft TTA_METHOD=eata CONFIG_FILE=tta/cfgs/dutuseg_c/dutuseg_c_eata.yaml TTA_MODE=cont_tta \
TTA_METHOD=eata OUTPUT_DIR=./tta/output_dutuseg_c/eata TTA_LR=1e-4 TTA_BATCH_SIZE=1 TTA_ADAPT_FULL_TRAINABLE_EXCEPT_EXCLUDED=False TTA_ADAPT_SAM_VISUAL_ENCODER=False TTA_ADAPT_SAM_MASK_DECODER=False TTA_ADAPT_SAM_PROMPT_ENCODER=False TTA_ADAPT_VLM_ENCODER=False TTA_ADAPT_SOFT_PROMPTING_TRANSFORMER=True \
sbatch ./slurm_dutuseg_tta.sh

# -------

# suim_c - baseline (no adaptation)
SEED=1 RUN_IDX=1 TTA_METHOD=eata CONFIG_FILE=tta/cfgs/suim_c/suim_c_eata.yaml TTA_MODE=cont_tta \
TTA_METHOD=eata OUTPUT_DIR=./tta/output_suim_c/eata TTA_LR=1e-2 TTA_BATCH_SIZE=1 TTA_ADAPT_FULL_TRAINABLE_EXCEPT_EXCLUDED=False TTA_ADAPT_SAM_VISUAL_ENCODER=False TTA_ADAPT_SAM_MASK_DECODER=False TTA_ADAPT_SAM_PROMPT_ENCODER=False TTA_ADAPT_VLM_ENCODER=False TTA_ADAPT_SOFT_PROMPTING_TRANSFORMER=False \
sbatch ./slurm_suim_tta.sh

SEED=1 RUN_IDX=2 TTA_METHOD=eata CONFIG_FILE=tta/cfgs/suim_c/suim_c_eata.yaml TTA_MODE=cont_tta \
TTA_METHOD=eata OUTPUT_DIR=./tta/output_suim_c/eata TTA_LR=1e-3 TTA_BATCH_SIZE=1 TTA_ADAPT_FULL_TRAINABLE_EXCEPT_EXCLUDED=False TTA_ADAPT_SAM_VISUAL_ENCODER=False TTA_ADAPT_SAM_MASK_DECODER=False TTA_ADAPT_SAM_PROMPT_ENCODER=False TTA_ADAPT_VLM_ENCODER=False TTA_ADAPT_SOFT_PROMPTING_TRANSFORMER=False \
sbatch ./slurm_suim_tta.sh

SEED=1 RUN_IDX=3 TTA_METHOD=eata CONFIG_FILE=tta/cfgs/suim_c/suim_c_eata.yaml TTA_MODE=cont_tta \
TTA_METHOD=eata OUTPUT_DIR=./tta/output_suim_c/eata TTA_LR=1e-4 TTA_BATCH_SIZE=1 TTA_ADAPT_FULL_TRAINABLE_EXCEPT_EXCLUDED=False TTA_ADAPT_SAM_VISUAL_ENCODER=False TTA_ADAPT_SAM_MASK_DECODER=False TTA_ADAPT_SAM_PROMPT_ENCODER=False TTA_ADAPT_VLM_ENCODER=False TTA_ADAPT_SOFT_PROMPTING_TRANSFORMER=False \
sbatch ./slurm_suim_tta.sh

# suim_c - SAM visual encoder
SEED=1 RUN_IDX=1_vis TTA_METHOD=eata CONFIG_FILE=tta/cfgs/suim_c/suim_c_eata.yaml TTA_MODE=cont_tta \
TTA_METHOD=eata OUTPUT_DIR=./tta/output_suim_c/eata TTA_LR=1e-2 TTA_BATCH_SIZE=1 TTA_ADAPT_FULL_TRAINABLE_EXCEPT_EXCLUDED=False TTA_ADAPT_SAM_VISUAL_ENCODER=True TTA_ADAPT_SAM_MASK_DECODER=False TTA_ADAPT_SAM_PROMPT_ENCODER=False TTA_ADAPT_VLM_ENCODER=False TTA_ADAPT_SOFT_PROMPTING_TRANSFORMER=False \
sbatch ./slurm_suim_tta.sh

SEED=1 RUN_IDX=2_vis TTA_METHOD=eata CONFIG_FILE=tta/cfgs/suim_c/suim_c_eata.yaml TTA_MODE=cont_tta \
TTA_METHOD=eata OUTPUT_DIR=./tta/output_suim_c/eata TTA_LR=1e-3 TTA_BATCH_SIZE=1 TTA_ADAPT_FULL_TRAINABLE_EXCEPT_EXCLUDED=False TTA_ADAPT_SAM_VISUAL_ENCODER=True TTA_ADAPT_SAM_MASK_DECODER=False TTA_ADAPT_SAM_PROMPT_ENCODER=False TTA_ADAPT_VLM_ENCODER=False TTA_ADAPT_SOFT_PROMPTING_TRANSFORMER=False \
sbatch ./slurm_suim_tta.sh

SEED=1 RUN_IDX=3_vis TTA_METHOD=eata CONFIG_FILE=tta/cfgs/suim_c/suim_c_eata.yaml TTA_MODE=cont_tta \
TTA_METHOD=eata OUTPUT_DIR=./tta/output_suim_c/eata TTA_LR=1e-4 TTA_BATCH_SIZE=1 TTA_ADAPT_FULL_TRAINABLE_EXCEPT_EXCLUDED=False TTA_ADAPT_SAM_VISUAL_ENCODER=True TTA_ADAPT_SAM_MASK_DECODER=False TTA_ADAPT_SAM_PROMPT_ENCODER=False TTA_ADAPT_VLM_ENCODER=False TTA_ADAPT_SOFT_PROMPTING_TRANSFORMER=False \
sbatch ./slurm_suim_tta.sh

# suim_c - SAM mask decoder
SEED=1 RUN_IDX=1_decoder TTA_METHOD=eata CONFIG_FILE=tta/cfgs/suim_c/suim_c_eata.yaml TTA_MODE=cont_tta \
TTA_METHOD=eata OUTPUT_DIR=./tta/output_suim_c/eata TTA_LR=1e-2 TTA_BATCH_SIZE=1 TTA_ADAPT_FULL_TRAINABLE_EXCEPT_EXCLUDED=False TTA_ADAPT_SAM_VISUAL_ENCODER=False TTA_ADAPT_SAM_MASK_DECODER=True TTA_ADAPT_SAM_PROMPT_ENCODER=False TTA_ADAPT_VLM_ENCODER=False TTA_ADAPT_SOFT_PROMPTING_TRANSFORMER=False \
sbatch ./slurm_suim_tta.sh

SEED=1 RUN_IDX=2_decoder TTA_METHOD=eata CONFIG_FILE=tta/cfgs/suim_c/suim_c_eata.yaml TTA_MODE=cont_tta \
TTA_METHOD=eata OUTPUT_DIR=./tta/output_suim_c/eata TTA_LR=1e-3 TTA_BATCH_SIZE=1 TTA_ADAPT_FULL_TRAINABLE_EXCEPT_EXCLUDED=False TTA_ADAPT_SAM_VISUAL_ENCODER=False TTA_ADAPT_SAM_MASK_DECODER=True TTA_ADAPT_SAM_PROMPT_ENCODER=False TTA_ADAPT_VLM_ENCODER=False TTA_ADAPT_SOFT_PROMPTING_TRANSFORMER=False \
sbatch ./slurm_suim_tta.sh

SEED=1 RUN_IDX=3_decoder TTA_METHOD=eata CONFIG_FILE=tta/cfgs/suim_c/suim_c_eata.yaml TTA_MODE=cont_tta \
TTA_METHOD=eata OUTPUT_DIR=./tta/output_suim_c/eata TTA_LR=1e-4 TTA_BATCH_SIZE=1 TTA_ADAPT_FULL_TRAINABLE_EXCEPT_EXCLUDED=False TTA_ADAPT_SAM_VISUAL_ENCODER=False TTA_ADAPT_SAM_MASK_DECODER=True TTA_ADAPT_SAM_PROMPT_ENCODER=False TTA_ADAPT_VLM_ENCODER=False TTA_ADAPT_SOFT_PROMPTING_TRANSFORMER=False \
sbatch ./slurm_suim_tta.sh

# suim_c - VLM encoder
SEED=1 RUN_IDX=1_vlm TTA_METHOD=eata CONFIG_FILE=tta/cfgs/suim_c/suim_c_eata.yaml TTA_MODE=cont_tta \
TTA_METHOD=eata OUTPUT_DIR=./tta/output_suim_c/eata TTA_LR=1e-2 TTA_BATCH_SIZE=1 TTA_ADAPT_FULL_TRAINABLE_EXCEPT_EXCLUDED=False TTA_ADAPT_SAM_VISUAL_ENCODER=False TTA_ADAPT_SAM_MASK_DECODER=False TTA_ADAPT_SAM_PROMPT_ENCODER=False TTA_ADAPT_VLM_ENCODER=True TTA_ADAPT_SOFT_PROMPTING_TRANSFORMER=False \
sbatch ./slurm_suim_tta.sh

SEED=1 RUN_IDX=2_vlm TTA_METHOD=eata CONFIG_FILE=tta/cfgs/suim_c/suim_c_eata.yaml TTA_MODE=cont_tta \
TTA_METHOD=eata OUTPUT_DIR=./tta/output_suim_c/eata TTA_LR=1e-3 TTA_BATCH_SIZE=1 TTA_ADAPT_FULL_TRAINABLE_EXCEPT_EXCLUDED=False TTA_ADAPT_SAM_VISUAL_ENCODER=False TTA_ADAPT_SAM_MASK_DECODER=False TTA_ADAPT_SAM_PROMPT_ENCODER=False TTA_ADAPT_VLM_ENCODER=True TTA_ADAPT_SOFT_PROMPTING_TRANSFORMER=False \
sbatch ./slurm_suim_tta.sh

SEED=1 RUN_IDX=3_vlm TTA_METHOD=eata CONFIG_FILE=tta/cfgs/suim_c/suim_c_eata.yaml TTA_MODE=cont_tta \
TTA_METHOD=eata OUTPUT_DIR=./tta/output_suim_c/eata TTA_LR=1e-4 TTA_BATCH_SIZE=1 TTA_ADAPT_FULL_TRAINABLE_EXCEPT_EXCLUDED=False TTA_ADAPT_SAM_VISUAL_ENCODER=False TTA_ADAPT_SAM_MASK_DECODER=False TTA_ADAPT_SAM_PROMPT_ENCODER=False TTA_ADAPT_VLM_ENCODER=True TTA_ADAPT_SOFT_PROMPTING_TRANSFORMER=False \
sbatch ./slurm_suim_tta.sh

# suim_c - soft prompting transformer
SEED=1 RUN_IDX=1_soft TTA_METHOD=eata CONFIG_FILE=tta/cfgs/suim_c/suim_c_eata.yaml TTA_MODE=cont_tta \
TTA_METHOD=eata OUTPUT_DIR=./tta/output_suim_c/eata TTA_LR=1e-2 TTA_BATCH_SIZE=1 TTA_ADAPT_FULL_TRAINABLE_EXCEPT_EXCLUDED=False TTA_ADAPT_SAM_VISUAL_ENCODER=False TTA_ADAPT_SAM_MASK_DECODER=False TTA_ADAPT_SAM_PROMPT_ENCODER=False TTA_ADAPT_VLM_ENCODER=False TTA_ADAPT_SOFT_PROMPTING_TRANSFORMER=True \
sbatch ./slurm_suim_tta.sh

SEED=1 RUN_IDX=2_soft TTA_METHOD=eata CONFIG_FILE=tta/cfgs/suim_c/suim_c_eata.yaml TTA_MODE=cont_tta \
TTA_METHOD=eata OUTPUT_DIR=./tta/output_suim_c/eata TTA_LR=1e-3 TTA_BATCH_SIZE=1 TTA_ADAPT_FULL_TRAINABLE_EXCEPT_EXCLUDED=False TTA_ADAPT_SAM_VISUAL_ENCODER=False TTA_ADAPT_SAM_MASK_DECODER=False TTA_ADAPT_SAM_PROMPT_ENCODER=False TTA_ADAPT_VLM_ENCODER=False TTA_ADAPT_SOFT_PROMPTING_TRANSFORMER=True \
sbatch ./slurm_suim_tta.sh

SEED=1 RUN_IDX=3_soft TTA_METHOD=eata CONFIG_FILE=tta/cfgs/suim_c/suim_c_eata.yaml TTA_MODE=cont_tta \
TTA_METHOD=eata OUTPUT_DIR=./tta/output_suim_c/eata TTA_LR=1e-4 TTA_BATCH_SIZE=1 TTA_ADAPT_FULL_TRAINABLE_EXCEPT_EXCLUDED=False TTA_ADAPT_SAM_VISUAL_ENCODER=False TTA_ADAPT_SAM_MASK_DECODER=False TTA_ADAPT_SAM_PROMPT_ENCODER=False TTA_ADAPT_VLM_ENCODER=False TTA_ADAPT_SOFT_PROMPTING_TRANSFORMER=True \
sbatch ./slurm_suim_tta.sh

